### ISSUE TITLE
feat: Capture and log crash of WebView to Firebase Crashlytics

### ISSUE THREAD

**Issue by mesqueeb** [capawesome-team/capacitor-firebase#100]
We did extensive research on how to capture the fact that the webview crashes, which happens often for us.
We might have 1 or a couple of memory leaks...?

But Firebase crashlytics didn't catch webview crashes for us, and the actual app itself never crashed.

closest thing we found to catching a webview crash:
https://github.com/ionic-team/capacitor/issues/2379 

Reading this thread, I assume we'll need to tweak these lines to add some native code to catch the crash:
https://github.com/ionic-team/capacitor/blob/0a25cce21f935c0d18cdeb9b0e04a9b6145f2072/ios/Capacitor/Capacitor/CAPBridgeViewController.swift#L279-L281

Do you think it's possible in here for your crashlytics plugin to capture this crash and make a manual log to Firebase Crashlytics?

**Comment by robingenz** [comment]
@mesqueeb That's correct, Firebase can only capture app crashes, not webview crashes/reloads.

Interesting idea. I will have a look at that. But I won't get to it for a few weeks.

**Comment by robingenz** [comment]
In order for Crashlytics to capture the WebView crash, the app must actually crash. For this, the following changes to `@capacitor/ios` are necessary: https://github.com/robingenz/capacitor-firebase-issue-100/commit/cf7e20a98d8a34319ac21fd9a0c60e90010862ea

There is already a discussion about this change: https://github.com/ionic-team/capacitor/issues/2379
Unfortunately, there is currently no other way to actually capture a WebView crash with Crashlytics.

Thanks to [cycraft](https://github.com/cycraft) for sponsoring this issues!
