### ISSUE TITLE
bug: tokenReceived event returns wrong token

### ISSUE THREAD

**Issue by phal0r** [capawesome-team/capacitor-firebase#148]
**Plugin(s):**
- @capacitor-firebase/messaging@0.5.0

**Platform(s):**
- ios

**Current behavior:**
Currently the tokenReceived event is triggered, when the app receives an APNS token and when getToken is invoked from js land. The first emit returns the APNS token instead of the Firebase token, which is a bug. The second invocation is probably not the right place, because the token is requested by the user anyways (and returned in the promises).

Additionally, the suggested method to get notified on Firebase token change is not yet implemented.

**Expected behavior:**
Always return the correct token and trigger tokenReceived, where it makes sense:
- on cold app starts
- when the token actually changes due to expiration or other firebase internal events

**Steps to reproduce:**
build and run the app.

**Related code:**

**Other information:**

**Capacitor doctor:**

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

Installed Dependencies:

  @capacitor/cli: 3.5.1
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

**Comment by phal0r** [comment]
Ah, I totally missed #144. Yeah, this is, what I wanted to prepare :)

**Comment by robingenz** [comment]
Okay, in that case I'll close this issue. 🙂 
Let me know if there is anything else.
