### ISSUE TITLE
bug(authentication): `displayName` is missing when signing in with Apple on iOS using `skipNativeAuth`

### ISSUE THREAD

**Issue by robingenz** [capawesome-team/capacitor-firebase#155]
**Plugin(s):**

- `@capacitor-firebase/authentication`

**Platform(s):**

- iOS

**Current behavior:**

See https://github.com/capawesome-team/capacitor-firebase/issues/30#issuecomment-1135213338.
The  `displayName` is missing when signing in with Apple on iOS (using `skipNativeAuth`).
This is related to https://github.com/firebase/firebase-ios-sdk/issues/4393.
We should try to find a workaround.

**Expected behavior:**

The `displayName` should be available at least on the first login.

**Comment by typefox09** [comment]
One workaround could be to use Firebase's new Auth blocking functions (this solution lies outside this SDK) 

Using the beforeUserCreated cloud function trigger, we can access the users name from the Apple auth token, and then use this to update Firebase's native displayName name field.  

I haven't tested this yet, however after reading the docs below, I believe it will be possible.

https://firebase.google.com/docs/functions/beta/auth-blocking-events

**Comment by fryiee** [comment]
> One workaround could be to use Firebase's new Auth blocking functions (this solution lies outside this SDK)
> 
> Using the beforeUserCreated cloud function trigger, we can access the users name from the Apple auth token, and then use this to update Firebase's native displayName name field.
> 
> I haven't tested this yet, however after reading the docs below, I believe it will be possible.
> 
> https://firebase.google.com/docs/functions/beta/auth-blocking-events

Not sure I love the idea of forcing a Cloud Function for this. The Apple credential generated does already return the value, but getting it downstream might be tricky until that issue referenced above has a clearer solution.

**Comment by fryiee** [comment]
@robingenz have you had any more thoughts on this? There's a patch for Flutterfire that someone posted in the parent issue which might be a good starting point? **https://gist.github.com/mbevin/393597735c67575eccf0858c4c17168d**

**Comment by robingenz** [comment]
Not yet, I was busy with the Capacitor 4 update and another project. Next week I wanted to find a solution and close this issue. Thanks for the hint. I will have a look.

**Comment by robingenz** [comment]
You can now test the dev version:
```
npm i @capacitor-firebase/authentication@1.0.0-dev.22fb97c.1661680412
```

Example:
```ts
const signInWithApple = async () => {
  const result = await FirebaseAuthentication.signInWithApple();
  return result.user.displayName;
};
```

The username is provided by Apple only at the first login.

**Comment by typefox09** [comment]
Have tried using the updated dev package, it doesn't seem to be working:

const result = await FirebaseAuthentication.signInWithApple()

result.user is undefined?

**Comment by robingenz** [comment]
No, I have not tested it yet. I will test all commits together this week before I release the next version.

**Comment by typefox09** [comment]
I'm not an expert with Swift but the issue might be coming from the below function:

When using skipNativeAuth I think you're not passing the user credential (as you're not signing in on the native layer).

That means the following will never return the display name as the user is being passed as nil:

`    public static func createUserResult(_ user: User?, displayName: String?) -> JSObject? {
        guard let user = user else {
            return nil
        }
        var result = JSObject()
        result["displayName"] = displayName ?? user.displayName
        result["email"] = user.email
        result["emailVerified"] = user.isEmailVerified
        result["isAnonymous"] = user.isAnonymous
        result["phoneNumber"] = user.phoneNumber
        result["photoUrl"] = user.photoURL?.absoluteString
        result["providerId"] = user.providerID
        result["tenantId"] = user.tenantID
        result["uid"] = user.uid
        return result
    }
`

**Comment by robingenz** [comment]
@typefox09 Yes, i found it.
Can you try it again with this version?

```
npm i @capacitor-firebase/authentication@1.0.0-dev.ea84699.1661853012
```

**Comment by typefox09** [comment]
Yep, can confirm that works, nice :).

**Comment by robingenz** [comment]
Thank you for testing!
