### ISSUE TITLE
bug(messaging): lastRemoteMessage not stored on iOS

### ISSUE THREAD

**Issue by EinfachHans** [capawesome-team/capacitor-firebase#162]
**Plugin(s):**

- messaging

**Platform(s):**

- iOS

**Current behavior:**

When you click on a push notification while the app is closed you will not receive the callback. This is because the ios implementation of this plugin doesn't store the `lastRemoteMessage` before registration, while the android side does.

**Expected behavior:**

iOS should also store the last push message until the plugin is registered and send it afterwards to catch the situation described above

**Other information:**

Android Code: https://github.com/capawesome-team/capacitor-firebase/blob/b8232674f885350e324f866fda43796c968585a6/packages/messaging/android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/messaging/FirebaseMessagingPlugin.java#L75

**Comment by robingenz** [comment]
Thank you @EinfachHans! I will take a look soon.

**Comment by robingenz** [comment]
Closed by a6a0720b9151492bbcf029bd26f8907030bd3359.

**Comment by robingenz** [comment]
@EinfachHans Oops, I totally forgot. 😄 It will be released in 5 minutes, thank you!
