### ISSUE TITLE
bug: Add support for Capacitor 4

### ISSUE THREAD

**Issue by RRGT19** [capawesome-team/capacitor-firebase#166]
**Plugin(s):**
All

**Current behavior:**
When upgrading from Capacitor 3 to Capacitor 4, `npm install` fails because of peer dependencies pointing to Capacitor 3.

**Expected behavior:**
Install should not return any dependency error.

**Other information:**
Capacitor 4 has been released recently, see releases [here](https://github.com/ionic-team/capacitor/releases). The `peerDependencies` of all your plugins need an update.

**Comment by robingenz** [comment]
Closed as duplicate of #125
