### ISSUE TITLE
bug: Capacitor-Firebase plugins are not compatible with AngularFire

### ISSUE THREAD

**Issue by Squix** [capawesome-team/capacitor-firebase#167]
**Plugin(s):**

All Capacitor Firebase plugins.

**Platform:**

- All capacitor platforms
- Using Angular & AngularFire

**Current behavior:**

App is complaining that no firebase app is initialized :
```
main.js:1 ERROR Error: Uncaught (in promise): FirebaseError: Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app).
```
But I initialized it with AngularFire 7, as the [official doc](https://github.com/angular/angularfire#example-use) says it should be :

```js
import { initializeApp, provideFirebaseApp } from "@angular/fire/app";
import { provideAuth, getAuth } from "@angular/fire/auth";

@NgModule({
  declarations: [AppComponent],
  entryComponents: [],
  imports: [
    provideFirebaseApp(() => initializeApp(environment.firebaseConfig)),
    provideAuth(() => getAuth())
  ],
```
I also tried the *compat API way (non-modular)* :

```js
import { AngularFireModule } from "@angular/fire/compat";
import { AngularFireAuthModule } from "@angular/fire/compat/auth";

@NgModule({
  declarations: [AppComponent],
  entryComponents: [],
  imports: [
    AngularFireModule.initializeApp(environment.firebaseConfig),
    AngularFireAuthModule
  ],

```

The only way for me to make it work was to directly access the firebase sdk, as stated in Capacitor-Firebase doc :
```js
export class AppComponent {
 constructor() {
  initializeApp(environment.firebaseConfig);
 }
}
```

It seems Angular Fire and Capacitor-firebase are not sharing the same firebase instance ?

**Expected behavior:**

This plugin should be compatible with Angular Fire, which is the most popular Firebase wrapper for Angular.

**Steps to reproduce:**

- Create a new app with capacitor, ionic and angular
- Install Firebase, AngularFire and Capacitor-firebase authentification
- Setup AngularFire in app.module.ts

Note : this bug does not seems to break something else in AngularFire (as for now).

**Comment by robingenz** [comment]
Hi @Squix,
i've never tested my plugins with `@angular/fire`.
Please provide a Minimal, Reproducible Example (see [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)) so I can have a look.

One thing in advance: These plugins use the native Firebase SDKs. So when you sign in on Android and iOS, you are signed in on native layer and not on web layer. So on Android and iOS you can't use Angular Fire without adjustments. You need to sign in the user on Android and iOS also on the web layer. How this works is described [here](https://github.com/capawesome-team/capacitor-firebase/blob/main/packages/authentication/docs/firebase-js-sdk.md).

**Comment by DwieDima** [comment]
@Squix for me this works with no issues using this configuration:
I've set `skipNativeAuth` to `true` inside `capacitor.config.ts`.

```typescript
import { initializeApp, provideFirebaseApp } from '@angular/fire/app';
import { getAuth, provideAuth } from '@angular/fire/auth';
import { getFirestore, provideFirestore } from '@angular/fire/firestore';
import { getFunctions, provideFunctions } from '@angular/fire/functions';
import { Capacitor } from '@capacitor/core';
import { getApp } from 'firebase/app';
import { indexedDBLocalPersistence, initializeAuth } from 'firebase/auth';
import { environment } from '../environments/environment';

  imports: [
    ...
    AppRoutingModule,
    provideFirebaseApp(() => initializeApp(environment.firebase)),
    provideAuth(() =>
      Capacitor.isNativePlatform()
        ? initializeAuth(getApp(), {
            persistence: indexedDBLocalPersistence
          })
        : getAuth()
    ),
    provideFirestore(() => getFirestore()),
    provideFunctions(() => getFunctions())
  ]
  ...

```

**Comment by Squix** [comment]
Thanks, I tried the snippet, but Angular still doesn't want to init my firebase app on web, seems to work on device, but I can't try sign in, because I've got another issue with this library though, which I need to solve first (I'm opening a new ticket now).
