### ISSUE TITLE
bug:  'CapacitorFirebaseAnalytics/Analytics' 

### ISSUE THREAD

**Issue by carlossk** [capawesome-team/capacitor-firebase#173]
**Plugin(s):**

@capacitor-firebase/analytics@0.5.1

**Platform(s):**

iOS - Xcode Version 13.4.1 

**Current behavior:**

✖ Updating iOS native dependencies with pod install - failed!
✖ update ios - failed!
[error] Analyzing dependencies
        [!] There are multiple dependencies with different sources for `CapacitorFirebaseAnalytics` in `Podfile`:
        
        - CapacitorFirebaseAnalytics (from `../../../../node_modules/@capacitor-firebase/analytics`)
        - CapacitorFirebaseAnalytics/Analytics (from `../../node_modules/@capacitor-firebase/analytics`)
        

**Steps to reproduce:**

Add the CapacitorFirebaseAnalytics/Analytics pod to your Podfile (usually ios/App/Podfile):

```
run npx cap sync
```

**Capacitor doctor:**

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.0.1
  @capacitor/core: 4.0.1
  @capacitor/android: 4.0.1
  @capacitor/ios: 4.0.1

Installed Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

**Comment by robingenz** [comment]
> Add the CapacitorFirebaseAnalytics/Analytics pod to your Podfile (usually ios/App/Podfile)

Why do you add the pod manually to your Podfile? 

The required pods are already included in the plugin Podfile.

**Comment by carlossk** [comment]
because I have this error  No such module 'FirebaseCore'

<img width="391" alt="image" src="https://user-images.githubusercontent.com/12755233/183514064-80c31625-6590-4b1b-b3a2-3f426f430f28.png">

**Comment by robingenz** [comment]
Okay, it seems like your setup is a little messed up. 
Please provide a Minimal, Reproducible Example (see [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)) so I can debug the issue.

Make sure you have followed the setup instructions carefully.

Here you can also find a demo app: https://github.com/robingenz/capacitor-firebase-authentication-demo

**Comment by carlossk** [comment]
Hi @robingenz my mistake is that I have the native project in a custom path, I made sure that the relative path was correct, now it works

**Comment by CraigRonald555** [comment]
@carlossk Do you mind telling me where you changed the path? I have this same issue, but don't quite follow what you meant in your response. Thanks!

**Comment by CraigRonald555** [comment]
@carlossk 

thanks for responding, that makes sense… unfortunately didn’t fix my problem :( looks like I may have to update my capacitor to get to the latest version of this plugin
