### ISSUE TITLE
feat: Ability to add tenant ID in the login itself

### ISSUE THREAD

**Issue by vaishnavm217** [capawesome-team/capacitor-firebase#174]
**Is your feature request related to a problem? Please describe:**
Currently the library allows only allows tenant ID additions on the providers. Cant see the option present in the signInWithEmailPassword option. For my situation, I cant use the firebase web auth  and need to use the native one. Web auth do have tenant ID option, when the autj object is created

**Describe the solution you'd like:**
maybe the initialization can take the tenant ID if needed. rest the providers will remain untouched.

**Describe alternatives you've considered:**
I am still testing the approach of `Auth.auth().tenantID = 'foo'`, if that works, it should be good, although then I need to seperate swift files for each env.

**Additional context:**

None

**Comment by robingenz** [comment]
Yes, this is missing currently. Thank you for your request!

**Comment by vaishnavm217** [comment]
More to add to the experimentation. `Auth.auth().tenantID = "foo"` seems to work.

**Comment by robingenz** [comment]
Would you like to test the dev build?

```
npm i @capacitor-firebase/authentication@1.0.0-dev.af4d281.1661008317
```
