### ISSUE TITLE
feat: AppCheck support

### ISSUE THREAD

**Issue by jjgriff93** [capawesome-team/capacitor-firebase#177]
**Is your feature request related to a problem? Please describe:**
Loving this library thus far. It would be incredibly useful to have a--check support in this library (there's only one capacitor alternative currently and that isn't being maintained and isn't compatible with Cap 4: https://github.com/mattmilan-dev/capacitor-firebase-appcheck

**Describe the solution you'd like:**
Similarly to the linked library, I would like to be able to access native firebase appcheck along with the tokens it issues from within my Capacitor application. I currently use AngularFire and when initialising appcheck on the web layer I access the native token as a CustomProvider during module bootstrapping:

```
// Initialise AppCheck natively if running on iOS or Android
      if (Capacitor.isNativePlatform()) {
        AppCheck.initialize({ debug: isDevMode() });
        // Use CustomProvider to get native AppCheck token
        provider = new CustomProvider({
          getToken: async () => {
            const { token, exp: expireTimeMillis } =
              await AppCheck.getAppCheckToken();
            return { token, expireTimeMillis };
          }
        });
        // Or use ReCAPTCHAv3 if running in web
      } else {
```

Thanks! Goes without saying that I'm happy to help implement or provide further info

**Comment by robingenz** [comment]
Great feature request! This plugin is still missing.

> Thanks! Goes without saying that I'm happy to help implement or provide further info

If you want, you can do the implementation. I would then create the boilerplate code for the new package and prepare everything.
Just let me know.

**Comment by phoheisel** [comment]
I would love to see that! Is there any other known way to get app check running witch cap4?

**Comment by robingenz** [comment]
I am currently not aware of any. The plugin is still planned but I currently have little free time.

**Comment by jjgriff93** [comment]
Hello guys, sorry for the delay but I have put together an implementation for this and opened a PR (#237), let me know what you think (and please test it)!

**Comment by robingenz** [comment]
A first dev version is now available for testing:

```
npm i @capacitor-firebase/app-check@1.2.0-dev.c2371d8.1667689388
```
