### ISSUE TITLE
bug: when the App is closed completely the notificationActionPerformed listener is not fired

### ISSUE THREAD

**Issue by RRGT19** [capawesome-team/capacitor-firebase#178]
**Plugin(s):**
- "@capacitor-firebase/messaging": "^0.5.1"

**Platform(s):**
- iOS

**Current behavior:**
When the App is closed (killed) completely and a push notification is sent, you open it from the notifications center and the `notificationActionPerformed` listener is not fired. I don't know if `notificationReceived` is being called, I see no logs.

**Expected behavior:**
`notificationActionPerformed` should be called when the app is closed completely.

**Steps to reproduce:**
Close the app completely, send a notification and try to open the notification from the notifications center.

**Related code:**
```typescript
    FirebaseMessaging.addListener('notificationReceived', event => {
      console.log('notificationReceived', {event});
    });

    FirebaseMessaging.addListener('notificationActionPerformed', event => {
      console.log('notificationActionPerformed', {event});
    });
```

**Payload being sent to FCM API:**

```json
{
  "to":"/topics/example",
  "priority":"high",
  "notification":{
    "title":"Hi",
    "body":"Testing here"
  },
  "data":{
    "title":"Hi",
    "body":"Testing here"
  }
}
```

**AppDelegate:**

```swift
func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
      NotificationCenter.default.post(name: .capacitorDidRegisterForRemoteNotifications, object: deviceToken)
    }

    func application(_ application: UIApplication, didFailToRegisterForRemoteNotificationsWithError error: Error) {
      NotificationCenter.default.post(name: .capacitorDidFailToRegisterForRemoteNotifications, object: error)
    }
    
    func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
        NotificationCenter.default.post(name: Notification.Name.init("didReceiveRemoteNotification"), object: completionHandler, userInfo: userInfo)
    }
```

![image](https://i.ibb.co/jfkpf6Y/Screen-Shot-2022-08-17-at-8-06-23-AM.png)

**Capacitor config:**
```
PushNotifications: {
      presentationOptions: ["badge", "sound", "alert"],
    },
```

The notification is displayed correctly on the phone and in the notification center.

**Other information:**
My goal is to be able to open a screen when you tab a notification from the notifications center. Right now, is not working because `notificationActionPerformed` is not being called.

_Imagine when you tab on a notification from WhatsApp and you are redirected to a screen that contains your conversation._

I don't know if this is a bug or a known limitation where we don't have a workaround yet.

Others issues that can be related or not:
- No sound is played by default. Not even the iOS default one.
- No badge count is being set above the App icon.

I have read:

- https://github.com/ionic-team/capacitor-plugins/issues/200
- https://github.com/capawesome-team/capacitor-badge/issues/24

Any help is appreciated.

**Capacitor doctor:**
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.0.1
  @capacitor/core: 4.0.1
  @capacitor/android: 4.0.1
  @capacitor/ios: 4.0.1

Installed Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/ios: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/core: 3.6.0
```

**Comment by robingenz** [comment]
Thank you for your request. I will have a look. Should be a bug.

**Comment by RRGT19** [comment]
To be sure that the issue is not on the way the FCM payload is sent, I have also tried with this:

**legacy HTTP**

```json
{
  "to":"/topics/example",
  "priority":"high",
  "content_available":true, // <= testing...
  "notification":{
    "title":"Hi",
    "body":"Testing here"
  },
  "data":{
    "title":"Hi",
    "body":"Testing here"
  }
}
```

**HTTP v1**

```json
{
  "message":{
    "topic":"example",
    "data":{
      "url":"https://google.com"
    },
    "notification":{
      "title":"Hi",
      "body":"Testing here"
    },
    "apns":{ // <= testing...
      "payload":{
        "aps":{
          "content-available":1
        }
      }
    }
  }
}
```

Also, I have tried to follow the steps described here:
https://forum.ionicframework.com/t/ios-push-notifications-not-being-received-after-capacitor-2-3-and-ionic-5-6-migration/222497/5

The result is the same, the notification is sent and I can see it on the notifications center (without a sound), but when you click on it, the app opens from scratch but `notificationActionPerformed` is not called. I cannot redirect the user or do something at all.

**Comment by carlossk** [comment]
I have the same issue, any idea about it?

**Comment by robingenz** [comment]
Please give this dev version a try: 

```
npm i @capacitor-firebase/messaging@1.1.0-dev.a6a0720.1664629140
```

**Comment by RRGT19** [comment]
@robingenz 
That version is working good from all points of view, app open/closed/killed, etc...
:)
