### ISSUE TITLE
bug: [ANDROID] Google Sign In throwing Error: Attempt to invoke virtual method on a null object reference

### ISSUE THREAD

**Issue by Squix** [capawesome-team/capacitor-firebase#179]
Hi, first I want to thank you for all your hard work and your quick replies to issues.

Here's some info on my environment :

- Angular 12
- Ionic 6
- Capacitor 4
- Installed plugins :
  -  @capacitor-community/barcode-scanner@3.0.0
  -  @capawesome/capacitor-screen-orientation@2.0.0
  =
  -  @capacitor-firebase/analytics@1.0.0
  -  @capacitor-firebase/authentication@1.0.0
  -  @capacitor-firebase/messaging@1.0.0
  =
  -  @capacitor/app@4.0.1
  -  @capacitor/browser@4.0.1
  -  @capacitor/geolocation@4.0.1
  -  @capacitor/haptics@4.0.1
  -  @capacitor/keyboard@4.0.1
  -  @capacitor/local-notifications@4.0.1
  -  @capacitor/network@4.0.1
  -  @capacitor/push-notifications@4.0.1
  -  @capacitor/status-bar@4.0.1

**Plugin(s):**

Capacitor Firebase Authentication - v1.0.0

**Platform:**

- Android

**Current behavior:**

```js
import {
  FirebaseAuthentication,
  SignInResult
} from "@capacitor-firebase/authentication";

public async logInUser(provider: "google" | "apple"): Promise<boolean> {
    let result: SignInResult;
    if (provider === "google") {
      result = await FirebaseAuthentication.signInWithGoogle();
    }
//[...]
 }
```
On web, the plugin is working correctly : when calling **FirebaseAuthentication.signInWithGoogle()**, the google log-in windows opens and the log-in flow works.

On android, when calling the same code, this error is thrown :
```
ERROR Error: Uncaught (in promise): Error: Attempt to invoke virtual method 'void io.capawesome.capacitorjs.plugins.firebase.authentication.handlers.GoogleAuthProviderHandler.signIn(com.getcapacitor.PluginCall)' on a null object reference
Error
    at new pe (d:\Projets\Dev\marTiClient\node_modules\zone.js\dist\zone-error.js:99:37)
    at new A (d:\Projets\Dev\marTiClient\node_modules\@capacitor\core\build\util.js:21:9)
    at returnResult (D:\Projets\Dev\marTiClient\www\index.html:419:32)
    at win.androidBridge.onmessage (D:\Projets\Dev\marTiClient\www\index.html:394:21)
```
and nothing is shown.

**Expected behavior:**

This function should show the google log-in prompt on device and continue the log-in flow.

**What I tried:**

- The demo app for capacitor firebase authentification (https://github.com/robingenz/capacitor-firebase-authentication-demo) works.
- Firebase is added and configured for Android, as stated in the docs of this library :
   - *google-services.json* is in android/app (and the others capacitor-firebase plugins are working)
   - `rgcfaIncludeGoogle = true` is in *variables.gradle*
   - *com.google.gms.google-services* plugin is applied in android/app/build.gradle

I tried all I could, including :
- removing android platform and starting over with a fresh android project
- cleaning gradle build and android studio cache files

Have you seen this error before ? Is it related to a specific issue in capacitor plugin development ?

Thank you for your time

**Comment by robingenz** [comment]
Please make sure that `google.com` is in your [configuration](https://github.com/capawesome-team/capacitor-firebase/tree/main/packages/authentication#configuration) providers array:

```json
{
  "plugins": {
    "FirebaseAuthentication": {
      "providers": ["google.com"]
    }
  }
}
```

**Comment by Squix** [comment]
Ok, that was the issue.
I had a typo in this file, wrote *FirebaseAuthentification* instead of **FirebaseAuthentication**.
My bad, thanks for the quick reply !

**Comment by robingenz** [comment]
You're welcome!
In this case i will close this issue.
