### ISSUE TITLE
bug: `getCurrentUser` returns user even when the user is removed from web-based Firebase manually

### ISSUE THREAD

**Issue by TadasMil** [capawesome-team/capacitor-firebase#184]
**Plugin(s):**
`@capacitor-firebase/authentication`

**Platform(s):**
`Android`

**Current behavior:**
As stated in this discussion [https://github.com/capawesome-team/capacitor-firebase/issues/140](url), the way we should identify if the user is logged in or not during app launch is using `getCurrentUser` function.

Having an empty `Authentication` table of google/facebook logged in users inside of Firebase project and launching the app using Android, the actual `user` instance with `getCurrentUser` is being returned. 

**Expected behavior:**
Having an empty `Authentication` table of google/facebook logged in users inside of Firebase project and launching the app using Android, the actual `user` instance should be null, so that the `user` would be redirected to the `login` page.

**Steps to reproduce:**
1. Run app on Android platform
2. Login with Google or Facebook.
3. The new instance is being saved on `Authentication` table inside of Firebase project.
4. Close the application and open it again.
5. `getCurrentUser` returns `user` instance even tho the actual instance is deleted and the user does not exist anymore.

**Related code:**

```
export const getUser = async () => {
  return await FirebaseAuthentication.getCurrentUser().user;
};

router.beforeEach(async (to, _, next) => {
  const user = await getUser();
  console.log('user instance', user);
})
```

**Other information:**
FYI, on Web it works as expected, once you launch the app `getCurrentUser` returns `null`. I did not tested this on `iOS`. 

**Capacitor doctor:**

```
Latest Dependencies:       

  @capacitor/cli: 4.1.0    
  @capacitor/core: 4.1.0   
  @capacitor/android: 4.1.0
  @capacitor/ios: 4.1.0    

Installed Dependencies:    

  @capacitor/core: 3.5.1
  @capacitor/android: 3.5.1
  @capacitor/cli: 3.5.1
  @capacitor/ios: 3.5.1

[success] Android looking great! 👌
[error] Xcode is not installed
```

**Comment by robingenz** [comment]
The User instance is saved by Firebase because you don't want that your users have to log in after every app start or? 

If you want to delete the actual user instance you have to sign the user out.

On the web, this needs to be configured (see Firebase docs).

**Comment by robingenz** [comment]
I am also not sure if I understand you issue correctly. Why should the user table in Firebase be empty after a signin? Do you manually delete the user entry?

**Comment by TadasMil** [comment]
Oh, I'm sorry for registering the issue. Probably its a falsy one. The only way for detecting manually deleted users using web-based Firebase is using `onAuthStateChanged`.

**Comment by robingenz** [comment]
I found this SO thread: https://stackoverflow.com/questions/40252218/how-can-i-detect-if-the-user-was-deleted-from-firebase-auth
It says you should call `getIdToken` with the parameter `forceRefresh=true` to immediately find out if a user is still logged in.
If not an error will be thrown.

Otherwise, the ID token should automatically become invalid after about an hour and getCurrentUser should then return null. So maybe you just have to wait a bit longer.

It doesn't look like this is a bug in this plugin at the moment. For this reason I am closing this issue.
