### ISSUE TITLE
bug: AnalyticsService not registered

### ISSUE THREAD

**Issue by MateiNenciu** [capawesome-team/capacitor-firebase#188]
**Plugin(s):**

"@capacitor-firebase/analytics": "1.0.0"
"firebase": "9.9.2"

**Platform(s):**

Android

**Current behavior:**

Installed this plugin, made the necessary updates listed here: https://firebase.google.com/docs/analytics/get-started?platform=android but the analytics events are not sent. 

If I run the app from android studio I see this error:
"E/GAv4-SVC: Device AnalyticsService not registered! Hits will not be delivered reliably."

**Expected behavior:**

The analytics should report events with configuration mentioned in README

**Steps to reproduce:**

Install plugin, make the installation steps, make some events, run app.

**Related code:**

```
No code needed
```

**Other information:**

Adding this line to AndroidManifest.xml fixes this issue:
```
<service android:name="com.google.android.gms.analytics.AnalyticsService"
        android:enabled="true"
        android:exported="false"/>
```

I don't see this in any official documentation, only on some stackoverflow posts. On the old capacitor-community/firebase-analytics it worked flawlessly without the above configuration.

**Capacitor doctor:**

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 4.1.0
  @capacitor/core: 4.1.0
  @capacitor/android: 4.1.0
  @capacitor/ios: 4.1.0

Installed Dependencies:

  @capacitor/cli: 4.0.1
  @capacitor/core: 4.0.1
  @capacitor/android: 4.0.1
  @capacitor/ios: 4.0.1

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

**Comment by MateiNenciu** [comment]
> Does this SO answer resolve your issue: https://stackoverflow.com/a/30271686/6731412 ?

Seems like it. But this looks some ancient answer and honestly I have no idea why it doesn't work without it... I can't find this solution on official documentation.

**Comment by robingenz** [comment]
I found this comment there: 

> maybe because these are required only on devices not having Google play services. But I too feel it should be mentioned in those docs.

Does your device have Google Play Services? 

Seems like you can also enable debugging with this commands:

'adb shell setprop log.tag.GAv4 DEBUG'

'adb logcat -s GAv4'

Maybe this will help you to find the real problem.
