### ISSUE TITLE
bug:  signInWithGoogle

### ISSUE THREAD

**Issue by DeveloperAdam-github** [capawesome-team/capacitor-firebase#189]
**Plugin(s):**

 "@capacitor-firebase/app": "^1.0.0",
    "@capacitor-firebase/authentication": "^1.0.0",

**Platform(s):**

iOS

**Current behavior:**

When trying to signInWithGoogle the function runs but no pop up occurs and no data is being returned.
**To Native ->  FirebaseAuthentication signInWithGoogle 60979170** is the message I get in the logs.

**Expected behavior:**

Assume a pop up should come up and ask me to sign in with google have tried same code and another plugin all works but wanted to use this plugin.

**Steps to reproduce:**

Install, setup the signInWithGoogle function and nothing happens

**Related code:**

```
const result = await FirebaseAuthentication.signInWithGoogle();
```

**Other information:**

**Capacitor doctor:**

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.1.0
  @capacitor/core: 4.1.0
  @capacitor/android: 4.1.0
  @capacitor/ios: 4.1.0

Installed Dependencies:

  @capacitor/cli: 4.1.0
  @capacitor/core: 4.1.0
  @capacitor/android: 4.1.0
  @capacitor/ios: 4.1.0

[success] iOS looking great! 👌
```

**Comment by DeveloperAdam-github** [comment]
<img width="440" alt="Screenshot 2022-08-27 at 13 01 34" src="https://user-images.githubusercontent.com/56017774/187029285-602f1f25-4848-4051-841e-aa0e05fbbc72.png">


This is a console log from Safari about this issue.

**Comment by robingenz** [comment]
Did you add 'google.com' to the configuration providers array and run 'npx cap sync'?

**Comment by DeveloperAdam-github** [comment]
> 

Yes and have added the url value from the GoogleService-Info

**Comment by robingenz** [comment]
Did you add the CapacitorFirebaseAuthentication/Google pod to your Podfile (usually ios/App/Podfile)?

**Comment by DeveloperAdam-github** [comment]
> 

Yep followed setup instructions and added that.

**Comment by robingenz** [comment]
Okay, please provide a minimal, reproducible example so I can debug the issue.

**Comment by corcorb** [comment]
@DeveloperAdam-github It's likely a different issue but I was having the same behavior and it was because I put the ` pod 'CapacitorFirebaseAuthentication/Google', :path => '../../node_modules/@capacitor-firebase/authentication'` under `def capacitor_pods` and not under `target 'App' do\ncapacitor_pods` in `Podfile`. Took me a couple hours to figure that out so posting just in case that's your issue as well.

**Comment by ngarel** [comment]
@corcorb I confirm that this is now working, however where in the doc is it mentioned that we have to set it this way?

```
target 'App' do
  capacitor_pods
  # Add your Pods here
  pod 'CapacitorFirebaseAuthentication/Google', :path => '../../node_modules/@capacitor-firebase/authentication'
end
```

**Comment by robingenz** [comment]
@ngarel See https://github.com/capawesome-team/capacitor-firebase/blob/main/packages/authentication/docs/setup-google.md#ios

**Comment by ngarel** [comment]
Right...for some reason I was seeing:
` pod 'CapacitorFirebaseAuthentication', :path => '../../node_modules/@capacitor-firebase/authentication'` which was already there...Didn't read it properly even though i visited this page a dozen times...

Thanks!
