### ISSUE TITLE
feat: Update JavaScript SDK docs to provide Play Games sign in example

### ISSUE THREAD

**Issue by erikwalle** [capawesome-team/capacitor-firebase#190]
**Is your feature request related to a problem? Please describe:**
I can't log in with Play Games Services after upgrading to Capacitor 4 and this package. Hoping an example will help, though I think I don't even get a response from FirebaseAuthentication.signInWithPlayGames()

Further, it seems like the extra step to sign in with the JavaScript SDK (https://github.com/capawesome-team/capacitor-firebase/blob/main/packages/authentication/docs/firebase-js-sdk.md) should be listed as a breaking change in BREAKING.md, as previous package supported this without the additional step.

**Describe the solution you'd like:**
An example of how to log in with Play Games services here:
https://github.com/capawesome-team/capacitor-firebase/blob/main/packages/authentication/docs/firebase-js-sdk.md

**Describe alternatives you've considered:**
Considered not upgrading from the old library: https://github.com/robingenz/capacitor-firebase-authentication
But Capacitor 4 will be required soon.

**Comment by robingenz** [comment]
Hi @erikwalle,
please add all the infos from your mail to this issue.
I will create a dev version for testing for you.

**Comment by erikwalle** [comment]
Hello @robingenz , I have put the details into a full bug report here: https://github.com/capawesome-team/capacitor-firebase/issues/195

This was just a request for additional documentation, thanks!

**Comment by robingenz** [comment]
Thank you! Did you now manage to log in to Play Games via the Firebase JS SDK? If so, could you share the code snippet here?
