### ISSUE TITLE
feat: `skipNativeAuth` option should be configurable per provider

### ISSUE THREAD

**Issue by robingenz** [capawesome-team/capacitor-firebase#191]
**Is your feature request related to a problem? Please describe:**

It is currently not possible to log in to the Firebase JS SDK with Apple and Twitter, as Apple requires `skipNativeAuth=true` and Twitter `skipNativeAuth=false` (see [here](https://github.com/robingenz/capacitor-firebase-authentication/issues/93#issuecomment-939459594)).

**Describe the solution you'd like:**

The `skipNativeAuth` option should be configurable per provider.

**Describe alternatives you've considered:**

**Additional context:**

**Comment by mesqueeb** [comment]
just FYI
your Twitter implementation works with `skipNativeAuth=true` on android, just not on iOS
