### ISSUE TITLE
bug: FirebaseAuthentication.signInWithPlayGames() errors every time

### ISSUE THREAD

**Issue by erikwalle** [capawesome-team/capacitor-firebase#195]
**Plugin(s):**
Running the latest `@capacitor-firebase/authentication` on Capacitor 4.0

**Platform(s):**
Android

**Current behavior:**
Syntax error:
```
java.lang.IllegalArgumentException: Given String is empty or null
W/System.err:     at com.google.android.gms.common.internal.Preconditions.checkNotEmpty(com.google.android.gms:play-services-basement@@18.0.0:2)
W/System.err:     at com.google.firebase.auth.PlayGamesAuthCredential.<init>(com.google.firebase:firebase-auth@@21.0.4:2)
W/System.err:     at com.google.firebase.auth.PlayGamesAuthProvider.getCredential(com.google.firebase:firebase-auth@@21.0.4:1)
W/System.err:     at io.capawesome.capacitorjs.plugins.firebase.authentication.handlers.PlayGamesAuthProviderHandler.handleOnActivityResult(PlayGamesAuthProviderHandler.java:50)
W/System.err:     at io.capawesome.capacitorjs.plugins.firebase.authentication.FirebaseAuthentication.handlePlayGamesAuthProviderActivityResult(FirebaseAuthentication.java:316)
W/System.err:     at io.capawesome.capacitorjs.plugins.firebase.authentication.FirebaseAuthenticationPlugin.handlePlayGamesAuthProviderActivityResult(FirebaseAuthenticationPlugin.java:375)
W/System.err: ... 24 more
```

**Expected behavior:**
Successful Play Games login

**Steps to reproduce:**
Call FirebaseAuthentication.signInWithPlayGames() after all other setup steps

**Related code:**

The problem seems related to a missing credential in `handleOnActivityResult` of `PlayGamesAuthProviderHandler`:
```
AuthCredential credential = PlayGamesAuthProvider.getCredential(serverAuthCode);
```

This credential is missing because it must be requested in `buildGoogleSignInClient`:
```
GoogleSignInOptions.Builder gsob = new GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_GAMES_SIGN_IN)
            .requestIdToken(pluginImplementation.getPlugin().getContext().getString(R.string.default_web_client_id))
            .requestServerAuthCode(pluginImplementation.getPlugin().getContext().getString(R.string.default_web_client_id))
            .requestEmail();
```
Note changes to the existing code:
- Added a `.requestServerAuthCode` in the chain
- Changed GoogleSignInOptions.DEFAULT_SIGN_IN to GoogleSignInOptions.DEFAULT_GAMES_SIGN_IN
(Reference: https://stackoverflow.com/questions/55578059/playgames-error-invalid-credential)

Unfortunately after that I got stuck with this error (on calling `getAuth()` from my javascript code, per JavaScript SDK guide):
`No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp()`

I tried importing `initializeApp` from `firebase/app` and calling it before `getAuth()`, but that didn't work

**Capacitor doctor:**

```
$ npx cap doctor
   Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 4.1.0
  @capacitor/core: 4.1.0
  @capacitor/android: 4.1.0
  @capacitor/ios: 4.1.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 4.1.0
  @capacitor/core: 4.1.0
  @capacitor/android: 4.1.0

[success] Android looking great! ≡ƒæî
[error] Xcode is not installed
```

**Comment by robingenz** [comment]
Thank you! I will have a look in the next days.

**Comment by robingenz** [comment]
I will release a new version with your fix soon. Thank you for all the info!

> Unfortunately after that I got stuck with this error (on calling getAuth() from my javascript code, per JavaScript SDK guide):
No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp()

This should be another error which is not related to this issue.
Usually this error means that you are not calling `firebase.initializeApp(...);` early enough.
However, I need to see the code to be able to help you. Maybe you can create a minimal, reproducible example.

**Comment by erikwalle** [comment]
Thanks @robingenz , I think my last attempt was missing that integration step entirely.

I will attempt another integration soon, can I use the latest release or is there a version you recommend? Thanks again!

**Comment by robingenz** [comment]
You can use the latest dev version: 
```
npm i @capacitor-firebase/authentication@1.0.0-dev.3b45e52.3b45e52
```
