### ISSUE TITLE
bug: Google calendar scops

### ISSUE THREAD

**Issue by Valonfeka** [capawesome-team/capacitor-firebase#207]
**Plugin(s):**

CapacitorFirebaseAuthentication/Google

**Platform(s):**

IOS

**Current behavior:**

I am adding the scope to ask for the permission of Calendar API but from what I see so far it's not working.

**Expected behavior:**

Needs to get ask for permission of the Calendar API

**Steps to reproduce:**

**Related code:**

```
const result = await FirebaseAuthentication.signInWithGoogle({
     customParameters: [],
     scopes: ['https://www.googleapis.com/auth/calendar']
 });
```

**Other information:**

**Capacitor doctor:**

Latest Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0

Installed Dependencies:

  @capacitor/ios: 3.5.1
  @capacitor/android: 3.5.1
  @capacitor/cli: 3.8.0
  @capacitor/core: 4.3.0

```
insert the output from `npx cap doctor` here
```

**Comment by robingenz** [comment]
I don't have any experience with this so far but it seems it's a bit more complex and you have to manage the OAuth access tokens yourself, see:
- https://github.com/firebase/firebase-js-sdk/issues/519
- https://www.youtube.com/watch?v=Bj15-6rBHQw
