### ISSUE TITLE
bug: Prompt select_account as customParameters is not working on signInWithGoogle.

### ISSUE THREAD

**Issue by shreyasPL** [capawesome-team/capacitor-firebase#209]
**Plugin(s):**

1. CapacitorFirebaseAuthentication - version - 1.1.0 

**Platform(s):**
1. Android
2. ios

**Current behavior:**

1. google signin prompt's to select the google accounts(since users will have multiple google accounts) only once at the beginning of the user's app cycle.
2. If I logout and try to login again with the google signin, the google's select account prompt is not popping out or showing, it lets me in with the previous account which used to to signin via google itself.

**Expected behavior:**

1. Please prompt me every time if, I am logged out to select an account.

**Steps to reproduce:**
1. Please add the following code and use the android device to signin via google.

**Related code:**

```
const options = {customParameters: [{key: 'prompt', value: 'select_account'}]}
                                    FirebaseAuthentication.signInWithGoogle(options).then((async () => {
                                    }))
```

**Other information:**

1. CustomParameters are supposed to be an array of key value pair, which I a following.

**Capacitor doctor:**

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0

Installed Dependencies:

  @capacitor/core: 4.3.0
  @capacitor/cli: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

**Comment by robingenz** [comment]
Please have a look at https://github.com/robingenz/capacitor-firebase-authentication/issues/129.
Does this help you?

**Comment by shreyasm312** [comment]
Hey, Thank you for the reply.
1. Yes, it does work fine, after I signout of the application successfully. 
2. So you mean to say, there is no support for Google oauth options.
If that's the case,
Is this is in scope of development in any time future?
Thank you.

**Comment by robingenz** [comment]
I will look at it again.

**Comment by robingenz** [comment]
> Hey, Thank you for the reply.
> 
>     1. Yes, it does work fine, after I signout of the application successfully.
> 
>     2. So you mean to say, there is no support for Google oauth options.
>        If that's the case,
>        Is this is in scope of development in any time future?
>        Thank you.

It seems like `GoogleSignInClient` does not custom parameters.
I will update the documentation.
I recommend to log out the user before the new login process starts.
