### ISSUE TITLE
bug:  FirebaseAuthentication signInWithGoogle Error 10 : 

### ISSUE THREAD

**Issue by aligassan** [capawesome-team/capacitor-firebase#220]
**Plugin(s):**

[capacitor]        @capacitor-firebase/app@1.1.0
[capacitor]        @capacitor-firebase/authentication@1.1.0

**Platform(s):**

Android

**Current behavior:**

When l try to signInWithGoogle the function runs and l have a pop-up occurs and data is returned Error 10.

**Expected behavior:**

After a pop-up asking me to sign in with google occurs and data he should returned successfully 

**Steps to reproduce:**

 l have [following Set up authentication using Google Sign-In ](https://github.com/capawesome-team/capacitor-firebase/blob/main/packages/authentication/docs/setup-google.md). But l have the same issue. 

l have added SHA-1 fingerprint to the Firebase console and re-download google-service.json , but l have same issue .

**Related code:**

```
const signInWithGoogle = async () => {
  const result = await FirebaseAuthentication.signInWithGoogle();
  return result.user;
};

```

**Other information:**

For SHA-1 fingerprint . l get it from google play console > App integrity > App signing key certificate. 
Also, l have replaced the SHA-1 fingerprint with the app signing key certificate with the Upload key certificate.  

l have same issue . 

**Capacitor doctor:**

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0

Installed Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/ios: 4.2.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

**Comment by robingenz** [comment]
Hi @aligassan,
thank you for your request.
This is a configuration error.
Please have a look at this comment: https://github.com/robingenz/capacitor-firebase-authentication/issues/97#issuecomment-961470725
