### ISSUE TITLE
bug : signInWithPhoneNumber not validating SMS code

### ISSUE THREAD

**Issue by swapnaliDeveloper** [capawesome-team/capacitor-firebase#222]
**Plugin(s):**

[@capacitor-firebase/authentication](https://www.npmjs.com/package/@capacitor-firebase/authentication)
v - 1.1.0 
v - 0.5.1
v - 0.2.2
plugin called with latest versions , getting same output in dev , production environment 

**Platform(s):**

android 
ios
 
**Current behavior:**

accepting any verification(random code other than actual SMS code) code in const result = await FirebaseAuthentication.signInWithPhoneNumber({
    verificationId,
    verificationCode,
  }); 
  and getting success 
 and return result as undefined always

**Expected behavior:**

FirebaseAuthentication.signInWithPhoneNumber func should validate verificationId , verificationCode and give error message 

**Steps to reproduce:**

normally , called signInWithPhoneNumber to receive opt => sms otp received on device
on verification step called signInWithPhoneNumber function with  verificationId,  verificationCode to verify but , accepting any random verificationCode like 000000

**Related code:**

```
await FirebaseAuthentication.signInWithPhoneNumber({
          verificationId,
          verificationCode,
        }).then((res: any) => {
          /// success code
        }).catch((error: any) => {
          /// error code 
    });
```

**Other information:**

   Ionic CLI                           : 5.4.16  
   Ionic Framework               : @ionic/angular 6.0.13
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

   NodeJS : v14.19.1 (/usr/local/bin/node)
   npm    : 8.15.1
   OS     : Linux 5.15

Android device version - 10 , 11, 12
ios version - 15 , 16 

**Capacitor doctor:**

getting following op always while verification function call
```
credential: {providerId: 'phone'} 
```

**Comment by davebanguilan** [comment]
Can you please create a small project in Github so that I can replicate it. Please include the `./android` folder

**Comment by swapnaliDeveloper** [comment]
Yes will share within day

**Comment by swapnaliDeveloper** [comment]
Hi @davebanguilan , repository is created as suggested and android folder included => https://github.com/swapnaliDeveloper/capacitor-otp
, please have a look and let me know if any changes required ...

**Comment by swapnaliDeveloper** [comment]
hi ... is there any update ...?

**Comment by robingenz** [comment]
Hi @swapnaliDeveloper,
The result of `FirebaseAuthentication.signInWithPhoneNumber({ verificationId, verificationCode, });` is only `undefined` if you pass an incorrect verification code, right?
With the correct verification code it works?

So this issue is just about throwing an error message instead of returning `undefined`, right?

I want to make sure I understand the problem.

**Comment by swapnaliDeveloper** [comment]
Hi @robingenz ,
I am able to fixed undefined response with skipNativeAuth: false 
by making skipNativeAuth: false , able to fetch authStateChange Listener and error responce for the invalid opt (000000)
i have using following code implementation by referring https://github.com/robingenz/capacitor-firebase-authentication-demo
``      try {
          await this.firebaseAuthenticationService.signInWithPhoneNumber({
            verificationId,
            verificationCode,
           })
           await this.successfunction();
        }
        catch (e) {
          console.log("This is sign in failed")
          console.log(e) 
//will display error messages
        }
        finally {
          console.log("this is final part")  
        }
   ``
 
Please confirm code implementation

**Comment by robingenz** [comment]
Glad to see it's working now.
In that case I will close this issue now.
