### ISSUE TITLE
feat: support for `loginWithRedirect()` 

### ISSUE THREAD

**Issue by lincolnthree** [capawesome-team/capacitor-firebase#224]
**Is your feature request related to a problem? Please describe:**

Requesting support for `loginWithRedirect()` instead of PopUp, for web environments where we know pop-ups won't work and should not be attempted. Like electron, or other single-page platforms.

**Describe the solution you'd like:**

The CapacitorFirebase login/connect/etc APIs should support `opts: { mode?: 'popup' | 'redirect' }` as an option. PopUp can still be default, but ideally this would be configurable in web environments.

**Describe alternatives you've considered:**

Manually calling the Firebase JS API 

**Additional context:**

Firebase docs for loginWithRedirect:
https://firebase.google.com/docs/auth/web/google-signin#:~:text=To%20sign%20in%20by%20redirecting%20to%20the%20sign%2Din%20page%2C%20call%20signInWithRedirect%3A

Note, we will need an additional function or event listener to check for/receive the redirect OAuth token/results:

https://firebase.google.com/docs/auth/web/google-signin#:~:text=Then%2C%20you%20can%20also%20retrieve%20the%20Google%20provider%27s%20OAuth%20token%20by%20calling%20getRedirectResult%20when%20your%20page%20loads

**Comment by mesqueeb** [comment]
@lincolnthree
Just a friendly FYI on related info.
please note that login with redirect is currently completely broken on Safari 16.1, which is already used worldwide.

more info at:
https://github.com/firebase/firebase-js-sdk/issues/6716
