### ISSUE TITLE
bug: CocoaPods could not find compatible versions for pod "Firebase/CoreOnly"

### ISSUE THREAD

**Issue by dodomui** [capawesome-team/capacitor-firebase#229]
After update this plugin from version 0.3.0 will get following error.

✖ Updating iOS native dependencies with pod install - failed!
✖ update ios - failed!
[error] Analyzing dependencies
        [!] CocoaPods could not find compatible versions for pod "Firebase/CoreOnly":
        In Podfile:
        CapacitorCommunityFirebaseAnalytics (from `../../node_modules/@capacitor-community/firebase-analytics`) was
        resolved to 1.0.1, which depends on
        Firebase/Analytics (~> 8.0) was resolved to 8.0.0, which depends on
        Firebase/Core (= 8.0.0) was resolved to 8.0.0, which depends on
        Firebase/CoreOnly (= 8.0.0)
        
        CapacitorFirebaseAuthentication (from `../../node_modules/@capacitor-firebase/authentication`) was resolved to
        1.1.0, which depends on
        Firebase/Auth (= 9.1.0) was resolved to 9.1.0, which depends on
        Firebase/CoreOnly (= 9.1.0)

**Comment by robingenz** [comment]
Please use the Capacitor Firebase Analytics plugin from this repository to make sure that the native SDKs have no version conflict: '@capacitor-firebase/analytics'.
