### ISSUE TITLE
bug: (Android only) signInWithFacebook() doesn't trigger appStateChange nor authStateChange after successful login

### ISSUE THREAD

**Issue by yaberkane05** [capawesome-team/capacitor-firebase#230]
**Plugin(s):**

FirebaseAuthentication

**Platform(s):**

Android

**Current behavior:**

Calling signInWithFacebook() on android and successful login return to the app but doesn't add user to firebase authenticated users, doesn't trigger appStateChange nor authStateChange and the app navigation is stuck and considered still inactive.
this works successfully on web and iOS.
**Expected behavior:**

calling signInWithFacebook() should successfully return to the app after successfull login and trigger authStateChange.

**Steps to reproduce:**

follow capacitor-firebase signInWithFacebook in android tutorial.

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Capacitor doctor:**

```
Latest Dependencies:       

  @capacitor/cli: 4.4.0    
  @capacitor/core: 4.4.0   
  @capacitor/android: 4.4.0
  @capacitor/ios: 4.4.0    

Installed Dependencies:    

  @capacitor/cli: 4.3.0    
  @capacitor/android: 4.3.0
  @capacitor/core: 4.3.0   
  @capacitor/ios: 4.3.0    

[success] Android looking great! 👌
```

**Comment by robingenz** [comment]
Hi @yaberkane05,
thank you for your request.
Please provide a Minimal, Reproducible Example (see [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)) so I can debug the issue.

**Comment by morethal** [comment]
The same is happening for me as well. 

I used the sample code for the JS login. This works for the Google login, but the Facebook login is not updating, once the Facebook login workflow returns back to my app.

This is the code I am using (copied from the samples)
```
const signInWithFacebook = async () => {
  // 1. Create credentials on the native layer
  const result = await FirebaseAuthentication.signInWithFacebook();
  // 2. Sign in on the web layer using the access token
  const credential = FacebookAuthProvider.credential(
    result.credential?.accessToken,
  );
  const auth = getAuth();
  await signInWithCredential(auth, credential);
};

```

**Comment by morethal** [comment]
Thanks for the swift reply @robingenz.

> Please also check if result.credential?.accessToken has a value.

It appears as if the promise of `FirebaseAuthentication.signInWithFacebook();` is never resolved. I added a log before and after, the log before is executed, the after is not. The whole UI is frozen. If I press the back button in Android, the sign in is canceled and the promise is rejected.

> @morethal Make sure that you initialize the Firebase JS SDK Auth instance correctly (see here).

I also tried to use indexedDBLocalPersistence with not success.

```
    auth = initializeAuth(app, {
      persistence: indexedDBLocalPersistence
    })
```

**Comment by robingenz** [comment]
@morethal  This is exactly the problem my linked comment solves. Please check if you did everything correctly and open a new issue if the problem persists.

**Comment by morethal** [comment]
@yaberkane05, you might want to try my answer here: https://github.com/capawesome-team/capacitor-firebase/issues/243#issuecomment-1308481303

**Comment by yaberkane05** [comment]
> 

This resolved the problem, thank you !

**Comment by robingenz** [comment]
Thanks for your help @morethal!
In this case i will close this issue.
