### ISSUE TITLE
bug: FirebaseMessaging.requestPermissions() always returns 'denied', even if the user presses 'Allow'. Push notifications work fine if the result is ignored

### ISSUE THREAD

**Issue by jaco-terbraak** [capawesome-team/capacitor-firebase#249]
**Plugin(s):**
@capacitor-firebase/messaging: 1.2.0

**Platform(s):**
iOS 15.4.1 (iPhone 8)

**Current behavior:**
1. Execute `FirebaseMessaging.requestPermissions()`
2. Press 'Allow' on the native iOS dialog that pops up
3. Watch the call return 'denied'
4. Add a 'tokenReceived' listener, and send a push notification to FCM using the received token
5. Close the app, and watch the push notification arrive successfully

**Expected behavior:**
The call should return 'granted' when the user presses 'Allow'.

**Steps to reproduce:**
See 'Current behavior'

**Related code:**
```
private getPermission(): Promise<boolean> {
    return FirebaseMessaging.checkPermissions().then(permissionResult => {
      if (permissionResult.receive == 'granted') {
        return true;
      }

      return FirebaseMessaging.requestPermissions().then(permissionResult => {
        // workaround: it always returns 'denied', even if the user presses 'allow'?!
        //
        // return permissionResult.receive != 'denied';

        return true;
      });
    });
  }
```

**Other information:**
<img width="543" alt="Schermafbeelding 2022-11-11 om 15 38 13" src="https://user-images.githubusercontent.com/34056076/201364740-3c8eb856-e249-413d-9aa3-ff30a723b3ac.png">

**Capacitor doctor:**
```
$ npx cap doctor
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.4.0
  @capacitor/core: 4.4.0
  @capacitor/android: 4.4.0
  @capacitor/ios: 4.4.0

Installed Dependencies:

  @capacitor/cli: 4.2.0
  @capacitor/core: 4.0.1
  @capacitor/android: 4.0.1
  @capacitor/ios: 4.0.1

[success] iOS looking great! 👌
[success] Android looking great! 👌

```

**Comment by robingenz** [comment]
Hi @jaco-terbraak,
i can't reproduce the issue:
![grafik](https://user-images.githubusercontent.com/13857929/201372301-3c7b05b8-72c4-49fa-8c63-c98143d5e533.png)

Please provide a Minimal, Reproducible Example (see [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)).
