### ISSUE TITLE
feat: Firebase Remote config alternative 

### ISSUE THREAD

**Issue by juanico18** [capawesome-team/capacitor-firebase#258]
I am looking for an alternative to 
https://github.com/chemerisuk/cordova-plugin-firebase-config or
https://github.com/capacitor-community/firebase-remote-config that does not support capacitor 4.

Do you have in mind to work on it?

Thanks

**Comment by robingenz** [comment]
I already work on it (see #240).
I close this issue as duplicate of #9.

**Comment by robingenz** [comment]
@juanico18 Would you be interested in testing the plugin as soon as it's ready?

**Comment by juanico18** [comment]
Hi @robingenz Yes, I am interested. Although I am working on migrate from cordova to capacitor a project. So maybe it would take me some time to test.
My fault not review the issues looking for anyone else requiring the feature! I thought I did it
