### ISSUE TITLE
feat: delete a user

### ISSUE THREAD

**Issue by maxojev** [capawesome-team/capacitor-firebase#260]
**Describe the solution you'd like:**
Add a way to delete a user account

**Additional context:**
The RGPD wants to give the possibility to a user to delete his account. Today the plugin API does not allow to delete a user. 
The objective of this feature is to allow the authenticated user to delete his account according to the guidelines of the RGPD.

**Comment by yaberkane05** [comment]
if you're using skipNativeAuth, you can use firebase JS SDK to re-authenticate the user and delete his account.

**Comment by trancee** [comment]
@robingenz I could work on this next, if it's still not being done yet.

**Comment by robingenz** [comment]
@trancee This would be great!

**Comment by maxojev** [comment]
@robingenz  and @trancee Thanks, can't wait to see version 1.3
