### ISSUE TITLE
bug: Firebase Analytics - 'FirebaseCore' module not found

### ISSUE THREAD

**Issue by jjgriff93** [capawesome-team/capacitor-firebase#268]
**Plugin(s):**

`CapacitorFirebaseAnalytics:1.2.0`

**Platform(s):**

`iOS`

**Current behavior:**

After installing the plugin following the instructions in the README, i.e. manually specifying `pod 'CapacitorFirebaseAnalytics/Analytics', :path => '../../node_modules/@capacitor-firebase/analytics'` in the Podfile, everything works fine. 

However as soon as you do an `npx cap sync ios`, the Podfile is overwritten with `CapacitorFirebaseAnalytics` instead of `CapacitorFirebaseAnalytics/Analytics`. Then trying to build my app in Xcode gives me `Firebase/Core` module not found. Looking in the `.podspec` file for the plug-in, it looks like it defaults to Lite instead of the Analytics subspec, and thus doesn't specify `Firebase/Analytics -> 9.1.0` in the pod dependencies, causing the error above.

**Expected behavior:**

In line with the other plugins in this repo, I'd expect the Firebase dependency (`Firebase/Analytics`) to be declared in the pod spec by default.

**Steps to reproduce:**

Follow the instructions in the [docs](https://github.com/capawesome-team/capacitor-firebase/tree/main/packages/analytics) to install the package within a bootstrap capacitor application. Then run `npx cap sync ios` again after following the instructions, then open the app in Xcode and build.

**Related code:**

Line 18 from `CapacitorFirebaseAnalytics.podspec`:
```
  s.default_subspec = 'Lite'

  s.subspec 'Lite' do |lite|
    # Default subspec that does not contain optional third party dependencies.
  end

  s.subspec 'Analytics' do |analytics|
    analytics.dependency 'Firebase/Analytics', '9.1.0'
  end

  s.subspec 'AnalyticsWithoutAdIdSupport' do |analyticsWithoutAdIdSupport|
    analyticsWithoutAdIdSupport.dependency 'Firebase/AnalyticsWithoutAdIdSupport', '9.1.0'
  end
end
```

**Capacitor doctor:**

```
Latest Dependencies:

  @capacitor/cli: 4.5.0
  @capacitor/core: 4.5.0
  @capacitor/android: 4.5.0
  @capacitor/ios: 4.5.0

Installed Dependencies:

  @capacitor/cli: 4.4.0
  @capacitor/ios: 4.4.0
  @capacitor/core: 4.4.0
  @capacitor/android: 4.4.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

**Comment by robingenz** [comment]
Capacitor sync only removes the pod if you added it to the wrong block, see: https://github.com/capawesome-team/capacitor-firebase/issues/182#issuecomment-1235225654

Can you share your Podfile before you run Capacitor sync?

**Comment by jjgriff93** [comment]
Ah, you're absolutely right, wrong block! Added it to the app block and all good, thank you. So we essentially need the Capacitor-generated pod reference within the usual `capacitor_pods` block as well as our own reference to the Analytics pod subspec.

Just out of curiosity, why is the set-up different to the other packages in this regard? Is it because of the option of the NoAdId subspec? If so might be more straight-forward to change the default subspec to `Analytics` and then only require manually declaring the pod in the app block to specify `/Lite` or `/AnalyticsWithoutAdIdSupport`?

**Comment by robingenz** [comment]
> Ah, you're absolutely right, wrong block! Added it to the app block and all good, thank you. 

Great, in this case  i will close this issue.

> Just out of curiosity, why is the set-up different to the other packages in this regard? Is it because of the option of the NoAdId subspec?

Yes, it is because of the `AnalyticsWithoutAdIdSupport` subspec.

> If so might be more straight-forward to change the default subspec to `Analytics` and then only require manually declaring the pod in the app block to specify `/Lite` or `/AnalyticsWithoutAdIdSupport`?

I had tried this before and there were problems when the pod was listed twice in the podfile (and once it is always added by cap sync). I don't remember exactly what the problem was though.
