### ISSUE TITLE
feat(authentication): add method `updateProfile`

### ISSUE THREAD

**Issue by robingenz** [capawesome-team/capacitor-firebase#28]
**Is your feature request related to a problem? Please describe:**

Currently there is no option to update the user's profile.

**Describe the solution you'd like:**

Add method `updateProfile`.

**Comment by trancee** [comment]
@robingenz are you currently working on implementing this feature? I actually need it, and if you haven't started yet, I would offer to take over this feature.

**Comment by robingenz** [comment]
@trancee No, i am currently not working on this. You are welcome to implement this feature. Like last time I suggest that you first create the definitions for a first review.
