### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by alexskrms** [capawesome-team/capacitor-firebase#280]
**Plugin(s):**
"@capacitor-firebase/authentication": "^1.2.0",

**Platform(s):**
Android

**Current behavior:**
I can´t do Facebook login in the Ionic + Capacitor app because this error: https://i.imgur.com/Jy4Voej.jpg

Error message: Error al iniciar sesión: Se ha producido un error al acceder a esta aplicación. Vuelve a intentarlo más tarde.

Error message (english): 
```
Error logging in: An error occurred while accessing this application. Please try again later.
```

**Expected behavior:**
It should work and let me authorize the app to get my data.

**Steps to reproduce:**
Configure Facebook Authentication with the steps mentioned by the plugin.

**Capacitor doctor:**
   Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

Installed Dependencies:

  @capacitor/android: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/ios: 4.4.0
  @capacitor/cli: 4.6.1

[error] Missing <manifest package=""> attribute in app/src/main

**Comment by robingenz** [comment]
Please copy the error message as text into this issue for reference.

**Comment by alexskrms** [comment]
> Please copy the error message as text into this issue for reference.

Done

**Comment by robingenz** [comment]
This issue should be a configuration error. Please have a look at this SO answer: https://stackoverflow.com/a/65502513/6731412

**Comment by alexskrms** [comment]
> This issue should be a configuration error. Please have a look at this SO answer: https://stackoverflow.com/a/65502513/6731412

I can't add the hashes without publishing the app on Google Play, do you know how to do that?

**Comment by robingenz** [comment]
> I can't add the hashes on Facebook developers without publishing the app on Google Play

This is not correct. You can just use your local keys for debugging and testing, e.g. https://stackoverflow.com/a/42290810/16289814

**Comment by alexskrms** [comment]
Do you have a way to capture errors in the plugin? In the catch for example for Firebase Errors I use something like this:

```
catch(error){
    if (error instanceof FirebaseError) {
       // Do something
    }
}
```

**Comment by robingenz** [comment]
You can use `try {} catch (error) {}` but it's just a normal `Error` instance.

Please close this issue if the actual problem has been solved.
