### ISSUE TITLE
feat(authentication): add method `deleteUser`

### ISSUE THREAD

**Issue by robingenz** [capawesome-team/capacitor-firebase#281]
**Is your feature request related to a problem? Please describe:**

Currently there is no way to delete the user's profile.

**Describe the solution you'd like:**

Add method `deleteUser`.

**Describe alternatives you've considered:**

**Additional context:**

https://firebase.google.com/docs/auth/web/manage-users#delete_a_user

**Comment by trancee** [comment]
relates to #260

**Comment by robingenz** [comment]
@trancee Thanks! :D 

Closed as duplicate of #260
