### ISSUE TITLE
feat(authentication): add method `reload`

### ISSUE THREAD

**Issue by trancee** [capawesome-team/capacitor-firebase#283]
**Is your feature request related to a problem? Please describe:**

Firebase offers a method to reload user account data, this should be also supported.

**Describe the solution you'd like:**

Add method `reload`.

**Describe alternatives you've considered:**

**Additional context:**

https://firebase.google.com/docs/reference/js/auth.md#reload

**Comment by robingenz** [comment]
Yes, definitely. Feel free to create a PR.
