### ISSUE TITLE
bug: `minimumFetchIntervalInSeconds` always uses defaultValue `43200` if given integer on android

### ISSUE THREAD

**Issue by flogesell** [capawesome-team/capacitor-firebase#286]
**Plugin(s):**

@capacitor-firebase/remote-config: ^1.2.0-dev.8dd4ad6.1668633721

**Platform(s):**

android

**Current behavior:**

the `minimumFetchIntervalInSeconds` (example: `60`) on android always getting replaced by default Value (`43200`) because native implementation uses `getLong` instead of `getInt`

**Expected behavior:**

should use given `minimumFetchIntervalInSeconds` 

**Steps to reproduce:**

Use Integer value for  `minimumFetchIntervalInSeconds` for example `60` and wait for refetching of Values

**Related code:**

```
await FirebaseRemoteConfig.fetchConfig({
				minimumFetchIntervalInSeconds: 60
			});
await FirebaseRemoteConfig.activate();
```

**Other information:**

The function getLong always returns the default value because Integers arent instance of Long

<img width="917" alt="grafik" src="https://user-images.githubusercontent.com/18707145/208629803-8b719016-d7bd-4f31-897b-c12bf6209a6f.png">
<img width="511" alt="grafik" src="https://user-images.githubusercontent.com/18707145/208629967-a3d46e33-1fd7-4e40-9c7e-fffe1185eb43.png">
<img width="1109" alt="grafik" src="https://user-images.githubusercontent.com/18707145/208630191-8e9a28dd-4cbb-4328-9589-2cda7eacc428.png">

**Capacitor doctor:**
```
Latest Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

Installed Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

**Comment by robingenz** [comment]
Closed by #287
