### ISSUE TITLE
fix: The SafetyNet Attestation API is deprecated and has been replaced by the Play Integrity API.

### ISSUE THREAD

**Issue by benj1852** [capawesome-team/capacitor-firebase#293]
Do you plan to make an update to support the new Play Integrity API ?

The SafetyNet Attestation API is deprecated and has been replaced by the Play Integrity API. We are working on a migration path to the Play Integrity API, which we expect to make available within the [SafetyNet deprecation timeline](https://developer.android.com/training/safetynet/deprecation-timeline).

https://firebase.google.com/docs/auth/android/phone-auth#before-you-begin

Thank you.

**Comment by robingenz** [comment]
Thank you for the request!

This is an open issue in the Firebase Android SDK (see https://github.com/firebase/firebase-android-sdk/issues/3890).
As far as I know, there is nothing I can do in the meantime.

For this reason i am closing this issue.

**Comment by robingenz** [comment]
An update for the Firebase Android SDK is now available: https://github.com/firebase/firebase-android-sdk/issues/3890#issuecomment-1488368740
