### ISSUE TITLE
bug: Can not receive authorise event from twitter app 

### ISSUE THREAD

**Issue by VashAlex** [capawesome-team/capacitor-firebase#295]
**Platform(s):**
tested on IOS, but it probably will happen on android too

**Current behavior:**
If user has twitter app on his device, he won't get user authorised credentials. But if user will remove twitter app and try to login via twitter, everything works fine

**Expected behavior:**
Get possibility to prevent opening twitter app

**Steps to reproduce:**
1) Call FirebaseAuthentication.signInWithTwitter()
2) I was redirected to browser window (looks like browser window)
3) when I clicked on Sign In button, it redirected me to the twitter app
and since this moment I can not login to twitter because I get login flow 2 times and do not receive any user creds. However if I will remove twitter app from device, everything work perfectly.

**Related code:**
await FirebaseAuthentication.signInWithTwitter({
        customParameters: [{ key: 'force_login', value: 'true' }]
      }).then(resp => {
      console.log(resp)
    });

**Comment by robingenz** [comment]
The plugin can't overwrite this behavior. 
This must be fixed by the Twitter team. 
Seems like they already work on this, see https://twittercommunity.com/t/login-with-twitter-is-now-broken-on-ios/182126/10.

For this reason I am closing this issue.

**Comment by VashAlex** [comment]
@robingenz 
thanks so much for the answer, I was afraid of this things but it is what it is and no other way than wait for fix from twitter side
