### ISSUE TITLE
bug: GoogleAppMeasurement dependency conflict with plugin capacitor-community/admob

### ISSUE THREAD

**Issue by juanico18** [capawesome-team/capacitor-firebase#301]
**Plugin(s):**

"@capacitor-firebase/analytics": "1.3.0",

**Platform(s):**

iOS

**Current behavior:**

Last version of analytics plugins depends on GoogleAppMeasurement (= 10.2.0) But Admob plugin requires
  GoogleAppMeasurement (< 10.0, >= 7.0)

        [!] CocoaPods could not find compatible versions for pod "GoogleAppMeasurement":
        In Podfile:
        CapacitorCommunityAdmob (from `../../node_modules/@capacitor-community/admob`) was resolved to 4.0.0, which depends on
        Google-Mobile-Ads-SDK (= 9.7.0) was resolved to 9.7.0, which depends on
        GoogleAppMeasurement (< 10.0, >= 7.0)
        
        CapacitorFirebaseAnalytics/Analytics (from `../../node_modules/@capacitor-firebase/analytics`) was resolved to 1.3.0, which depends on
        Firebase/Analytics (= 10.2.0) was resolved to 10.2.0, which depends on
        Firebase/Core (= 10.2.0) was resolved to 10.2.0, which depends on
        FirebaseAnalytics (~> 10.2.0) was resolved to 10.2.0, which depends on
        FirebaseAnalytics/AdIdSupport (= 10.2.0) was resolved to 10.2.0, which depends on
        GoogleAppMeasurement (= 10.2.0)

**Expected behavior:**

Be able to manage dependencies

**Steps to reproduce:**

 npm install --save @capacitor-community/admob
 npm install --save  "@capacitor-firebase/analytics": "1.3.0",
npx cap update

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Capacitor doctor:**

```
insert the output from `npx cap doctor` here
```

**Comment by juanico18** [comment]
I wanted to update remoteConfig from "@capacitor-firebase/remote-config": "^1.2.0-dev.93b28c1.1669212870"
to version 1.3.0 But I have that dependency problem.

What is the most stable version of remoteconfig plugin? Until admob is updated?

Thanks

**Comment by robingenz** [comment]
The most stable remote config plugin version is the latest one. 

Please try the following to specify a specific pod version if you have multiple conflicting versions: https://stackoverflow.com/a/45322760/6731412

Let me know if it works.

**Comment by robingenz** [comment]
Okay, please provide a Minimal, Reproducible Example (see [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)) so I can debug the issue.

**Comment by juanico18** [comment]
@juanico18 YOu can see the problem in this repo https://github.com/juanico18/conflict_dependencies23 by run 
npx cap sync or pod install.

I have detected that the problem is with the manual dependency add it into pod file following readme of firebase analytics.

  # Add your Pods here
  pod 'CapacitorFirebaseAnalytics/Analytics', :path => '../../node_modules/@capacitor-firebase/analytics'

**Comment by robingenz** [comment]
@juanico18 The repo isn't public.

**Comment by juanico18** [comment]
@robingenz Now it is public
