### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by Bokitza** [capawesome-team/capacitor-firebase#304]
**Plugin(s):**
Firebase Authentication

**Platform(s):**
Android

**Current behavior:**
Throws an error: 

Attempt to invoke virtual method 'java.lang.Boolean com.getcapacitor.PluginCall.getBoolean(java.lang.String, java.lang.Boolean)' on a null object reference

probably after some kind of native login attempt 

**Steps to reproduce:**
cant really say cuz its a sentry issue- but as you can see from sentry log its somewhat connected with a cancelled attempt to login

**Sentry Logging:**
<img width="872" alt="image" src="https://user-images.githubusercontent.com/58147254/213540547-d9b59a72-d9b8-4229-a53b-32f55ee45e4b.png">

**Capacitor doctor:**

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.6.2
  @capacitor/core: 4.6.2
  @capacitor/android: 4.6.2
  @capacitor/ios: 4.6.2

Installed Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

[success] iOS looking great! 👌
[error] Missing <manifest package=""> attribute in app/src/main
```

**Comment by robingenz** [comment]
Which plugin version do you use?

**Comment by Bokitza** [comment]
1.2.0

**Comment by robingenz** [comment]
Thank you for reporting! Will be fixed in the upcoming version.
