### ISSUE TITLE
[analytics] Any way to get the appInstanceID?

### ISSUE THREAD

**Issue by nijakobius** [capawesome-team/capacitor-firebase#310]
### Is your feature request related to a problem? Please describe:
I am trying to set up the RevenueCat -> Firebase integration [described here](https://www.revenuecat.com/docs/firebase-integration#set-firebaseappinstanceid-as-a-subscriber-attribute).

They require the `appInstanceID` [described here in the Firebase Docs](https://firebase.google.com/docs/reference/swift/firebaseanalytics/api/reference/Classes/Analytics#/c:objc(cs)FIRAnalytics(cm)appInstanceID).

### Describe the solution you'd like:
It would be great to have a method to extract this `appInstanceID`.

Or is this already possible?

(I believe it is different from  the applicationId you [can get from @capacitor-firebase/app](@capacitor-firebase/app). As that is always the same across users/devices/installations...)

**Comment by robingenz** [comment]
Thanks for the detailed request. I add this to the next release.

**Comment by robingenz** [comment]
```
npm i @capacitor-firebase/analytics@1.3.0-dev.ceaa8dc.1676791198
```
