### ISSUE TITLE
bug: sendSignInEmailLink [error] - {"code":"UNIMPLEMENTED"}

### ISSUE THREAD

**Issue by seanaguinaga** [capawesome-team/capacitor-firebase#313]
**Plugin(s):**

@capacitor-firebase/authentication

**Platform(s):**

iOS

**Current behavior:**

```
⚡️  To Native ->  FirebaseAuthentication sendSignInLinkToEmail 46591705
⚡️  TO JS undefined
⚡️  [error] - {"code":"UNIMPLEMENTED"}
```

**Expected behavior:**

Would send email successfully

**Steps to reproduce:**

**Related code:**

```
const sendSignInLinkToEmail = async (email: string) => {
  await FirebaseAuthentication.sendSignInLinkToEmail({
    email,
    actionCodeSettings: actionCodeSettings({}),
  });
  // The link was successfully sent. Inform the user.
  // Save the email locally so you don't need to ask the user for it again
  // if they open the link on the same device.
  const { Preferences } = await import("@capacitor/preferences");
  await Preferences.set({ key: "emailForSignIn", value: email });
};
```

**Other information:**

I followed all the set up steps and this error comes up

**Capacitor doctor:**

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.6.3
  @capacitor/core: 4.6.3
  @capacitor/android: 4.6.3
  @capacitor/ios: 4.6.3

Installed Dependencies:

  @capacitor/cli: 4.6.3
  @capacitor/core: 4.6.3
  @capacitor/android: 4.6.3
  @capacitor/ios: 4.6.3

[success] iOS looking great! 👌
```

**Comment by robingenz** [comment]
Which plugin version do you use?

**Comment by seanaguinaga** [comment]
`"@capacitor-firebase/authentication": "^1.3.0"`

**Comment by robingenz** [comment]
I just tested it and it works for me.
Please make sure you use the latest version of the plugin and provide a Minimal, Reproducible Example (see [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)) in a public GitHub repository so I can debug the issue.

**Comment by seanaguinaga** [comment]
I got it to work eventually in the nx/nrwl monorepo by making sure that the package.json in the project folder has versions like this:

```
{
  "name": "ionic",
  "dependencies": {
    "@capacitor-firebase/authentication": "*",
    "@capacitor/app": "*",
    "@capacitor/core": "*",
    "@pantrist/capacitor-firebase-dynamic-links": "*",
    "@capacitor/preferences": "*",
    "@capacitor/splash-screen": "*"
  },
  "devDependencies": {
    "@capacitor/cli": "*"
  }
}
```

Otherwise the plugins never installed/resolved when syncing them with the capacitor cli
