### ISSUE TITLE
[Bug][Messaging] - W/FirebaseMessaging: Missing Default Notification Channel metadata in AndroidManifest. Default value will be used.

### ISSUE THREAD

**Issue by Bokitza** [capawesome-team/capacitor-firebase#321]
**Plugin(s):**
  "@capacitor/cli": "^4.6.1",
  "@capacitor/core": "^4.6.1",
  "@capacitor-firebase/messaging": "^1.3.0",

**Platform(s):**
Android

**Current behavior:**
I try to request permission, get an answer that "permission is granted", but than wont see the app in the Notification list in the settings. Of course no message would appear. 
after sending a notification from firebase console - i get the above error in android studio:
```W/FirebaseMessaging: Missing Default Notification Channel metadata in AndroidManifest. Default value will be used.```

when i reopen the app - the prompt is shown - yet the notification wont appear -from here and on everything works correctly.

<img width="400" alt="image" src="https://user-images.githubusercontent.com/58147254/219814366-97913f33-6be1-41c1-bc1b-466bb677b088.png">

![image](https://user-images.githubusercontent.com/58147254/219814596-f7e1f0fe-e751-4efe-8c68-aef8068b687b.png)

**Expected behavior:**
Prompt should appear on start, as declared in the code.

**Steps to reproduce:**
add this code to index.js in a react app:

```
requestPermissions();
subscribeToTopic("testing");
```

and open the app.
now send a message from fb console to topic "testing" and wait for the log to appear in android studio
now go to the app...

**Related code:**
mentioned above :P

**Other information:**
Android 13
Pixel 6a

**Capacitor doctor:**

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.6.3
  @capacitor/core: 4.6.3
  @capacitor/android: 4.6.3
  @capacitor/ios: 4.6.3

Installed Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/ios: 4.6.1
  @capacitor/android: 4.6.1

[success] iOS looking great! 👌
[error] Missing <manifest package=""> attribute in app/src/main
```

**Comment by robingenz** [comment]
Thank you for your issue. I will look into this.

**Comment by robingenz** [comment]
This issue is related to https://github.com/capawesome-team/capacitor-firebase/pull/300 and https://github.com/ionic-team/capacitor-plugins/issues/1135.
