### ISSUE TITLE
bug: signInWithGoogle: ⚡️ TO JS undefined

### ISSUE THREAD

**Issue by klyse** [capawesome-team/capacitor-firebase#323]
**Plugin(s):**
`FirebaseAuthentication`, `PushNotifications`

**Platform(s):**
ios

**Current behavior:**
`signInWithGoogle` produces the following logs in xcode:
```
⚡️  To Native ->  FirebaseAuthentication signInWithGoogle 128495494
⚡️  TO JS undefined
```

**Expected behavior:**
login succeeds

**Steps to reproduce:**
 Call `signInWithGoogle` in svelteKit (Static) project 

**Related code:**

javascript
```
FirebaseAuthentication.signOut();
const result = await FirebaseAuthentication.signInWithGoogle();

const credential = GoogleAuthProvider.credential(result.credential?.idToken);
const auth = getAuth();
await signInWithCredential(auth, credential);
```

AppDelegate
```
func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey: Any] = [:]) -> Bool {
    // added code according to docs
    if Auth.auth().canHandle(url) {
      return true
    }
    return ApplicationDelegateProxy.shared.application(app, open: url, options: options)
}
```

**Other information:**
I'm using svelteKit.
Could be related to: https://github.com/capawesome-team/capacitor-firebase/discussions/307
Works in Android and on web.

**Capacitor doctor:**

```
~/projects/magun main* ❯ npx cap doctor
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.6.3
  @capacitor/core: 4.6.3
  @capacitor/android: 4.6.3
  @capacitor/ios: 4.6.3

Installed Dependencies:

  @capacitor/cli: 4.6.2
  @capacitor/core: 4.6.2
  @capacitor/ios: 4.6.3
  @capacitor/android: 4.6.3

[success] iOS looking great! 👌
[error] Missing <manifest package=""> attribute in app/src/main
```

**Comment by robingenz** [comment]
I just answered https://github.com/capawesome-team/capacitor-firebase/discussions/307. Maybe this helps you.

If not, please also provide a Minimal, Reproducible Example (see [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)) in a public GitHub repository so I can debug the issue.

**Comment by klyse** [comment]
I ended up debugging this the past two days 🤯
I found solution in this repo: https://github.com/aaronksaunders/mobile-gauth/blob/master/src/firebase-service.ts

The issue was a missing code here:
```javascript
if (Capacitor.isNativePlatform()) {
        const app = initializeApp(firebaseConfig);

	// require to work appropriately on native devices
	initializeAuth(app, {
		persistence: indexedDBLocalPersistence
	});
}
```

**Comment by robingenz** [comment]
Thank you, I will document this!
