### ISSUE TITLE
[analytics] Purchase events and revenue not tracked for Android (iOS works)

### ISSUE THREAD

**Issue by nijakobius** [capawesome-team/capacitor-firebase#325]
**Plugin(s):**
@capacitor-firebase/analytics 1.3.0 and now
@capacitor-firebase/analytics 1.3.0-dev.ceaa8dc.1676791198
@capacitor-firebase/app@1.3.0
firebase@9.17.1

**Platform(s):**
Android only

**Current behavior:**
In Google Analytics I can see monetization events and revenue for iOS **but not for Android**:

<img width="1989" alt="Screenshot 2023-02-20 at 13 54 04" src="https://user-images.githubusercontent.com/37240226/220117303-37bf0fcd-d016-4605-8a96-e1fad3364bc5.png">

**Expected behavior:**
Android monetization events and revenue should be seen in the above screen shot (there was actually more Android revenue in the same time span).

**Related code:**
I use the following functions, but nothing explicitly to track revenue (e.g. there is no event where I add revenue as a parameter or so):
```
Capacitor.Plugins.FirebaseAnalytics.setUserId();
Capacitor.Plugins.FirebaseAnalytics.setCurrentScreen();
Capacitor.Plugins.FirebaseAnalytics.setUserProperty();
Capacitor.Plugins.FirebaseAnalytics.logEvent();
```

**Other information:**
Everything else works great: All other events are shown for both Android and iOS.

**Capacitor doctor:**
```
Latest Dependencies:

  @capacitor/cli: 4.6.3
  @capacitor/core: 4.6.3
  @capacitor/android: 4.6.3
  @capacitor/ios: 4.6.3

Installed Dependencies:

  @capacitor/cli: 4.6.3
  @capacitor/android: 4.6.3
  @capacitor/core: 4.6.3
  @capacitor/ios: 4.6.3
```

**Comment by robingenz** [comment]
I assume you are using RevenueCat because of [this comment](https://github.com/capawesome-team/capacitor-firebase/issues/310#issue-1570378279) from you in another issue.
Unfortunately, I have no experience with RevenueCat. From the documentation I understand that the RevenueCat SDK sends the events to Firebase Analytics:

> The Google Analytics portion of this integration allows RevenueCat to send subscription lifecycle events to Firebase Analytics / Google Analytics.

Please make sure that the `appInstanceId` is set correctly on Android. If this is already the case, contact the provider of the RevenueCat Android SDK / Plugin and report the issue there.

You are welcome to refer to this issue. I am available to answer any questions.

**Comment by nijakobius** [comment]
> I assume you are using RevenueCat because of [this comment](https://github.com/capawesome-team/capacitor-firebase/issues/310#issue-1570378279) from you in another issue. Unfortunately, I have no experience with RevenueCat. From the documentation I understand that the RevenueCat SDK sends the events to Firebase Analytics:
> 
> > The Google Analytics portion of this integration allows RevenueCat to send subscription lifecycle events to Firebase Analytics / Google Analytics.
> 
> Please make sure that the `appInstanceId` is set correctly on Android. If this is already the case, contact the provider of the RevenueCat Android SDK / Plugin and report the issue there.
> 
> You are welcome to refer to this issue. I am available to answer any questions.

Actually, I haven't implemented any of the `appInstanceId` code yet. I also haven't configured the RevenueCat<->Firebase integration at all. That's why I had assumed this has nothing to do with RevenueCat.

Then the more fundamental question is: (For someone not using RevenueCat), would you expect this plugin (alone) to send any monetization events and revenue data to Firebase/Analytics?

**Comment by nijakobius** [comment]
Thanks for the info :)

I'll know more in about a week when I have fully implemented the integration. I'll update this issue then.

**Comment by nijakobius** [comment]
I think I found the solution: One must activate "Firebase > Project Settings > Integration > Google Play"
