### ISSUE TITLE
bug: Google Signin Not Working after publishing to Playstore 

### ISSUE THREAD

**Issue by zagham-nadeem** [capawesome-team/capacitor-firebase#327]
**Plugin(s):**

"@capacitor-firebase/authentication": "1.2.0",

**Platform(s):**

Android

**Current behavior:**

I have created the app name bepositive i have used "@capacitor-firebase/authentication": "1.2.0",
google signin working fine while i create apk and test
but after publishing on playstore not working 
here is my app playstore link
[BePositive](https://play.google.com/store/apps/details?id=com.zagham.bepositive)
**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
async googleLogin() {
      const result = await FirebaseAuthentication.signInWithGoogle();
      this.apiCall.api_postLogin(this.UserData);
    }
```

**Other information:**

**Capacitor doctor:**

```
Latest Dependencies:

  @capacitor/cli: 4.6.3
  @capacitor/core: 4.6.3
  @capacitor/android: 4.6.3
  @capacitor/ios: 4.6.3

Installed Dependencies:

  @capacitor/cli: 4.2.0
  @capacitor/core: 4.2.0
  @capacitor/android: 4.2.0
  @capacitor/ios: 4.2.0

[success] Android looking great! 👌
```

**Comment by robingenz** [comment]
Thank you for your request!
`not working` is too little information. Do you have any error messages?

**Comment by zagham-nadeem** [comment]
sir i am getting this issue in console
`getRecentTasks: taskId=30443   userId=0   baseIntent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.zagham.bepositive/.MainActivity }`

**Comment by zagham-nadeem** [comment]
this is capacitor.config.ts code
`FirebaseAuthentication: {
    skipNativeAuth: false,
      providers: ["facebook.com", "google.com"],
  },`

**Comment by robingenz** [comment]
> sir i am getting this error in logcat `getRecentTasks: taskId=30443 userId=0 baseIntent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.zagham.bepositive/.MainActivity }`

This is no error, just a normal debug message. Unfortunately this does not help.

**Comment by zagham-nadeem** [comment]
than sir how do i explain

**Comment by robingenz** [comment]
You must log the error messages in your app in production mode.

**Comment by zagham-nadeem** [comment]
can i share my code

**Comment by robingenz** [comment]
Reviewing code is time-consuming. That's why I want to see the error message first.

**Comment by zagham-nadeem** [comment]
sir its not giving any kind of error
thats why i have created the issue

**Comment by robingenz** [comment]
> sir its not giving any kind of error

I would be very surprised. Maybe you are simply not logging the error.

**Comment by zagham-nadeem** [comment]
hey sir what is `skipNativeAuth: false` in capacitor.config.ts

**Comment by robingenz** [comment]
Please take a look at the documentation: 

> Configure whether the plugin should skip the native authentication. Only needed if you want to use the Firebase JavaScript SDK. This configuration option has no effect on Firebase account linking. Note that the plugin may behave differently across the platforms. Only available for Android and iOS.

You only need this if you want to use the Firebase JS SDK. It skips the authentication on the native layer (Android and iOS) so that you can authenticate the user on the web layer.

**Comment by robingenz** [comment]
But this should not be related to your issue because it behaves the same locally and in the Play Store.

**Comment by zagham-nadeem** [comment]
its solved the error is fixed

**Comment by zagham-nadeem** [comment]
thanks for your reply sir

**Comment by zagham-nadeem** [comment]
all the issue is that we have to provide the sha1 in firebase not the android studio sha1 
play store provide its own sha1 keys so we have to provide these sha1 of playstore in firebase
