### ISSUE TITLE
No result when signInWithGoogle in Ios

### ISSUE THREAD

**Issue by ludonoel1** [capawesome-team/capacitor-firebase#329]
Hello,
I implemented your plugin and it is working on Android and Browser but not working on IOS.

SignInWithGoogle return nothing,I Get answer.

Iwhat I did:
- add your library 
-  àdd your pod
- npx cap update

Do you have an idea..?

**Comment by robingenz** [comment]
Make sure to follow the installation steps correctly: https://github.com/capawesome-team/capacitor-firebase/blob/main/packages/authentication/docs/setup-google.md#ios

If it still does not work, please provide a Minimal, Reproducible Example (see [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)) in a public GitHub repository so I can debug the issue.

You can also take a look at this issue: https://github.com/capawesome-team/capacitor-firebase/issues/323

**Comment by ludonoel1** [comment]
When I add "/Google" in pod name, after nix cap update, the name has changed..

Please find a repo with my config, https://github.com/ludonoel1/ionic-google

**Comment by robingenz** [comment]
> When I add "/Google" in pod name, after nix cap update, the name has changed..

In this case you add the pod to the wrong place. This is the correct place: https://github.com/robingenz/capacitor-firebase-authentication-demo/blob/1bfe6c90994e69b9cd159c0fafba621bab90c858/ios/App/Podfile#L24

Should be this line in your project: https://github.com/ludonoel1/ionic-google/blob/69b0d0803105601742bd8fbe5ee7c725a4c31f87/ios/App/Podfile#L35
