### ISSUE TITLE
bug: Facebook login failed on Android as embedded browser is disabled 

### ISSUE THREAD

**Issue by typefox09** [capawesome-team/capacitor-firebase#331]
**Plugin(s):**
@capacitor-firebase/authentication": "^1.3.0

![Screenshot_20230228_180155_Facebook](https://user-images.githubusercontent.com/61811299/221779164-8be3ac15-b722-4630-ad66-f6157afe1ffc.jpg)
**Platform(s):**
Android 

**Current behavior:**
Logging in with Faceboook causes a security error due to being used in an embedded browser. Normally the Facebook app handles the login, however this isn't happening (even though my Facebook app is installed and logged in.

**Expected behavior:**
The user should be logged in

**Steps to reproduce:**
Initialising the code sample below to start Facebook login on an Android device using Capacitor 4

**Related code:**

strings.xml
  <string name="facebook_app_id">["MY ACTUALY APP ID NUMBER"]</string>
  <string name="fb_login_protocol_scheme">fb["MY ACTUALY APP ID NUMBER"]</string>
  <string name="facebook_client_token">["MY ACTUALY APP CLIENT NUMBER"]</string>
  
  
  Android manifest:
  
          <meta-data
            android:name="com.facebook.sdk.ApplicationId"
            android:value="@string/facebook_app_id" />

        <meta-data
            android:name="com.facebook.sdk.ClientToken"
            android:value="@string/facebook_client_token" />

        <activity
            android:exported="true"
            android:name="com.facebook.FacebookActivity"
            android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"
            android:label="@string/app_name" />
  
          <activity
            android:name="com.facebook.CustomTabActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data android:scheme="@string/fb_login_protocol_scheme" />
            </intent-filter>
        </activity>

Function that's being used to call auth:

const result = await FirebaseAuthentication.signInWithFacebook('email')
                        const credential = FacebookAuthProvider.credential(
                            result.credential?.accessToken,
                        );
                        await signInWithCredential(auth, credential)

```
insert short code snippets here
```

**Other information:**

**Capacitor doctor:**

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.7.0
  @capacitor/core: 4.7.0
  @capacitor/android: 4.7.0
  @capacitor/ios: 4.7.0

Installed Dependencies:

  @capacitor/cli: 4.0.1
  @capacitor/core: 4.0.1
  @capacitor/android: 4.0.1
  @capacitor/ios: 4.0.1

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

**Comment by robingenz** [comment]
Thank you for your request.
Please provide a Minimal, Reproducible Example (see [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)) in a public GitHub repository so I can debug the issue.
