### ISSUE TITLE
bug: google signin always uses last account used

### ISSUE THREAD

**Issue by itsnamangoyal** [capawesome-team/capacitor-firebase#332]
**Plugin(s):**
@capacitor-firebase/authentication: ^1.3.0

**Platform(s):**
android, (I'm not implementing iOS, so can't talk about that)

**Current behavior:**
when using signInWithGoogle(), it automatically selects the last account used to signin. But for web it always asks to select account. 
imo android behaviour is an error.

**Expected behavior:**
Always asks for which account to signin even if an account has been used to signin before.

**Steps to reproduce:**
1. signin with google.
2. signout.
3. singin again with google.

**Comment by robingenz** [comment]
Please take a look at this comment: https://github.com/robingenz/capacitor-firebase-authentication/issues/129#issuecomment-1027113318

**Comment by ludonoel1** [comment]
Hello, 
I had the same error as you, but now I use this code :
`return FirebaseAuthentication.signOut().then(() => {
            const auth = getAuth();
            return signOut(auth);
          });`
          
          And everything works
