### ISSUE TITLE
bug:  SignIn Failed with facebook and android

### ISSUE THREAD

**Issue by ludonoel1** [capawesome-team/capacitor-firebase#333]
**Plugin(s):**

- authentication facebook
-     "@capacitor-firebase/authentication": "^1.3.0",
capacitor v4

**Platform(s):**

android

**Current behavior:**

- I click on my button to signin with Facebook but I get error message "Error: signIn failed.\n    at returnResult (http://localhost/:422:32)\n    at win.androidBridge.onmessage (http://localhost/:397:21)".
 It worked 2 days ago..
However, it's working on browser. 
I did like you wrote in your doc..

**Expected behavior:**

Click on my button,facebook popup apparead, accept everything ....

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Capacitor doctor:**

```
insert the output from `npx cap doctor` here
```

**Comment by robingenz** [comment]
Thank you for your request.
Please provide a Minimal, Reproducible Example (see [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)) in a public GitHub repository so I can debug the issue.

**Comment by ludonoel1** [comment]
Please find a repo with my config, https://github.com/ludonoel1/ionic-google

**Comment by ludonoel1** [comment]
Tell me if it's normal to get : "signIn failed" or not.
On browser I get "You already have an account with other credentials...."

**Comment by robingenz** [comment]
Please paste the Android Studio Logcat log here.

**Comment by ludonoel1** [comment]
signInwithFacebook return "Already has an account" whereas on android returns "signIn failed"

**Comment by robingenz** [comment]
> com.google.firebase.auth.FirebaseAuthUserCollisionException: An account already exists with the same email address but different sign-in credentials. Sign in using a provider associated with this email address.

Same issue on Android but the error message is not the same.
This will be improved in issue #25.
I close this as a duplicate.

**Comment by ludonoel1** [comment]
Do you need help for the improvement ?

Because  capacitor 5 is so far away ...

Do you  have a patch or something ?

**Comment by robingenz** [comment]
No, there is no patch yet.
I will implement it as soon as I get the chance. 
There is also the possibility to sponsor this issue and of course PRs are welcome.
