### ISSUE TITLE
feat(authentication): resend sms verification code

### ISSUE THREAD

**Issue by robingenz** [capawesome-team/capacitor-firebase#34]
**Is your feature request related to a problem? Please describe:**

Currently it is not possible to request the SMS verification code again.

**Describe the solution you'd like:**

Add an option to resend the sms verification code.

**Comment by 67pankaj** [comment]
@robingenz any update on resend sms implementation

**Comment by robingenz** [comment]
Not yet, I will work on it as soon as I have some more time. PRs are welcome.

**Comment by elliott44k** [comment]
Any info on what needs to be done for this? I'm happy to start contributing to the library since I'll be using it.

**Comment by hermitdemschoenenleben** [comment]
@elliott44k have a look at the corresponding PR of capacitor-firebase-auth: https://github.com/baumblatt/capacitor-firebase-auth/pull/206/files

**Comment by robingenz** [comment]
Closed by #273
