### ISSUE TITLE
bug:   Recieving push notification while app is active and also notificationReceived got triggered at the same time, On android works fine On IOS I am facing this problem!

### ISSUE THREAD

**Issue by prakash03yes** [capawesome-team/capacitor-firebase#347]
![image](https://user-images.githubusercontent.com/77315058/227838349-e70705d0-5089-450f-b3cd-3a95b7bcb7f6.png)

**Comment by prakash03yes** [comment]
Fixed it by adding few lines on the file NotificationRouter

    public func userNotificationCenter(_ center: UNUserNotificationCenter,
                                       willPresent notification: UNNotification,
                                       withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
        let presentationOptions: UNNotificationPresentationOptions?

        if notification.request.trigger?.isKind(of: UNPushNotificationTrigger.self) == true {
            presentationOptions = pushNotificationHandler?.willPresent(notification: notification)
        } else {
            presentationOptions = localNotificationHandler?.willPresent(notification: notification)
        }
        
        
        // Modified here starts
        if UIApplication.shared.applicationState == .active {
            completionHandler([])
        }else{
            completionHandler(presentationOptions ?? [])
        }
        //  Modified here ends

    }

**Comment by robingenz** [comment]
Thank you for your request.
Please fill out the issue template correctly so I get all the information I need and create a new issue.
