### ISSUE TITLE
feat(authentication): add Sign-In Anonymously

### ISSUE THREAD

**Issue by robingenz** [capawesome-team/capacitor-firebase#35]
**Is your feature request related to a problem? Please describe:**

Sign-In Anonymously is currently not supported.

**Describe the solution you'd like:**

Support Sign-In Anonymously and `linkWith...` methods.

Methods:

- `signInAnonymously`
- `linkWithApple`
- `linkWithGoogle`
- ...

**Comment by davidecampello** [comment]
Hi! Are you planning to implement this features?
Thanks

**Comment by robingenz** [comment]
> Hi! Are you planning to implement this features? Thanks

Yes, it's planned

**Comment by trancee** [comment]
@robingenz Have you made any progress on this one already? If not, I would like to help you out with the implementation.

**Comment by robingenz** [comment]
@trancee No, there is no progress yet. You are very welcome to contribute! If you have any questions, let me know. Feel free to let me look at the Typescript definitions first before you do the actual implementation (just create a Draft PR).

**Comment by trancee** [comment]
> @trancee No, there is no progress yet. You are very welcome to contribute! If you have any questions, let me know. Feel free to let me look at the Typescript definitions first before you do the actual implementation (just create a Draft PR).

Sure, I will create the definitions first before starting the implementation and let you review them.
