### ISSUE TITLE
feat(authentication): Email Link Authentication

### ISSUE THREAD

**Issue by robingenz** [capawesome-team/capacitor-firebase#36]
**Is your feature request related to a problem? Please describe:**

[Firebase Email Link Authentication](https://firebase.google.com/docs/auth/web/email-link-auth) is currently not supported.

**Describe the solution you'd like:**

Support Firebase Email Link Authentication.

**Comment by DwieDima** [comment]
Is there any ETA for this feature? 🔥

**Comment by robingenz** [comment]
Not yet, but I should get to it in Q3.

**Comment by trancee** [comment]
@robingenz Have you made any progress on this one already? If not, I would like to help you out with the implementation.

**Comment by robingenz** [comment]
@trancee Not yet. You are welcome to submit a PR. Let me know if you have any questions.

**Comment by DwieDima** [comment]
Hi @trancee thanks a lot for the PR!
Is there any way to get `skipNativeAuth` working together with magic link auth?

**Comment by robingenz** [comment]
Implemented in #172
