### ISSUE TITLE
bug: iOS Remote configs are not loading with a first load

### ISSUE THREAD

**Issue by prajapatijay95** [capawesome-team/capacitor-firebase#364]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [ ] Authentication
- [ ] Crashlytics
- [ ] Cloud Messaging
- [ ] Performance
- [X] Remote Config

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [ ] Android
- [X] iOS
- [ ] Web

### Current behavior

App is not loading the remote config with a fresh install and first load.

### Expected behavior

App must always load the remote config even with the first load.

### Reproduction

none

### Steps to reproduce

Uninstall the existing app if any.
Install the fresh app and load the firebase remote config, it's getting loaded with the static (default) values and not fetching it from the server.
Close the app and open it again, it works.

`await FirebaseRemoteConfig.fetchConfig({
    minimumFetchIntervalInSeconds: 1200,
  });`
`await FirebaseRemoteConfig.activate();`
`const { value } = await FirebaseRemoteConfig.getString({
    key: 'key',
  });`

The value is empty.

### Other information

<img width="997" alt="image" src="https://user-images.githubusercontent.com/48172481/232960537-37c53246-5973-4a0d-aecf-86a94416cf70.png">

In iOS methods, after the implementation it's calling `call.resolve()` which is causing this issue and not waiting to complete the fetch or activate. 

### Capacitor doctor

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.7.3
  @capacitor/core: 4.7.3
  @capacitor/android: 4.7.3
  @capacitor/ios: 4.7.3

Installed Dependencies:

  @capacitor/cli: 4.7.1
  @capacitor/core: 4.7.1
  @capacitor/android: 4.7.3
  @capacitor/ios: 4.7.1

[success] iOS looking great! 👌

### Before submitting

- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
Thank you for reporting this.
I released a dev version for Capacitor 4:
```
npm i @capacitor-firebase/remote-config@1.4.0-dev.5d562ff.1681878046
```

The fix will be included in the next official release (Capacitor 5).

**Comment by prajapatijay95** [comment]
Thanks @robingenz for a quick response.
