### ISSUE TITLE
feat: Set color and channel general and push 

### ISSUE THREAD

**Issue by josuelmm** [capawesome-team/capacitor-firebase#370]
### Current problem

Set color and channel general and push 

### Preferred solution

```
<meta-data android:name="com.google.firebase.messaging.default_notification_color" android:resource="@string/color"
        />
<meta-data android:name="com.google.firebase.messaging.default_notification_channel_id" android:value="@string/default_notification_channel_id"
        />
```

**Comment by robingenz** [comment]
You have to configure this in your `AndroidManifest.xml`. The plugin has no impact on this.
Example with the notification icon: https://github.com/robingenz/ionic-capacitor-firebase-messaging-demo/blob/06f8c00e1575fef9ff8c9253a61a0f4803a501c4/android/app/src/main/AndroidManifest.xml#L14

Let me know if you have any other questions.
