### ISSUE TITLE
Unable to find a specification for `FirebaseAnalyticsWithoutAdIdSupport (= 10.8.0)`

### ISSUE THREAD

**Issue by typefox09** [capawesome-team/capacitor-firebase#376]
### Plugin(s)

- [X] Analytics
- [ ] App
- [ ] App Check
- [ ] Authentication
- [ ] Crashlytics
- [ ] Cloud Messaging
- [ ] Performance
- [ ] Remote Config

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [ ] Android
- [X] iOS
- [ ] Web

### Current behavior

After installing the latest version of this package and running npx cap sync, an error appears (pasted below) when using the Firebase Analytics WithoutAdIdSupport package. I tried commenting this out and using the standard package (With ID Ad Support) and then everything works.

This isn't a viable solution though due to App Tracking Transparency.

I tried running "pod repo update", "pod install", "-- repo-update", however that doesn't solve anything.

Also tried deleting the Podfile.lock. This didn't work either.

✖ update ios - failed!
[error] Analyzing dependencies
        [!] Unable to find a specification for `FirebaseAnalyticsWithoutAdIdSupport (= 10.8.0)` depended upon by
        `CapacitorFirebaseAnalytics/AnalyticsWithoutAdIdSupport`
        
        You have either:
        * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
        * mistyped the name or version.
        * not added the source repo that hosts the Podspec to your Podfile.
        
       

### Expected behavior

npx cap sync should pass

### Reproduction

private repo

### Steps to reproduce

1. Install latest version of this package
2. Add "pod 'CapacitorFirebaseAnalytics/AnalyticsWithoutAdIdSupport', :path => '../../node_modules/@capacitor-firebase/analytics'" to capacitor_pods section (# Add your pods here)
3. npx cap sync

### Other information

✖ update ios - failed!
[error] Analyzing dependencies
        [!] Unable to find a specification for `FirebaseAnalyticsWithoutAdIdSupport (= 10.8.0)` depended upon by
        `CapacitorFirebaseAnalytics/AnalyticsWithoutAdIdSupport`
        
        You have either:
        * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
        * mistyped the name or version.
        * not added the source repo that hosts the Podspec to your Podfile.

### Capacitor doctor

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.0.0
  @capacitor/core: 5.0.0
  @capacitor/android: 5.0.0
  @capacitor/ios: 5.0.0

Installed Dependencies:

  @capacitor/cli: 5.0.0
  @capacitor/core: 5.0.0
  @capacitor/ios: 5.0.0
  @capacitor/android: 5.0.0

[success] iOS looking great! 👌

### Before submitting

- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
Thank you for your request. I'll take a look in the next few days.

**Comment by typefox09** [comment]
Is there an update on this? Currently unable to launch new app updates as we don't use App Tracking Transparency

**Comment by typefox09** [comment]
Found the fix. 


in CapacitorFirebaseAnalytics.podspec change the following:

`
  s.subspec 'AnalyticsWithoutAdIdSupport' do |analyticsWithoutAdIdSupport|
    analyticsWithoutAdIdSupport.dependency 'FirebaseAnalyticsWithoutAdIdSupport', '10.8.0'
  end
`

To:

`
  s.subspec 'AnalyticsWithoutAdIdSupport' do |analyticsWithoutAdIdSupport|
    analyticsWithoutAdIdSupport.dependency 'Firebase/AnalyticsWithoutAdIdSupport', '10.8.0'
  end
`

**Comment by robingenz** [comment]
Sorry, i am currently extremely busy. I will fix this.

**Comment by robingenz** [comment]
You can use this dev version in the meantime: 

```
npm i @capacitor-firebase/analytics@5.0.0-dev.351d12d.1683650804
```
