### ISSUE TITLE
bug: SMS verification code not received and an empty verification ID

### ISSUE THREAD

**Issue by bravao911** [capawesome-team/capacitor-firebase#380]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [X] Authentication
- [ ] Crashlytics
- [ ] Cloud Messaging
- [ ] Performance
- [ ] Remote Config

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [X] Android
- [X] iOS
- [ ] Web

### Current behavior

I am experiencing an issue where the phone authentication process fails with the error message "The phone auth credential was created with an empty verification ID." This error occurs when attempting to confirm the verification code received via SMS. 

However, I am not receiving the SMS verification code. I have tested this with multiple phone numbers, but none of them receive the code.

I have followed the plugin's documentation and made sure that the Firebase project is properly configured. However, the phoneCodeSent event is not triggered, and as a result, the verification ID is empty when attempting to confirm the verification code.

I have also verified that the phone numbers I'm using are correct and capable of receiving SMS messages. Additionally, I have confirmed that my dependencies are up to date and using the latest version of the plugin.

This issue prevents users from signing in with their phone numbers, as they are unable to receive the necessary verification code.

### Expected behavior

I expected to receive the SMS verification code when attempting to sign in with a phone number. The plugin's documentation indicates that the phoneCodeSent event should be triggered, and I should be prompted to enter the verification code that was sent to my mobile device.

I have verified that the phone numbers I'm using are capable of receiving SMS messages, and I have double-checked that the phone numbers are entered correctly in the code. I expect to receive the verification code and be able to confirm it, allowing users to sign in with their phone numbers successfully.

### Reproduction

https://github.com/bravao911/TaxiPort-Userapp

### Steps to reproduce

1. Install the Firebase Authentication plugin for Capacitor version 5.0.0.
2. Create a new project and set up Firebase Authentication with phone number sign-in enabled.
3. Firebase  App Check ios registered. 
4. Firebase GoogleService-info.plist exist into platform/ios/app/app.
5. Implement the provided example code for phone number sign-in using the signInWithPhoneNumber and confirmVerificationCode functions.
6. Build and run the project on a device.
7. Enter a valid phone number in the application UI and proceed with the sign-in process. Observe that the SMS verification code is not received on the provided phone number.
8. Check the console or logcat output for any error messages related to the SMS code verification process.

Full code : 

```
  async login() {
    FirebaseAuthentication.signInWithPhoneNumber({phoneNumber: this.CountryCode +this.phone }).then(res => {
      FirebaseAuthentication.addListener('phoneCodeSent', async event => {
        console.log(event)
        this.a.create({
          message: 'ادخل الكود المرسل اليك',
          backdropDismiss: false,
          cssClass: 'alert-rtl',
          inputs: [{
            name: 'code',
            type: 'text',
            placeholder: 'xxxxxxxx'
          }],
          buttons: [
            { text: 'الغاء', },
            {
              text: 'تاكيد',
              handler: (data) => {
                if (data.code) {
                  FirebaseAuthentication.confirmVerificationCode({
                    verificationId: event.verificationId,
                    verificationCode: this.api.opreationconvertNumber(data.code),
                  }).then(async (user: any) => {
                    console.log(user)
                  })
                } else {
                  this.api.toast('يرجى ادخال رمز الكود المرسل اليك عبر رسائل نصية', 3000, 'danger')
                  return false
                }
              }
            }
          ]
        }).then(p => {
          p.present()
        })
      })
    })
  }
```

### Other information

[screenshots  erorr ](https://ibb.co/SV0MR7r)

### Capacitor doctor

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.0.4
  @capacitor/core: 5.0.4
  @capacitor/android: 5.0.4
  @capacitor/ios: 5.0.4

Installed Dependencies:

  @capacitor/cli: 5.0.4
  @capacitor/core: 5.0.4
  @capacitor/android: 5.0.4
  @capacitor/ios: 5.0.4

[success] iOS looking great! 👌
[error] Missing <manifest package=""> attribute in app/src/main

### Before submitting

- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
Thank you for your detailed request. I will take a look as soon as possible.

**Comment by juanxodj** [comment]
I am having the same error

**Comment by ArtemSvetlakov** [comment]
I have the same error. No fix yet?

**Comment by robingenz** [comment]
Sorry, I am currently extremely busy. I will take a look as soon as possible. PRs are welcome.

**Comment by ArtemSvetlakov** [comment]
Thanks for the answer. This problem is only related to the quota limit:

Error Domain=FIRAuthErrorDomain Code=17052 "QUOTA_EXCEEDED : Exceeded quota." UserInfo={NSLocalizedDescription=QUOTA_EXCEEDED : Exceeded quota., FIRAuthErrorUserInfoNameKey=ERROR_QUOTA_EXCEEDED}

**Comment by bravao911** [comment]
> Thanks for the answer. This problem is only related to the quota limit:
> 
> Error Domain=FIRAuthErrorDomain Code=17052 "QUOTA_EXCEEDED : Exceeded quota." UserInfo={NSLocalizedDescription=QUOTA_EXCEEDED : Exceeded quota., FIRAuthErrorUserInfoNameKey=ERROR_QUOTA_EXCEEDED}

Hi, maybe you exceeded the quota. But for me no . Even if I try the next 24 hrs l have the same issue as i mentioned above.

**Comment by felipeclopes** [comment]
@robingenz it is happening to me, but only if I'm already logged in with a different method. 

Just to explain how I'm reproducing this:
1. Authenticate with Google
2. Subscribe to `FirebaseAuthentication.addListener('phoneCodeSent', (sms) => {})
3. Call `await FirebaseAuthentication.signInWithPhoneNumber({ phoneNumber });`

`phoneCodeSent` listener is invoked with no `verificationId`.

```
Capacitor:

   Capacitor CLI      : 5.0.5
   @capacitor/android : 5.0.5
   @capacitor/core    : 5.0.5
   @capacitor/ios     : 5.0.5
```
`"@capacitor-firebase/authentication": "^5.0.0",`

This same flow used to work on previous version and Cap 4.

**Comment by TruongHaiDang** [comment]
I encountered a similar issue even though I have set up APNs (.p8 file in Cloud Messaging tab). Please let me know how to resolve it if possible. Thank you very much.

**Comment by bravao911** [comment]
l have followed error into 

```
 private func verifyPhoneNumber(_ options: SignInWithPhoneNumberOptions) {
        PhoneAuthProvider.provider()
            .verifyPhoneNumber(options.getPhoneNumber(), uiDelegate: nil) { verificationID, error in               
                if let error = error {
                    print(error as Any)
                }
                self.pluginImplementation.handlePhoneCodeSent(verificationID ?? "")
            }
    }
```

l have error 

`Error Domain=FIRAuthErrorDomain Code=17006 "The given sign-in provider is disabled for this Firebase project. Enable it in the Firebase console, under the sign-in method tab of the Auth section." UserInfo={NSLocalizedDescription=The given sign-in provider is disabled for this Firebase project. Enable it in the Firebase console, under the sign-in method tab of the Auth section., FIRAuthErrorUserInfoNameKey=ERROR_OPERATION_NOT_ALLOWED}`

Phone provider already enabled ! .

**Comment by robingenz** [comment]
@bravao911 Is this issue still relevant? I can't access your reproduction link. I just tried it with a client's app and everything worked fine.

Apart from that you should add the listener (`addListener(...)`) BEFORE calling `signInWithPhoneNumber(...)`.
