### ISSUE TITLE
bug(app-check): does not work with custom provider on Android

### ISSUE THREAD

**Issue by CoooWeee** [capawesome-team/capacitor-firebase#385]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [X] App Check
- [ ] Authentication
- [ ] Crashlytics
- [ ] Cloud Messaging
- [ ] Performance
- [ ] Remote Config

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [X] Android
- [ ] iOS
- [ ] Web

### Current behavior

Token refresh via android play integrity not firing.

### Expected behavior

It is working fine as long as I use only debug tokens. Production build and trying to use play integrity do not even do a call to Google (no entry in logs).  It was working fine for with:

    "@capacitor-firebase/app-check": "^1.4.0",
    "@angular/fire": "^7.5.0"
    
It does not work with:

    "@capacitor-firebase/app-check": "^5.0.0",
    "@angular/fire": "^7.6.1",
    "@capacitor/android": "^5.0.4",
    "@capacitor/app": "^5.0.2",
    "@capacitor/core": "^5.0.4",

To me it looks like as initializeAppCheck is not using the CustomProvider anymore and so it does not even try to call "getToken" in the CustomProvider. Could also be an issue with firebase or @angular/fire. 
Is it working for anyone with the latest versions?

### Reproduction

N/A

### Steps to reproduce

1. Create ionic project with '@capacitor-firebase/app-check'
2. Add app-check:
````

import {
  provideAppCheck,
  initializeAppCheck,
  CustomProvider,
  AppCheckToken,
} from '@angular/fire/app-check';
import { FirebaseAppCheck } from '@capacitor-firebase/app-check';
import { getApp } from '@angular/fire/app';

@NgModule({
  declarations: [AppComponent],
  entryComponents: [],
  imports: [
provideAppCheck(
      () => {

        FirebaseAppCheck.initialize({
          debug:  !environment.production,
          isTokenAutoRefreshEnabled: true,
        })

        // Use CustomProvider to get native AppCheck token
        const provider = new CustomProvider({
          getToken: async (): Promise<AppCheckToken> => FirebaseAppCheck.getToken() as Promise<AppCheckToken>,
        });

        // Initialise AngularFire app check using provider
        return initializeAppCheck(getApp(), {
          provider,

          // Optional argument. If true, the SDK automatically refreshes App Check
          // tokens as needed.
          isTokenAutoRefreshEnabled: true,
        });

      },
    ),
    ]});
````

4. Create production build
5. make sure playstore, firebase, and everything related to app-check is set
6. deploy android app to play store
7. install from playstore

### Other information

Successful & failed '_getTokens_' I normally see in the google cloud log explorer. But there is nothing. 

### Capacitor doctor

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.0.4
  @capacitor/core: 5.0.4
  @capacitor/android: 5.0.4
  @capacitor/ios: 5.0.4

Installed Dependencies:

  @capacitor/cli: 5.0.4
  @capacitor/ios: 5.0.4
  @capacitor/android: 5.0.4
  @capacitor/core: 5.0.4

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Before submitting

- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
Since version `1.4.0` nothing has changed in the App Check plugin implementation. Only the Firebase SDKs and the Capacitor SDK have been updated. I'm leaving this issue open in case anyone else has the same problem. Maybe you can find the reason.

**Comment by robingenz** [comment]
It seems like nobody else has this problem. Since nothing has changed in the App Check plugin implementation since version `1.4.0`, I close this issue.
