### ISSUE TITLE
bug: capacitor 4 support ?

### ISSUE THREAD

**Issue by snimavat** [capawesome-team/capacitor-firebase#389]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [X] Authentication
- [ ] Crashlytics
- [ ] Cloud Messaging
- [ ] Performance
- [ ] Remote Config

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [X] Android
- [ ] iOS
- [ ] Web

### Current behavior

The main page of capawsome says "Capacitor 4 support" but i dont see instructions on firebase authentication plugin for how to use it with capacitor 4.

### Expected behavior

Docs for how to use the plugins / versions supported - for capacitor 4

### Reproduction

https://github.com

### Steps to reproduce

None

### Capacitor doctor

None

### Before submitting

- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
Thank you for your request. 
We always only support the latest Capacitor version, so currently Capacitor 5.
I just updated the README.
Please try to install an older version of the plugin (e.g. 1.4.0) to use it with Capacitor 4.
