### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by Aviho-M** [capawesome-team/capacitor-firebase#406]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [X] Authentication
- [ ] Crashlytics
- [ ] Cloud Messaging
- [ ] Performance
- [ ] Remote Config

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [X] Android
- [ ] iOS
- [ ] Web

### Current behavior

Plugin version:

@robingenz/capacitor-firebase-authentication 5.0.1

Platform(s):

Android

Current behavior:

Facebook sign in  calling signInWithFacebook() but the result is an 

Object {
callbackId: "114081066"
methodName: "signInWithFacebook"
options: {}
pluginId: "FirebaseAuthentication"
 };
without idToken 

Related code:

  const result = await FirebaseAuthentication.signInWithFacebook();
 console.log(result )
 works fine for ios and web

### Expected behavior

The Facebook registration window will open

### Reproduction

@robingenz/capacitor-firebase-authentication

### Other information
Additionally, when I execute FirebaseAuthentication.signOut(); after logging in with either Google or email and password, I encounter the following error: "Unhandled Promise rejection: The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first. ; Zone: <root> ; Task: Promise.then ; Value: Error: The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize()."
_No response_

### Capacitor doctor

 √ Creating capacitor.config.json in android\app\src\main\assets in 3.76ms
[capacitor] [info] Found 2 Cordova plugins for android:
[capacitor]        cordova-annotated-plugin-android@1.0.4
[capacitor]        cordova-plugin-purchases@4.2.3
[capacitor] [info] Inlining sourcemaps
[capacitor] √ copy android in 3.28s
[capacitor] √ Updating Android plugins in 15.21ms
[capacitor] [info] Found 8 Capacitor plugins for android:
[capacitor]        @capacitor-firebase/authentication@5.0.1
[capacitor]        @capacitor/app@4.1.1
[capacitor]        @capacitor/device@5.0.4
[capacitor]        @capacitor/haptics@4.1.0
[capacitor]        @capacitor/keyboard@4.1.1
[capacitor]        @capacitor/push-notifications@5.0.5
[capacitor]        @capacitor/splash-screen@4.2.0
[capacitor]        @capacitor/status-bar@4.1.1
[capacitor] [info] Found 2 Cordova plugins for android:
[capacitor]        cordova-annotated-plugin-android@1.0.4
[capacitor]        cordova-plugin-purchases@4.2.3
[capacitor] √ update android in 207.38ms
[capacitor] √ Running Gradle build in 11.85s

### Before submitting

- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
Thank you for your request.
Please provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) using [this template](https://github.com/capawesome-team/.capacitor-app) in a public GitHub repository so I can debug the issue.

**Comment by Aviho-M** [comment]
I fixed the problem by adding this line to the manifest
      <meta-data android:name="com.facebook.sdk.ClientToken" android:value=ClientToken />
