### ISSUE TITLE
bug: Error in push notifications iOS: sound, alert, badge

### ISSUE THREAD

**Issue by josuelmm** [capawesome-team/capacitor-firebase#407]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [ ] Authentication
- [ ] Crashlytics
- [X] Cloud Messaging
- [ ] Performance
- [ ] Remote Config

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [ ] Android
- [X] iOS
- [ ] Web

### Current behavior

In Capacitor 4, notifications in iOS were automatically applied to "strip", "globe" and "sound"

Now in 5, only "balloon", "strip" and "sound" are enabled, they do not appear in the notification segment of the app, nor in the notification settings of the application

CAPACITOR 4
![image](https://github.com/capawesome-team/capacitor-firebase/assets/12968781/3d0ae843-c177-4fc1-853e-fd60b7d49751)

CAPACITOR 5
![image](https://github.com/capawesome-team/capacitor-firebase/assets/12968781/9ec3f6c4-0c3c-4703-bbb7-98057c87ccd8)

### Expected behavior

Notifications in iOS were automatically applied to "strip", "globe" and "sound"

### Reproduction

https://github.com/robingenz/capacitor-firebase-plugin-demo

### Steps to reproduce

 Error with Capacitor 5
![image](https://github.com/capawesome-team/capacitor-firebase/assets/12968781/cc41c31e-2b8b-47d4-9b64-a1ec82dc1894)

### Capacitor doctor

Latest Dependencies:

@capacitor/cli: 5.2.1
@capacitor/core: 5.2.1
@capacitor/android: 5.2.1
@capacitor/ios: 5.2.1

Installed Dependencies:

@capacitor/core: 5.2.1
@capacitor/cli: 5.2.1
@capacitor/android: 5.2.1
@capacitor/ios: 5.2.1

### Before submitting

- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by josuelmm** [comment]
Any help @robingenz

**Comment by robingenz** [comment]
You just created the issue 2 hours ago. Give me some time to test it.

**Comment by josuelmm** [comment]
Log
⚡️  To Native ->  FirebaseMessaging requestPermissions 103063703
⚡️  [log] - FirebaseMessaging requestPermissions: {"receive":"denied"}

This after of accept notifications

```
let permStatus = await FirebaseMessaging.checkPermissions();
        console.log('FirebaseMessaging checkPermission:', permStatus);
        if (permStatus.receive !== 'granted') {
          permStatus = await FirebaseMessaging.requestPermissions();
          console.log('FirebaseMessaging requestPermissions:', permStatus);
        }
```

**Comment by robingenz** [comment]
I could not reproduce the issue with this [demo app](https://github.com/robingenz/capacitor-firebase-plugin-demo) on my iPhone 13 with iOS 16.5.1. Feel free to debug it yourself and create a PR.

![IMG_B9B8150399DF-1](https://github.com/capawesome-team/capacitor-firebase/assets/13857929/627bafa0-a414-4df1-8494-ab70af0c1a95)

**Comment by robingenz** [comment]
> Log ⚡️ To Native -> FirebaseMessaging requestPermissions 103063703 ⚡️ [log] - FirebaseMessaging requestPermissions: {"receive":"denied"}
> 
> This after of accept notifications
> 
> ```
> let permStatus = await FirebaseMessaging.checkPermissions();
>         console.log('FirebaseMessaging checkPermission:', permStatus);
>         if (permStatus.receive !== 'granted') {
>           permStatus = await FirebaseMessaging.requestPermissions();
>           console.log('FirebaseMessaging requestPermissions:', permStatus);
>         }
> ```

If the user denies the permission once, you can't ask for it again.

**Comment by josuelmm** [comment]
I'll upload a code and let you know here @robingenz

**Comment by josuelmm** [comment]
I got the error.. the problem is
@capawesome/capacitor-badge

It happens that this plugin requests permission from notifications... in apple the notification is divided into 4 types... (sound, badge, banner, list)
That plugin asks for the badge-only permission, before the notifications ask for all types of permissions.
