### ISSUE TITLE
feat: Cloud Firestore

### ISSUE THREAD

**Issue by EinfachHans** [capawesome-team/capacitor-firebase#41]
**Is your feature request related to a problem? Please describe:**

Support Firebase Firestore

**Describe the solution you'd like:**

Currently using this Cordova Plugin: https://github.com/dpa99c/cordova-plugin-firebasex

**Additional context:**

**Comment by alpfactory-alex** [comment]
@robingenz Do you already have a timeline in your mind for this? Just curious whether its worth it to use the Firebase JS SDK for now and wether we could easily switch then later. 

Great work you're doing!

**Comment by robingenz** [comment]
@alpfactory-alex Not yet. Migrating from the Firebase JS SDK to the plugin should be easy, as I'm trying to adopt the interfaces.

**Comment by AllTerrainDeveloper** [comment]
This could be a great plugin :) 💯(actually all of them, Database, Storage and FireStore at least)

Thank you for the awesome worrk, the Auth plugin works flawlesly.

**Comment by robingenz** [comment]
Would anyone be interested in testing a first development version of this plugin and giving some feedback afterwards?

**Comment by bojanbizjak** [comment]
Yes, but what we need most is background upload (files that are stored in the file system) to Storage and of course the standard Storage functionality.

**Comment by robingenz** [comment]
> Yes, but what we need most is background upload (files that are stored in the file system) to Storage and of course the standard Storage functionality.

That's what's planned next. Feel free to subscribe to #63.

**Comment by robingenz** [comment]
@bojanbizjak and anyone else who is interested: Here is the first dev version:

```
npm i @capacitor-firebase/firestore@5.1.0-dev.3050d98.1695803101
```

Here you can find the docs: https://capawesome.io/plugins/firebase/cloud-firestore/

I appreciate any feedback. There are two limitations currently, see:
- #438
- #439

**Comment by robingenz** [comment]
I just did the first tests and there seems to be big differences in performance. The Firebase Swift SDK is on average 4x faster when retrieving documents (tested on iOS 17.0.1). In my case I retrieve 20 documents. This takes an average of 95ms with the Firebase Swift SDK and an average of 455ms with the Firebase JS SDK.

**Comment by maccman** [comment]
We'd be very interested in testing this at https://reflect.app

**Comment by robingenz** [comment]
@maccman That would be great! Let me know if you need anything or if you are missing features.

@ocavue Thanks, i will take a look. 👍
