### ISSUE TITLE
bug: signInWithMicrosoft behavior on Android (and potentially iOS)

### ISSUE THREAD

**Issue by khang-nd** [capawesome-team/capacitor-firebase#411]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [X] Authentication
- [ ] Crashlytics
- [ ] Cloud Messaging
- [ ] Performance
- [ ] Remote Config

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [X] Android
- [ ] iOS
- [ ] Web

### Current behavior

It seems currently there is no way to login to the web layer with the `signInWithMicrosoft` approach as mentioned here: https://github.com/capawesome-team/capacitor-firebase/discussions/216 and https://github.com/capawesome-team/capacitor-firebase/discussions/165.

### Expected behavior

It would be lovely to have this feature supported and functional.

### Reproduction

N/A

### Steps to reproduce

Refer to the existing discussions: https://github.com/capawesome-team/capacitor-firebase/discussions/216 and https://github.com/capawesome-team/capacitor-firebase/discussions/165.

### Capacitor doctor

I'm still using **Capacitor v4.x** with **capacitor-firebase v1.4**

### Before submitting

- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
> As mentioned [here](https://cloud.google.com/identity-platform/docs/web/microsoft?hl=en), you can indeed not use the Microsoft sign-in with `signInWithCredential`.
> 
> > You can then use [Custom authentication](https://cloud.google.com/identity-platform/docs/web/custom) to exchange the Microsoft credential for a custom token.

As already mentioned, this is only possible with Custom Authentication. But you have to implement this yourself, as it is out-of-scope for the plugin. The long term goal is to offer all Firebase SDKs as Capacitor plugins, so you don't need the Firebase JS SDK on Android and iOS anymore. I therefore close this issue as non planned.
