### ISSUE TITLE
bug:  SignInwithApple returns displayName null for first connexion

### ISSUE THREAD

**Issue by ludonoel1** [capawesome-team/capacitor-firebase#417]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [X] Authentication
- [ ] Crashlytics
- [ ] Cloud Messaging
- [ ] Performance
- [ ] Remote Config

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [X] Android
- [X] iOS
- [X] Web

### Current behavior

This is my code : 
```
return FirebaseAuthentication.signInWithApple({ skipNativeAuth: true, scopes: ["name", "email"] }).then((result: SignInResult) => {
          const provider = new OAuthProvider('apple.com')
          const authCredential = provider.credential({
            idToken: result.credential.idToken,
            rawNonce: result.credential.nonce,
          });
         return signInWithCredential(getAuth(), authCredential)
.then((result: UserCredential) => {console.log(result.displayName}
```

Problem is that displayName null for new account...

I remove account in firebase console after every registration.

### Expected behavior

I'm expecting to get displayName of Apple account where I can find firstname and lastname.

### Reproduction

none

### Steps to reproduce

Just run this code

### Capacitor doctor

  @capacitor/cli: 5.2.2
  @capacitor/core: 5.2.2
  @capacitor/android: 5.2.2
  @capacitor/ios: 5.2.2

Installed Dependencies:

  @capacitor/cli: 5.0.5
  @capacitor/core: 5.0.5
  @capacitor/android: 5.0.5
  @capacitor/ios: 5.0.5

### Before submitting

- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
Apple provides the display name only once at signup.
Make sure you delete the Firebase user entry AND revoke the Apple ID access correctly.

**Comment by ludonoel1** [comment]
I did it ...

**Comment by robingenz** [comment]
Okay, I will take a closer look at it as soon as possible.

**Comment by ludonoel1** [comment]
Thanks. Do you have a working example maybe ? please, because it's urgent

**Comment by ludonoel1** [comment]
With version 5.1.0 it's working on Web but not for ios simulator

**Comment by robingenz** [comment]
It should work with the [demo app](https://github.com/robingenz/capacitor-firebase-authentication-demo). But the demo app does not use `skipNativeAuth`. So I don't know if it will help you.

There are currently a few open issues that I need to work through. If you want you can have your issue prioritized via a [one-time sponsorship](https://opencollective.com/capawesome/contribute/bug-report-43213). Otherwise PRs are also welcome.

**Comment by ludonoel1** [comment]
Finally I use this code: 

`let options: SignInWithAppleOptions = {
                clientId: 'cclientID', //
                redirectURI: 'handler', //
                scopes: 'email name',
              };
              
              return SignInWithApple.authorize(options)
                .then((result: SignInWithAppleResponse) => {
                  const provider = new OAuthProvider('apple.com')
                  const authCredential = provider.credential({
                    idToken: result.response.identityToken,
                  });
    const displayName = `${result.response.givenName} ${result.response.familyName}`
                 return signInWithCredential(getAuth(), authCredential)`


Issue is that signInWithCredential doesn't return displayName. DisplayName is still null

**Comment by robingenz** [comment]
I am glad you found a workaround.
Does this problem occur on all 3 platforms? Or on which platforms did you test it?

**Comment by robingenz** [comment]
Oh, so you mean on Android & iOS?

**Comment by ludonoel1** [comment]
Yes :)

**Comment by robingenz** [comment]
I just tested it and cannot reproduce your issue. When I delete the Firebase user entry and revoke the Apple ID access, the next time I sign in I get the display name.

![grafik](https://github.com/capawesome-team/capacitor-firebase/assets/13857929/b57835c7-2cce-4177-8360-b041f46a861d)

**Comment by robingenz** [comment]
@ludonoel1 This might help you: https://github.com/capawesome-team/capacitor-firebase/issues/481#issuecomment-1790244121
