### ISSUE TITLE
bug: capacitor PushNotificationsPlugin getPushNotificationsInstance returns null in Android OS

### ISSUE THREAD

**Issue by HosseinKurd** [capawesome-team/capacitor-firebase#424]
### Plugin(s)

- [ ] Analytics
- [X] App
- [ ] App Check
- [ ] Authentication
- [ ] Crashlytics
- [ ] Cloud Messaging
- [ ] Performance
- [ ] Remote Config

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [X] Android
- [ ] iOS
- [ ] Web

### Current behavior

capacitor `PushNotificationsPlugin.getPushNotificationsInstance()` returns null when app is closed in Android OS
Because of that notifications wouldn't be handled.

### Expected behavior

It should return an instance of `PushNotificationsPlugin`

### Reproduction

https://github.com/capawesome-team/.capacitor-app

### Steps to reproduce

`com/capacitorjs/plugins/pushnotifications/PushNotificationsPlugin.java`:

  public static void sendRemoteMessage(RemoteMessage remoteMessage) {
    PushNotificationsPlugin pushPlugin = PushNotificationsPlugin.getPushNotificationsInstance();// It it null
    if (pushPlugin != null) {
      pushPlugin.fireNotification(remoteMessage);
    } else {
      lastMessage = remoteMessage;
    }
  }

### Capacitor doctor

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.3.0
  @capacitor/core: 5.3.0
  @capacitor/android: 5.3.0
  @capacitor/ios: 5.3.0

Installed Dependencies:

  @capacitor/cli: 5.0.5
  @capacitor/android: 5.0.5
  @capacitor/core: 5.0.5
  @capacitor/ios: 5.0.5

[error] Xcode is not installed

### Before submitting

- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
I am closing this issue because it seems to have been created in the wrong repository. There is neither the `PushNotificationsPlugin` nor a method named `getPushNotificationsInstance` in this repository.
