### ISSUE TITLE
bug: signInWithMicrosoft doesn't work on Mobile

### ISSUE THREAD

**Issue by colinethrl** [capawesome-team/capacitor-firebase#425]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [X] Authentication
- [ ] Crashlytics
- [ ] Cloud Messaging
- [ ] Performance
- [ ] Remote Config

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [ ] Android
- [X] iOS
- [ ] Web

### Current behavior

I currently have an Ionic app where I try to connect with Microsoft with this bit of code:
```
const result = await FirebaseAuthentication.signInWithMicrosoft();
const provider = new OAuthProvider('microsoft.com');
const credential = provider.credential({
  idToken: result.credential?.idToken,
  accessToken: result.credential?.accessToken,
  rawNonce: result.credential?.nonce
 });

const auth = getAuth();
```
On the Web, it opens the pop up, then the credentials are populated with the tokens and then the auth.currentUser is populated. I can then enter my app and fetch db objects normally.
On the Mobile (iOS Emulator iPhone 14 Pro and real device IPhone 12 mini), it opens the pop up, then the credentials are populated with the tokens (the exact same ones as on the Web) **but the auth.currentUser stays null** which blocks access to the app obviously because the user is not authenticated according to Firebase.

I tried adding this line:
`await signInWithCredential(auth, credential);`
but it fails on Web and Mobile as it returns an error like this:
`400 error: : Invalid IdP response/credential`

### Expected behavior

FirebaseAuthentication.signInWithMicrosoft() should populate auth.currentUser on Mobile too.

### Reproduction

https://github.com/colinethrl/microsoft-issue

### Steps to reproduce

In an Ionic app:
html:
`  <ion-button (click)="connectWithMicrosoft()">Connect Microsoft</ion-button>
`
ts:
```
async connectWithMicrosoft() {
    const result = await FirebaseAuthentication.signInWithMicrosoft();
    const provider = new OAuthProvider('microsoft.com');
    const credential = provider.credential({
      idToken: result.credential?.idToken,
      accessToken: result.credential?.accessToken,
      rawNonce: result.credential?.nonce
    });

    const auth = getAuth();
    
    this.redirect();
}
```
package.json:
"@capacitor-firebase/authentication": "^5.1.0"

I have done the steps to download the ios/App/App/GoogleService-Info.plist and all the iOS configuration needed following the doc (swift package, AppDelegate.swift etc)

Everything works fine on both Web and iOS for Google with this code so it doesn't look like an issue of firebase auth config:
```
async connectWithGoogle() {
    const result = await FirebaseAuthentication.signInWithGoogle();

    const credential = GoogleAuthProvider.credential(result.credential?.idToken);
    const auth = getAuth();
    const signInResponse = await signInWithCredential(auth, credential);

    this.redirect();
  }
```

### Other information

The reproduction repository provided cannot be used right away because Firebase is not configured inside of it (I couldn't put my own Firebase credentials into a public repository). Thank you for your understanding.

### Capacitor doctor

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.3.0
  @capacitor/core: 5.3.0
  @capacitor/android: 5.3.0
  @capacitor/ios: 5.3.0

Installed Dependencies:

  @capacitor/cli: 5.2.2
  @capacitor/core: 5.2.2
  @capacitor/android: 5.2.2
  @capacitor/ios: 5.2.2

[success] iOS looking great! 👌
[error] Missing <manifest package=""> attribute in app/src/main

### Before submitting

- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
Hi @colinethrl,
please take a look at this comment: https://github.com/capawesome-team/capacitor-firebase/discussions/216#discussioncomment-3803525
In the long run, the goal is to support all Firebase SDKs so that the Firebase JS SDK on Android and iOS is no longer necessary.
