### ISSUE TITLE
feat: iOS Critical Messages

### ISSUE THREAD

**Issue by rickkock** [capawesome-team/capacitor-firebase#427]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [ ] Authentication
- [ ] Crashlytics
- [X] Cloud Messaging
- [ ] Performance
- [ ] Remote Config

### Current problem

Currently I I'm converting my app from Cordova to Capacitor and I would like to implement critical push notifications for iOS, witch I noticed this plugin is missing. Can this be implemented?

### Preferred solution

Implement .critical inside the options configuration and the requestPermission method

**Comment by robingenz** [comment]
Hi @rickkock, thank you for your request.
I will make sure this is included in the next version.

Ref: https://stackoverflow.com/a/68522623/16289814

**Comment by robingenz** [comment]
@rickkock Can you give it a try and let me know if everything works?

```
npm i @capacitor-firebase/messaging@5.1.0-dev.1bc48bb.1694614305
```

I don't have a Critical Alert Notifications Entitlement for testing.

**Comment by rickkock** [comment]
Just did a quick test, and I received 2 permission prompts for regular push messages and critical. Just how it supposed to be. So it seems everything works. Didn't send any messages yet but the permission handling works.

**Comment by robingenz** [comment]
@rickkock Thanks for testing!
