### ISSUE TITLE
feat(firestore): support batched writes

### ISSUE THREAD

**Issue by robingenz** [capawesome-team/capacitor-firebase#444]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [ ] Authentication
- [ ] Crashlytics
- [X] Cloud Firestore
- [ ] Cloud Messaging
- [ ] Performance
- [ ] Remote Config

### Current problem

Batched writes are currently not supported.

### Preferred solution

Support batched writes, see https://firebase.google.com/docs/firestore/manage-data/transactions#batched-writes.

**Comment by rosostolato** [comment]
Is this something that someone new to the project can help with?

**Comment by robingenz** [comment]
I'm afraid the implementation is a bit more complex and therefore not a good first issue.

**Comment by robingenz** [comment]
Would anyone be interested in testing this feature?
