### ISSUE TITLE
feat: Android: Remove isTokenAutoRefreshEnabled from initialize method of FirebaseAppCheck.java

### ISSUE THREAD

**Issue by DaveRicho** [capawesome-team/capacitor-firebase#480]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [X] App Check
- [ ] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [ ] Cloud Messaging
- [ ] Performance
- [ ] Remote Config

### Current problem

Hi @robingenz, 

You may already be on top of this (and perhaps I should attempt a pull request - but I'm still pretty new to this stuff and don't want to waste anyone's time), but I had some issues with App Check android (web and ios are perfect).

After thinking I had something wrong with my SHA256 keys (for days!), I think I found the issue. I read, re-read and then re-read this page another 20 times [https://firebase.google.com/docs/app-check/android/play-integrity-provider](https://firebase.google.com/docs/app-check/android/play-integrity-provider).

Finally I realised that (this might only apply for com.google.firebase:firebase-appcheck-playintegrity:17.1.1 and perhaps not for the current project's 17.0.1) that in the initializeApp step, that they look to have dropped **isTokenAutoRefreshEnabled**.

So that these mods to **FirebaseAppcheck.java** seem to resolve my problem (at least when I use 17.1.1): 

```
public void initialize(boolean debug, boolean isTokenAutoRefreshEnabled) {
        if (debug) {
            this.appCheckInstance.installAppCheckProviderFactory(DebugAppCheckProviderFactory.getInstance(), isTokenAutoRefreshEnabled);
        } else {
            this.appCheckInstance.installAppCheckProviderFactory(                    
//                    PlayIntegrityAppCheckProviderFactory.getInstance(),
//                    isTokenAutoRefreshEnabled
                      PlayIntegrityAppCheckProviderFactory.getInstance()
                );
        }
    }
```

### Preferred solution

Remove **isTokenAutoRefreshEnabled** from FirebaseAppCheck.java so the initialize method looks like:

```
public void initialize(boolean debug, boolean isTokenAutoRefreshEnabled) {
        if (debug) {
            this.appCheckInstance.installAppCheckProviderFactory(DebugAppCheckProviderFactory.getInstance(), isTokenAutoRefreshEnabled);
        } else {
            this.appCheckInstance.installAppCheckProviderFactory(
                    PlayIntegrityAppCheckProviderFactory.getInstance()
                );
        }
    }
```

### Additional context

Thanks so much for your hard work on this App you legend @robingenz and apologies if I have wasted anyone's time here.

**Comment by robingenz** [comment]
Thank you for your request!

> but I had some issues with App Check android (web and ios are perfect).

Unfortunately, that is not a sufficient description of your problem for me to be able to help you.

> Finally I realised that (this might only apply for com.google.firebase:firebase-appcheck-playintegrity:17.1.1 and perhaps not for the current project's 17.0.1) that in the initializeApp step, that they look to have dropped isTokenAutoRefreshEnabled.

I don't think so since this would be a breaking change in a minor/patch release. The method also still exists in the documentation: https://firebase.google.com/docs/reference/android/com/google/firebase/appcheck/FirebaseAppCheck#installAppCheckProviderFactory(com.google.firebase.appcheck.AppCheckProviderFactory,boolean)
For this reason i am closing this issue.

Feel free to update this issue if you find out anything new.

**Comment by DaveRicho** [comment]
Sorry @robingenz, I think I've got some other problem anyway with PlayIntegrityAppCheckProviderFactory.

I've had to resort going back to the deprecated 

```
this.appCheckInstance.installAppCheckProviderFactory(
                    SafetyNetAppCheckProviderFactory.getInstance()
            );
```

to get our production app working for now....
