### ISSUE TITLE
bug: Getting no such module FirebaseCore

### ISSUE THREAD

**Issue by mehtaparam** [capawesome-team/capacitor-firebase#483]
### Plugin(s)

- [X] Analytics
- [ ] App
- [ ] App Check
- [ ] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [ ] Cloud Messaging
- [ ] Performance
- [ ] Remote Config

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [ ] Android
- [X] iOS
- [ ] Web

### Current behavior

<img width="1051" alt="image" src="https://github.com/capawesome-team/capacitor-firebase/assets/16741514/d9dfd118-abd4-4849-8ddf-620c711e55a9">
Getting no such module FirebaseCore

### Expected behavior

I should be able to use firebase analytics in iOS

### Reproduction

Not able to share

### Steps to reproduce

Trying to create build for iOS

### Other information

Ionic:

   Ionic CLI                     : 7.1.1 (/Users/mehtaparam/.nvm/versions/node/v18.12.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.4.3
   @angular-devkit/build-angular : 16.2.5
   @angular-devkit/schematics    : 16.2.5
   @angular/cli                  : 16.2.5
   @ionic/angular-toolkit        : 10.0.0

Capacitor:

   Capacitor CLI      : 5.5.1
   @capacitor/android : 5.5.1
   @capacitor/core    : 5.5.1
   @capacitor/ios     : 5.5.1

Utility:

   cordova-res                          : 0.15.4
   native-run (update available: 2.0.0) : 1.7.3

System:

   NodeJS : v18.12.1 (/Users/mehtaparam/.nvm/versions/node/v18.12.1/bin/node)
   npm    : 8.19.2
   OS     : macOS Unknown

### Capacitor doctor

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1

Installed Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Before submitting

- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by Pathrom** [comment]
In my case the pods were not updated automatically, I simply followed the documentation by adding this line and it worked.

target 'App' do
  capacitor_pods
  pod 'CapacitorFirebaseAnalytics/Analytics', :path => '../../node_modules/@capacitor-firebase/analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
end


I also had to delete this other one:
   pod 'CapacitorFirebaseAnalytics', :path => '../../node_modules/@capacitor-firebase/analytics'

**Comment by gelinger777** [comment]
It happened to us too.  on Xcode 14
