### ISSUE TITLE
bug: Error: Not implemented on Android.

### ISSUE THREAD

**Issue by imuhammadnadeem** [capawesome-team/capacitor-firebase#484]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [ ] Authentication
- [x] Crashlytics
- [ ] Cloud Firestore
- [ ] Cloud Messaging
- [ ] Performance
- [ ] Remote Config

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [X] Android
- [ ] iOS
- [ ] Web

### Current behavior

When I'm calling this function
const result = await FirebaseCrashlytics.isEnabled();
it returns this.

Error: Uncaught (in promise): Error: Not implemented on Android.

### Expected behavior

It should work properly.

### Reproduction

https://github.com/imuhammadnadeem/LoyaltyProgram

### Steps to reproduce

The complete code is in the repo you just have to clone it and after cloning
1- Install node modules
2- Build for Android The complete

### Capacitor doctor

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1

[success] Android looking great! 👌

### Before submitting

- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
This is currently only available on iOS as documented here: https://capawesome.io/plugins/firebase/crashlytics/#isenabled

Therefore it is not a bug. Feel free to create a feature request. This should be easy to implement.
I'm not sure why it's currently only available on iOS.
