### ISSUE TITLE
bug: Appcheck Package is not correctly using the provider Device Check vs AppAttest For iOS  14+ devices.

### ISSUE THREAD

**Issue by balajitoverto** [capawesome-team/capacitor-firebase#490]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [X] App Check
- [ ] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [ ] Cloud Messaging
- [ ] Performance
- [ ] Remote Config

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [ ] Android
- [X] iOS
- [ ] Web

### Current behavior

{ "sub": "1:************06:ios:3b262cd82***********",
 "aud": [
    "projects/85********",   
    "projects/ABC"
   ], 
 "provider": "device_check_device_identification", 
 "iss": "https://firebaseappcheck.googleapis.com/*********", 
 "exp": 1695284564, 
 "iat": 1695280964, 
 "jti": "G6vqvRPv**********************60tRmR1***"
}

### Expected behavior

{
    "sub": "1:***********06:ios:1b3f479e7**************",
    "aud": [
      "projects/85*********",
      "projects/ABC"
    ],
    "provider": "device_check_app_attest",
    "iss": "https://firebaseappcheck.googleapis.com/***********",
    "exp": 1695293981,
    "iat": 1695290381,
    "jti": "EBdv4gM8***************************i1j1lMX***"
  }`

### Reproduction

https://github.com/capawesome-team/.capacitor-app

### Steps to reproduce

By logging the device 
Get bearer token response, inspect with JWT response you can see the response

### Other information

When we test it on IOS 14+ devices it' still uses the Device check instead of AppAttest.

### Capacitor doctor

Latest Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1

Installed Dependencies:

  @capacitor/cli: 5.2.2
  @capacitor/core: 5.2.2
  @capacitor/ios: 5.2.3
  @capacitor/android: 5.2.2

### Before submitting

- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by balajitoverto** [comment]
With your sample repository [,](https://github.com/capawesome-team/.capacitor-app.git) you should be able to reproduce the response by enabling Firebase in your project. When a user logs in, you can investigate the JWT response.
In one of our projects, we encountered an issue with DeviceCheck where we observed that the provider we received was 'device_check_device_identification.' However, in another project where DeviceCheck is functioning correctly, the provider appears as 'device_check_app_attest.' The project facing the DeviceCheck issue is using Angular version 13.4.0 and '@capacitor-firebase/app-check' version '^5.1.0.' As we delve into further investigation, we've noticed that the JWT response Below, we have attached the JWT response.
Expected behavior.
`{
    "sub": "1:***********06:ios:1b3f479e7**************",
    "aud": [
      "projects/85*********",
      "projects/ABC"
    ],
    "provider": "device_check_app_attest",
    "iss": "https://firebaseappcheck.googleapis.com/***********",
    "exp": 1695293981,
    "iat": 1695290381,
    "jti": "EBdv4gM8***************************i1j1lMX***"
  }``
  Current behavior
  `{ "sub": "1:************06:ios:3b262cd82***********",
 "aud": [
    "projects/85********",   
    "projects/ABC"
   ], 
 "provider": "device_check_device_identification", 
 "iss": "https://firebaseappcheck.googleapis.com/*********", 
 "exp": 1695284564, 
 "iat": 1695280964, 
 "jti": "G6vqvRPv**********************60tRmR1***"
}`
When testing on iOS 14 or later, the application continues to use DeviceCheck instead of AppAttest. It appears that the package code is not correctly applying the configuration to utilize the correct source
If you need additional details, please reach out to us

**Comment by robingenz** [comment]
> When testing on iOS 14 or later, the application continues to use DeviceCheck instead of AppAttest.

Unfortunately, I cannot reproduce this. Here you can find the place in the code where the provider is set: https://github.com/capawesome-team/capacitor-firebase/blob/8b4b50f61f11e692290ef6ca1dd2832f20547801/packages/app-check/ios/Plugin/CustomAppCheckProviderFactory.swift#L7

On iOS 14 and above, `AppAttestProvider` is selected.

Feel free to create a PR if you find the problem.

**Comment by TamilselvanMariyappan** [comment]
@robingenz  raised this PR - https://github.com/capawesome-team/capacitor-firebase/pull/525 We could make the CustomAppCheckProvider class as public. We noted when we call it in the appdelegate before firebase.configure it's works. Can you review and merge the PR?

**Comment by TamilselvanMariyappan** [comment]
@robingenz  when can we see this published in NPM to use in our app? Or if you think it may take sometime. Could you suggest how we can clone and build the package and use it from feature branch and use it temporarily. 
Thanks

**Comment by robingenz** [comment]
@TamilselvanMariyappan I just published a dev version you can use:

```
npm i @capacitor-firebase/app-check@5.3.0-dev.66c3007.1702913246
```

**Comment by TamilselvanMariyappan** [comment]
@robingenz  thanks for quick update

**Comment by TovertoApps** [comment]
@robingenz 
We are getting invalid token with short length of token example below,
X-Firebase-AppCheck: eyJlcn85ciI6Iigjyreds05fRVJST1IifQ==
npm i @capacitor-firebase/app-check@5.3.0-dev.66c3007.1702913246

When we use current public release package, we are able to get the full-length valid token but when we use the Dev published branch, we noted this issue.
If you have any insights, recommendations, or steps we can take to address this issue, we would greatly appreciate your assistance.

Thank you for your time and support.

**Comment by robingenz** [comment]
The class has only been made public. This should have no effect on the token. Feel free to debug it and create a PR if you find any bugs.
