### ISSUE TITLE
bug: Default Firebase app has not yet been configured error

### ISSUE THREAD

**Issue by smitedan** [capawesome-team/capacitor-firebase#492]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [X] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [ ] Cloud Messaging
- [ ] Performance
- [ ] Remote Config

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [ ] Android
- [X] iOS
- [ ] Web

### Current behavior

Hello,

i am getting the following error trying to load my application in IOS xcode

10.18.0 - [FirebaseCore][I-COR000003] The default Firebase app has not yet been configured. Add `FirebaseApp.configure()` to your application initialization. This can be done in in the App Delegate's application(_:didFinishLaunchingWithOptions:)` (or the `@main` struct's initializer in SwiftUI). Read more: https://goo.gl/ctyzm8.

the application works in both Web and Android and i am only using Firebase authentication. I have made sure to follow the steps

    1. Move your config file into the App root directory of your app: /ios/App/App/GoogleService-Info.plist.
    2. Now register the file in your XCode project by dragging it from /ios/App/App/GoogleService-Info.plist into the XCode file 
        explorer into the folder /App/App. If prompted, select to add the config file to all targets.***
        
Sorry i am a little bit new at this and have no idea why this error is occurring, any help would be appreciated 

### Expected behavior

Firebase to be configured on launch in xcode

### Reproduction

none available

### Steps to reproduce

use npx cap open ios,
Build in the project
application loads 
error appears with no crashing 

### Capacitor doctor

  @capacitor/cli: 5.5.1    
  @capacitor/core: 5.5.1   
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1    

Installed Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/ios: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1

### Before submitting

- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by smitedan** [comment]
hopefully this helps, https://github.com/smitedan/my-ts-app

**Comment by robingenz** [comment]
It seems like you did not set up the Firebase SDK correctly. The "/ios/App/App/GoogleService-Info.plist" is missing.

**Comment by smitedan** [comment]
sorry i had that in the .gitignore but its inside that folder

**Comment by robingenz** [comment]
Please commit all the files I need to reproduce the problem. This error occurs, among other things, if the `GoogleService-Info.plist` file has not been added correctly. Please make sure that you have followed this [setup guide](https://github.com/capawesome-team/capacitor-firebase/blob/main/docs/firebase-setup.md#ios) exactly. You are welcome to create a new Firebase project with the Spark plan.

**Comment by smitedan** [comment]
i missed the step of importing and configuring firebase inside the AppDelegate, thanks for the help
