### ISSUE TITLE
bug(authentication): `authStateChange` listener fires too early on the web

### ISSUE THREAD

**Issue by robingenz** [capawesome-team/capacitor-firebase#494]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [X] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [ ] Cloud Messaging
- [ ] Performance
- [ ] Remote Config

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [ ] Android
- [ ] iOS
- [X] Web

### Current behavior

As soon as an `authStateChange` listener is registered, the plugin should submit non-consumed events. The `retainUntilConsumed` parameter is used for this. Unfortunately, this only exists on Android and iOS and not on the web.

### Expected behavior

Same behavior on the web.

### Reproduction

-

### Steps to reproduce

-

### Capacitor doctor

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1

Installed Dependencies:

  @capacitor/cli: 5.0.0
  @capacitor/core: 5.0.0
  @capacitor/android: 5.0.0
  @capacitor/ios: 5.0.0

### Before submitting

- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
I am setting a bounty of **$50** on this.
The task is to create a PR in https://github.com/ionic-team/capacitor that closes https://github.com/ionic-team/capacitor/issues/7084 which is labeled as `type: bug`.

**Comment by sirajlekhak** [comment]
is it still open ? @robingenz

**Comment by robingenz** [comment]
@sirajlekhak Yes, this is still open.
