### ISSUE TITLE
bug(firestore): not returning maps correctly in android

### ISSUE THREAD

**Issue by Tsquared86** [capawesome-team/capacitor-firebase#497]
Hi I am using the capacitor firestore plugin and it works perfectly on iOS and the web, but on android it returns map objects with an "=" instead of a ":". when this happens the front end reads it as a string and can not iterate it on the frontend. How can I get past this?

This is what the console logs for the variable format:
'[{amount=5, name=Eggs, icon=}, {amount=2 slices, icon=, name=Cheese}, {amount=To Taste, icon=, name=Salt}, {amount=To Taste, name=Pepper , icon=}]'

This is the error:
Error: Cannot find a differ supporting object '[{amount=5, name=Eggs, icon=}, {amount=2 slices, icon=, name=Cheese}, {amount=To Taste, icon=, name=Salt}, {amount=To Taste, name=Pepper , icon=}]' of type 'string'. NgFor only supports binding to Iterables such as Arrays.

```ts
async getCollection(ref: string) {
    const { snapshots } = await FirebaseFirestore.getCollection({
      reference: ref,
    });
    return snapshots;
  };
```
  
  
```ts
  async getDocument(ref: string) {

    const { snapshot } = await FirebaseFirestore.getDocument({
      reference: ref
    });
    console.log(snapshot)
    return snapshot;

  };
```

**Comment by robingenz** [comment]
Thank you for your request! Unfortunately, I cannot reproduce your issue. It works for me on Android without any problems. Here you can find the official demo app: https://github.com/robingenz/capacitor-firebase-plugin-demo

![grafik](https://github.com/capawesome-team/capacitor-firebase/assets/13857929/d3bcc0b1-56a7-41cb-8b50-920c1ca563e7)
