### ISSUE TITLE
feat(remote-config): support realtime config updates

### ISSUE THREAD

**Issue by davideramoaxa** [capawesome-team/capacitor-firebase#499]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [ ] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [ ] Cloud Messaging
- [ ] Performance
- [X] Remote Config

### Current problem

It's currently not possible to register for realtime remote config changes

### Preferred solution

Implementation of Firebase remote config realtime API 

https://firebase.google.com/docs/remote-config/real-time

https://firebase.google.com/docs/remote-config/get-started?platform=android#add-real-time-listener

**Comment by robingenz** [comment]
Thank you! This feature is definitely missing.

**Comment by f1ght4fun** [comment]
+1 ... this is a deal-breaker feature to receive updates on config changes. 

Is there any timeframe when this feature might be added to plugin !?

**Comment by robingenz** [comment]
The Realtime API is quite new. You still receive updates on config changes but not yet in realtime. There is no ETA yet. PRs are welcome (please let me know beforehand). You can also prioritize this issue as sponsor.

**Comment by robingenz** [comment]
I am setting a [bounty](https://capawesome.io/contributing/bounties/) of **$50** on this issue.

The task is to add support for realtime config updates to the Firebase Remote Config plugin. The base branch to be used is [`feat/issue-499`](https://github.com/capawesome-team/capacitor-firebase/tree/feat/issue-499). This branch already contains the necessary type definitions (see #502). The implementation can be based on the [`addDocumentSnapshotListener`](https://github.com/capawesome-team/capacitor-firebase/blob/bc73b938afea985e780259d3499caf1836a35a69/packages/firestore/src/definitions.ts#L74) method of the Firebase Cloud Firestore plugin.
The changes must be fully tested.

Let me know if you have any questions.

**Comment by robingenz** [comment]
This is now available as dev version:

```
npm i @capacitor-firebase/remote-config@5.3.0-dev.8e93695.1702565523
```
