### ISSUE TITLE
"prompt-with-rationale" not showing on iOS

### ISSUE THREAD

**Issue by kjkortes** [capawesome-team/capacitor-firebase#504]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [ ] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [x] Cloud Messaging
- [ ] Performance
- [ ] Remote Config

### Version

5.2.0

### Platform(s)

- [ ] Android
- [x] iOS
- [ ] Web

### Current behavior

When the app ask permission for the first time and the user selected "don't allow" it gives the "prompt-with-rationale" response. However, I only see this happening on Android and not on iOS. 

### Expected behavior

should the "prompt-with-rationale" response show on iOS

### Reproduction

n/a

### Steps to reproduce

1. trigger prompt for notification permission

### Capacitor doctor

Latest Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1

Installed Dependencies:

  @capacitor/cli: 5.0.3
  @capacitor/ios: 5.0.3
  @capacitor/core: 5.0.3
  @capacitor/android: 5.0.3

[success] iOS looking great! 👌

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
`prompt-with-rationale` is not supported on iOS, see https://stackoverflow.com/a/29980902/6731412.

**Comment by kjkortes** [comment]
ok thanks
