### ISSUE TITLE
feat(storage): add file metadata during upload

### ISSUE THREAD

**Issue by robingenz** [capawesome-team/capacitor-firebase#506]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [ ] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [ ] Cloud Messaging
- [X] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Current problem

It is currently not possible to add file metadata during upload. It is only possible to call the `updateMetadata(...)` method after the upload.

### Preferred solution

It should be possible to add metadata during the upload of a file, see https://firebase.google.com/docs/storage/web/upload-files#add_file_metadata.
This should be supported on Android, iOS and Web. 

### Additional context

I am setting a [bounty](https://capawesome.io/contributing/bounties/) of **$50** on this issue.

The base branch to be used is [`feat/issue-506`](https://github.com/capawesome-team/capacitor-firebase/tree/feat/issue-506). This branch already contains the necessary type definitions (see #514).

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by triyam** [comment]
> I recommend to make the changes in the definitions.ts file first and let me review them before starting with the actual implementation.

As you have told, let me know should I ahead. 

> I am new open-source, you mistake correction or guidance will be a great help

**Comment by robingenz** [comment]
@triyam See https://github.com/capawesome-team/capacitor-firebase/issues/505#issuecomment-1844807268

The bounty is still available.
