### ISSUE TITLE
⚡ Capacitor 6

### ISSUE THREAD

**Issue by robingenz** [capawesome-team/capacitor-firebase#521]
According to [this blog post](https://ionic.io/blog/introducing-a-new-capacitor-release-cadence), Capacitor 6 will be the `latest` version from February 2024. From this point on, all plugins in this repository should also support Capacitor 6. Capacitor 5 will no longer be supported from this date.

**Comment by flozero** [comment]
the latest version of the packages are not supporting capacitor 6 yet. Is there any plan for it ?

**Comment by robingenz** [comment]
Capacitor 6 will be supported as soon as it's official released.

**Comment by flozero** [comment]
can we maybe hope to have a next version maybe ? so we can start working with it ? Thanks for your work
