### ISSUE TITLE
bug: Firestore fails an iOS app, while on the the web it works good

### ISSUE THREAD

**Issue by okletstryit** [capawesome-team/capacitor-firebase#523]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [ ] Authentication
- [ ] Crashlytics
- [X] Cloud Firestore
- [ ] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Version

5.3.0

### Platform(s)

- [ ] Android
- [x] iOS
- [ ] Web

### Current behavior

<img width="998" alt="image" src="https://github.com/capawesome-team/capacitor-firebase/assets/108156669/9b9e646f-3ef9-4df1-88a0-78dee6f54515">

Sometimes it fails to run and I see another issue. But in my main app, It fails as it is on the screenshot

#0	0x0000000106882610 in std::__1::shared_ptr<firebase::firestore::util::Executor>::shared_ptr[abi:v160006](std::__1::shared_ptr<firebase::firestore::util::Executor> const&) at /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.0.sdk/usr/include/c++/v1/__memory/shared_ptr.h:634

### Expected behavior

It works the same way as on the Web

### Reproduction

https://github.com/okletstryit/failing-ios

### Steps to reproduce

git clone https://github.com/okletstryit/failing-ios
cd failing-ios
npm install
npm run buid
npm run sync-ios
npm run start-xcode

press Play in xcode

### Capacitor doctor

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/ios: 5.6.0

[success] iOS looking great! 👌

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
Thanks for reporting the issue. Please also share your Xcode debug console output after the error occurred.

**Comment by okletstryit** [comment]
[Xcode debug.txt](https://github.com/capawesome-team/capacitor-firebase/files/13694285/Xcode.debug.txt)

Thank you for replying. Here is all the logs I have in Xcode

**Comment by okletstryit** [comment]
@robingenz  I would be grateful for advice on how to workaround this issue if you know the cause of it until you get it fixed on your side

**Comment by robingenz** [comment]
It seems like you did not set up Firebase correctly. The `GoogleService-Info.plist` file is missing.

**Comment by okletstryit** [comment]
@robingenz  It seems I did not add it to git, or something went wrong with xCode. I added it to my test repo now, the issue is still here

**Comment by robingenz** [comment]
You should not add Firebase packages to XCode manually (e.g. `Package.resolved`). This is all handled by the Capacitor plugin. I removed the packages and tested your reproduction example and could not find any problems:

```
⚡️  WebView loaded
⚡️  To Native ->  FirebaseFirestore getDocument 71085217
⚡️  To Native ->  SplashScreen hide 71085218
⚡️  TO JS undefined
⚡️  TO JS {"snapshot":{"path":"users\/2NkGwKiBHFV1K5kDg9fJOcig78u2\/lessons\/lesson_1","id":"lesson_1","data":{"b":2,"a":1}}}
```

**Comment by okletstryit** [comment]
@robingenz Sorry for the dumb question, this is my first capacitor project. Could you please explain what Firebase packages I should remove and from where?

**Comment by robingenz** [comment]
These are the necessary changes: https://github.com/robingenz/capawesome-team-capacitor-firebase-issue-523/commit/0cc5d28cd7875ff14b98f4f6614b0bdace5bd05d

**Comment by okletstryit** [comment]
@robingenz Thanks so much! It works! I added these "wrong" libraries after reading some of the tutorials. 

For those who maybe has the same issue, I removed all Firebase-specific packages from Xcode in App-General-Frameworks section.
