### ISSUE TITLE
bug(authentication): No user is signed in

### ISSUE THREAD

**Issue by selvaganes** [capawesome-team/capacitor-firebase#524]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [X] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [ ] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Version

5.3.0

### Platform(s)

- [ ] Android
- [X] iOS
- [ ] Web

### Current behavior

When doing signInWithYahoo this error shows:-
To Native ->  FirebaseAuthentication signInWithYahoo 48551500
[ FirebaseAuthentication ]  No user is signed in.
ERROR MESSAGE:  {"errorMessage":"No user is signed in.","message":"No user is signed in."}
⚡️  [error] - {"errorMessage":"No user is signed in.","message":"No user is signed in."}
⚡️  To Native ->  FirebaseAuthentication signInWithYahoo 48551501

### Expected behavior

Should SignIn as per 5.2.0

### Reproduction

Its based on your Example code

### Steps to reproduce

const signInWithYahoo = async () => {
  const result = await FirebaseAuthentication.signInWithYahoo();
  return result.user;
};

### Capacitor doctor

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0

Installed Dependencies:

  @capacitor/android: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/cli: 5.5.1
  @capacitor/ios: 5.5.1

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by arstrasser** [comment]
I am able to reproduce with oauth log in with Microsoft. 

Isolated the issue to `startSignInFlow()` and `startLinkFlow()` in the `/packages/authentication/ios/Plugin/Handlers/OAuthProviderHandler.swift` file where `handleSuccessfulSignIn` and `handleSuccessfulLink` are swapped.

Swapping these two calls to where they should go resolves the issue for signInWithMicrosoft (and I strongly suspect this would fix Yahoo as well).

**Comment by selvaganes** [comment]
Not really sure yet but I think this is a firebase bug. However on the Firebase SDK when I set setCustomParameters with prompt: 'select_account' it works fine. If prompt:'login' is used it fails. On capacitor-firebase it fails on everything.
