### ISSUE TITLE
bug: Collection Groups Don't Work

### ISSUE THREAD

**Issue by mooalot** [capawesome-team/capacitor-firebase#534]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [ ] Authentication
- [ ] Crashlytics
- [X] Cloud Firestore
- [ ] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Version

5.3.0

### Platform(s)

- [ ] Android
- [ ] iOS
- [X] Web

### Current behavior

Getting a collection group returns no data. 

### Expected behavior

It should return data.

### Reproduction

https://github.com/mooalot/cap-firestore

### Steps to reproduce

1. Add sub collection documents to firestore
2. Read sub collections as collection group
3. Nothing is returned

### Other information

I haven't tried IOS or Android yet. The example repo is a direct comparison of what firebase does vs what capacitor-firebase does.

### Capacitor doctor

Not Necessary

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
Thank you for reporting the issue.
I just published a dev version with a potential fix: 

```
npm i @capacitor-firebase/firestore@5.3.0-dev.244262.1704405695
```

It would be great if you could help me with testing.

**Comment by mooalot** [comment]
> Thank you for reporting the issue. I just published a dev version with a potential fix:
> 
> ```
> npm i @capacitor-firebase/firestore@5.3.0-dev.244262.1704405695
> ```
> 
> It would be great if you could help me with testing.

This seems to fix the issue. I will be writing relatively extensive tests. I will let you know if there are any more problems.

**Comment by robingenz** [comment]
Great, thank you for testing!
