### ISSUE TITLE
Google login is not working

### ISSUE THREAD

**Issue by TamilselvanMariyappan** [capawesome-team/capacitor-firebase#542]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [X] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [ ] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Version

5.3.0

### Platform(s)

- [ ] Android
- [X] iOS
- [ ] Web

### Current behavior

![Untitled](https://github.com/capawesome-team/capacitor-firebase/assets/115609208/96d18863-b9f2-450c-8050-70163793b9c1)

### Expected behavior

"Once clicked, the login is not working fine."

### Reproduction

https://github.com/TamilselvanMariyappan/capacitor-firebase-plugin-demo/tree/Offshore-Dev-Demo

### Steps to reproduce

https://github.com/TamilselvanMariyappan/capacitor-firebase-plugin-demo/tree/Offshore-Dev-Demo

  "@angular/fire": "17.0.0",
   "@capacitor-firebase/authentication": "5.3.0",
   "rxjs": "7.8.0",

### Capacitor doctor

ionic cap build ios

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
Please share more information. What exactly is not working?

**Comment by TamilselvanMariyappan** [comment]
In iOS, when attempting to log in to the Google account, only a loading message is displayed.
FYI: Our current branch is https://github.com/TamilselvanMariyappan/capacitor-firebase-plugin-demo/tree/Offshore-Dev-Demo.

![image](https://github.com/capawesome-team/capacitor-firebase/assets/115609208/6f7bfd8d-dcb7-4733-a7eb-f0112c69aef5)

**Comment by conradfr** [comment]
If you change computer you may need to generate new fingerprints for the Firebase project.

**Comment by SureshKumarToverto** [comment]
The functionality works as expected on Android; we have validated it with fingerprints for the Firebase project as well. However, on **iOS**, we still encounter issues when trying to log in using Google.

**Comment by robingenz** [comment]
@TamilselvanMariyappan You did not follow the installation instructions correctly. You need to add the `CapacitorFirebaseAuthentication/Google` pod to your `ios/app/Podfile` file, see: https://github.com/capawesome-team/capacitor-firebase/blob/main/packages/authentication/docs/setup-google.md#ios

**Comment by SureshKumarToverto** [comment]
Thanks, But we got an error
<img width="861" alt="Screenshot 2024-01-10 at 4 57 14 PM" src="https://github.com/capawesome-team/capacitor-firebase/assets/155732803/cd23fd7f-c954-49b6-90ec-ae75abeae43d">

**Error**
[capacitor] ✖ Updating iOS native dependencies with pod install - failed!
[capacitor] ✖ update ios - failed!
[capacitor] [error] Analyzing dependencies
[capacitor]         [!] CocoaPods could not find compatible versions for pod "GoogleSignIn":
[capacitor]         In snapshot (Podfile.lock):
[capacitor]         GoogleSignIn (= 6.2.4, ~> 6.2.4)
[capacitor]         
[capacitor]         In Podfile:
[capacitor]         CapacitorFirebaseAuthentication/Google (from `../../node_modules/@capacitor-firebase/authentication`) was resolved to 5.3.0, which depends on
[capacitor]         GoogleSignIn (= 7.0.0)
[capacitor]         
[capacitor]         CodetrixStudioCapacitorGoogleAuth (from `../../node_modules/@codetrix-studio/capacitor-google-auth`) was resolved to 0.0.1, which depends on
[capacitor]         GoogleSignIn (~> 6.2.4)
[capacitor]         
[capacitor]         
[capacitor]         You have either:
[capacitor]         * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
[capacitor]         * changed the constraints of dependency `GoogleSignIn` inside your development pod `CodetrixStudioCapacitorGoogleAuth`.
[capacitor]         You should run `pod update GoogleSignIn` to apply changes you've made.
[capacitor]         
[ERROR] An error occurred while running subprocess capacitor.
        capacitor sync ios exited with exit code 1.
        Re-running this command with the --verbose flag may provide more information.

**Comment by robingenz** [comment]
I cannot find the changes in your reproduction example.

**Comment by SureshKumarToverto** [comment]
Can you please check now, I commit the changes.

**Comment by SureshKumarToverto** [comment]
I have Firebase/Messaging and Firebase/Analytics in the Podfile, but I still encounter problems with IOS Google login. Could you please share a branch that works for both Google and Microsoft login on iOS? It would be more helpful for our current project. Thanks in advance.

**Comment by robingenz** [comment]
Just take a look at our Firebase Authentication demo app: https://github.com/robingenz/capacitor-firebase-authentication-demo

**Comment by DevEdward666** [comment]
followed this solution and worked for me
https://stackoverflow.com/questions/42197729/app-getting-crash-when-click-on-googlesignin-button-why
