### ISSUE TITLE
bug: push notification not working

### ISSUE THREAD

**Issue by imPrinceSingh** [capawesome-team/capacitor-firebase#544]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [ ] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [X] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Version

5.6.0

### Platform(s)

- [X] Android
- [ ] iOS
- [X] Web

### Current behavior

I have tried @capacitor/push-notifications and @capacitor-firebase/messaging plugins for push notification with vue3. When I import PushNotification or FirebaseMessaging in a file, console shows error like; 'Failed to fetch dynamically imported module' and 'Couldn't resolve component "default" '. I have also added google-services.json file for firebase.
`import { FirebaseMessaging, GetTokenOptions } from "@capacitor-firebase/messaging";
`
if we are not importing this plugin everything is working fine.

### Expected behavior

I want to use PushNotifications or FirebaseMessaging plugin in my project.

### Reproduction

https://github.com/Paganiniana/capawesome-bug-reproduction

### Steps to reproduce

build project
run on local and test web server
run on an android device

### Capacitor doctor

npm run

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
I cannot access your reproduction repository. Please make it public.
