### ISSUE TITLE
bug: isSupported should return false when private browsing

### ISSUE THREAD

**Issue by khamaileon** [capawesome-team/capacitor-firebase#553]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [ ] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [X] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Version

5.4.0

### Platform(s)

- [ ] Android
- [ ] iOS
- [X] Web

### Current behavior

isSupported returns true when private browsing. isSupported from @firebase/messaging is returning false (correct behavior).

### Expected behavior

Should return false.

### Reproduction

No need

### Steps to reproduce

No need

### Capacitor doctor

No need

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
I'm not sure what you mean. `@capacitor-firebase/messaging` is using `isSupported(...)` from `@firebase/messaging`, see https://github.com/capawesome-team/capacitor-firebase/blob/9fb781f734a3923a26729aa413c49917852d5af6/packages/messaging/src/web.ts#L66.

**Comment by khamaileon** [comment]
Oh, I didn't pay enough attention. The response signature is not the same.
messaging.isSupported -> false
FirebaseMessaging.isSupported -> Object { isSupported: false }

And boolean of a object is true...

@robingenz thanks for the quick reply though :pray:
