### ISSUE TITLE
[FEATURE]: Add required `Privacy Manifest` file for iOS

### ISSUE THREAD

**Issue by edshkliaruk** [capawesome-team/capacitor-firebase#563]
### Plugin(s)

- [X] Analytics
- [ ] App
- [ ] App Check
- [X] Authentication
- [X] Crashlytics
- [X] Cloud Firestore
- [X] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [X] Remote Config

### Current problem

**Description**

Starting with Spring 2024 Apple requires third-party SDKs to add a Privacy Manifest file (similar to the privacy nutrition labels in the store). Apple specifically lists Capacitor as one of the SDKs that must include this manifest otherwise any App that includes it is not allowed to release an update (or new app) to the store.

https://developer.apple.com/support/third-party-SDK-requirements/

**Platform(s)**

iOS

**Additional Context**
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests
https://developer.apple.com/videos/play/wwdc2023/10060/

### Preferred solution

Need to add the Privacy Manifest wherever it is specified in the requirements.
The full list: https://developer.apple.com/support/third-party-SDK-requirements/

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by robingenz** [comment]
The privacy manifest will be provided by the Firebase iOS SDK, see https://github.com/firebase/firebase-ios-sdk/issues/11490#issuecomment-1755956915.
For this reason, i am closing this issue.
