### ISSUE TITLE
feat: react hooks?

### ISSUE THREAD

**Issue by jonathan-chin** [capawesome-team/capacitor-firebase#566]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [X] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [ ] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Current problem

I'm trying to write a few programs that use react, reactfire, capacitor, and this plugin. however, it seems that this plugin is based heavily on Promises, which aren't fully supported in react functional components. with react's suspense, we can achieve a functionality similar to async / await with hooks; we can wait until the hook completes and instead render a different component.

I can use promises in React with a workaround but it would be far better if there were react hooks. is this possible? I'm also happy to develop and `PR` some code but would need some guidance first.

### Preferred solution

It would be great to have a similar interface as reactfire's implementation. for example:
```
import {useUser} from 'reactfire';
[...]
const {user} = useUser();
```

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by robingenz** [comment]
> however, it seems that this plugin is based heavily on Promises

Yes, this is how Capacitor plugins work. Unfortunately, React hooks are not in the scope of this plugin. For one thing, I have no experience with React myself. Secondly, the maintenance of all plugins is already very time-consuming. Adding framework-specific code to the plugins would not be maintainable for me. For this reason, I am currently not planning to add any support.
