### ISSUE TITLE
feat(authentication): add `fetchSignInMethodsForEmail(...)` method

### ISSUE THREAD

**Issue by DontGiveAFck** [capawesome-team/capacitor-firebase#592]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [X] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [ ] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Current problem

On `account-exists-with-different-credential` error code user should be forced to use sign in method that was used previously, but when this error thrown there is no way to detect available sign in methods.

### Preferred solution

When `account-exists-with-different-credential` happens, error object should also contain `availableProviders` property (or `email` property and `fetchSignInMethodsForEmail` method should be implemented in plugin).

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by robingenz** [comment]
The [`fetchSignInMethodsForEmail`](https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseAuth#fetchSignInMethodsForEmail(java.lang.String)) method seems to be deprecated on the native platforms, see [Firebase docs](https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseAuth#fetchSignInMethodsForEmail(java.lang.String)).

Can you share a link to the docs regarding the `availableProviders` property?

**Comment by DontGiveAFck** [comment]
@robingenz 

`availableProviders` prop doesn't exists, I just wrote it as an example of another prop that might exist. (Looks like that it doesn't)

Possible solution - `signInWithCredentials` method throws `FirebaseAuthUserCollisionException` exception that contains `email` field and it can be used with firebase js sdk at least to handle this error somehow. Because now we forced to ask user to type email manually and check available providers that sounds like an issue. 

[Firebase docs](https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseAuth#signInWithCredential(com.google.firebase.auth.AuthCredential))

**Comment by DontGiveAFck** [comment]
@robingenz 

Regarding [fetchSignInMethodsForEmail](https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseAuth#fetchSignInMethodsForEmail(java.lang.String)) - yes, it's deprecated but it would be nice to have it if we will know user's email from solution above, so firebase js sdk will be not needed and issue will be fixed.

**Comment by robingenz** [comment]
Please give this dev build a try and let me know if everything works as expected:

```
npm i @capacitor-firebase/authentication@5.4.1-dev.e2f5589.1711099069
```

**Comment by DontGiveAFck** [comment]
@robingenz 
I checked this build:
1. There is still no user email returned from login error. I mentioned possible fix in [this comment](https://github.com/capawesome-team/capacitor-firebase/issues/592#issuecomment-2014061368)
2. `fetchSignInMethodsForEmail` works fine on ios, but on android there is an issue (screenshot attached) 
<img width="448" alt="Screenshot 2024-03-22 at 13 54 36" src="https://github.com/capawesome-team/capacitor-firebase/assets/24360535/d5971a96-0c83-488b-9afb-f7af003d2255">

**Comment by robingenz** [comment]
1. Yes, this PR only covers the `fetchSignInMethodsForEmail` method for now. Please create a separate issue for the `FirebaseAuthUserCollisionException`. I'm concerned that this will be a bit more difficult to implement, as I can only give Capacitor an error code when throwing an error, but no custom properties.
2. Thanks, I will fix it for Android.
