### ISSUE TITLE
feat: upgrade Firebase SDK version to have Privacy Manifest

### ISSUE THREAD

**Issue by edshkliaruk** [capawesome-team/capacitor-firebase#599]
### Plugin(s)

- [X] Analytics
- [ ] App
- [ ] App Check
- [X] Authentication
- [X] Crashlytics
- [ ] Cloud Firestore
- [ ] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [X] Remote Config

### Current problem

The latest version of the Firebase iOS SDK is 10.23.0.
https://github.com/firebase/firebase-ios-sdk/releases

This version includes the presence of the Privacy Manifest file that Apple requires to have since March 1st of this year.
It would be great to update the Firebase SDK version for this library.

### Preferred solution

The best option would be to update the Firebase SDK to the latest version.

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by Paso** [comment]
Will this be added to the v5 releases? It has prevented us from building our iOS app for a couple of weeks.

**Comment by robingenz** [comment]
This issue will be resolved in v6.0.0, see milestone.

**Comment by robingenz** [comment]
Closed by #612
