### ISSUE TITLE
[Analytics] Need to upgrade Firebase iOS SDK to 10.24.0 in @capacitor-firebase/analytics version 1.4.*

### ISSUE THREAD

**Issue by kientrant1** [capawesome-team/capacitor-firebase#623]
I'm receiving this notification
![image](https://github.com/capawesome-team/capacitor-firebase/assets/7844830/151a6493-45e7-4116-bc7b-ddc19d603219)

And as I see that this upgrading has been released with @capacitor-firebase/analytics version 6.0.0 (https://github.com/capawesome-team/capacitor-firebase/pull/612/files).

However, currently, I'm using **capacitor version 4** so I only use @capacitor-firebase/analytics version **1.4.0**.  Can we adapt/upgrade Firebase iOS SDK for this analytics version as well? Many thanks!

**Comment by robingenz** [comment]
We only provide updates for the latest Capacitor version. Feel free to [patch the plugin](https://capawesome.io/blog/how-to-patch-a-capacitor-plugin/).
