### ISSUE TITLE
feat(firestore): add addCollectionGroupSnapshotListener

### ISSUE THREAD

**Issue by svrznjak** [capawesome-team/capacitor-firebase#624]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [ ] Authentication
- [ ] Crashlytics
- [X] Cloud Firestore
- [ ] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Current problem

I am not sure but I think there is a very important feature missing. What I am trying to do is addCollectionSnapshotListener on collectionGroup query.
Such a thing can be done with javascript firebase library like this:
`const resources = query(collectionGroup(getFirestore(), 'resources'));`
`onSnapshot(resources, (querySnapshot) => {`
`  querySnapshot.forEach((doc) => {`
`    console.log(doc.data());`
`  });`
`});`

### Preferred solution

Since there already are [getCollection](https://github.com/capawesome-team/capacitor-firebase/tree/main/packages/firestore#getcollection), [addCollectionSnapshotListener](https://github.com/capawesome-team/capacitor-firebase/tree/main/packages/firestore#adddocumentsnapshotlistener) and [getCollectionGroup](https://github.com/capawesome-team/capacitor-firebase/tree/main/packages/firestore#getcollectiongroup) functions in API, I would suggest addCollectionGroupSnapshotListener function is added.

I made a quick glance at [addCollectionSnapshotListener web code](https://github.com/capawesome-team/capacitor-firebase/blob/792c4d15bc6f1a57ffa41d6eaa5d2436f56f9fb3/packages/firestore/src/web.ts#L204) and I think whole function can be copied and only change that is needed is on [line 212](https://github.com/capawesome-team/capacitor-firebase/blob/792c4d15bc6f1a57ffa41d6eaa5d2436f56f9fb3/packages/firestore/src/web.ts#L212) where `'collecion'` should be changed to `'collectionGroup'`.

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [ ] I have attached links to possibly related issues and discussions.

**Comment by robingenz** [comment]
Thank you for your request. Would you be willing to create a PR?

**Comment by svrznjak** [comment]
Time files... Well, I am not familiar with capacitor plugins, but I can give it a try.

**Comment by robingenz** [comment]
Let me know if you have any questions. I am currently working on other issues, so it will take some time until I get to this issue. You can also sponsor the issue if you want me to prioritize it.
