### ISSUE TITLE
feat: Cloud Storage for Firebase

### ISSUE THREAD

**Issue by Sampath-Lokuge** [capawesome-team/capacitor-firebase#63]
Hi,

Any reason for not having `Cloud Storage for Firebase` on this plugin? Thanks!

`Doc:` https://firebase.google.com/docs/storage

**Comment by robingenz** [comment]
Hi @Sampath-Lokuge,
I haven't had time to implement it yet. But this plugin is definitely in planning.
So the reason is lack of time.

**Comment by tlebeitsuk** [comment]
+1

**Comment by bojanbizjak** [comment]
+1

**Comment by bojanbizjak** [comment]
Is there a timeline for when this functionality might be available?

**Comment by robingenz** [comment]
Not yet. ETA is this year.

**Comment by prudradeep** [comment]
+1

**Comment by robingenz** [comment]
The first version is now available as dev version: 

```
npm i @capacitor-firebase/storage@5.1.0-dev.bf4bd39.1697375834
```

Here you can find the documentation: https://github.com/capawesome-team/capacitor-firebase/blob/feat/storage/packages/storage/README.md

**Comment by bojanbizjak** [comment]
The link to the documentation is not working

**Comment by robingenz** [comment]
> The link to the documentation is not working

It just doesn't work for me in the GitHub mobile app. I can open the link in Chrome without any problems.

**Comment by bojanbizjak** [comment]
It's true. It works in Chrome.
