### ISSUE TITLE
feat: AppCheck Debug provider in Simulators

### ISSUE THREAD

**Issue by jjgriff93** [capawesome-team/capacitor-firebase#630]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [X] App Check
- [ ] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [ ] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Current problem

Currently this package does not work when running the Capacitor code from an iOS simulator, unless the debug flag is set when calling `FirebaseAppCheck.initialize()`. This is because simulators only support running with the AppCheckDebugProvider and will fail any real device checks.

### Preferred solution

As per the [Firebase docs](https://firebase.google.com/codelabs/app-attest#3), the following code could be implemented:
```swift
class MyAppCheckProviderFactory: NSObject, AppCheckProviderFactory {
  func createProvider(with app: FirebaseApp) -> AppCheckProvider? {
    #if targetEnvironment(simulator)
      // App Attest is not available on simulators.
      // Use a debug provider.
      return AppCheckDebugProvider(app: app)
    #else
      // Use App Attest provider on real devices.
      return AppAttestProvider(app: app)
    #endif
  }
}
```

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by robingenz** [comment]
You can select the debug provider using the [initialize](https://capawesome.io/plugins/firebase/app-check/#initialize) method.
