### ISSUE TITLE
feat: Add Firebase Functions plugin

### ISSUE THREAD

**Issue by jjgriff93** [capawesome-team/capacitor-firebase#640]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [ ] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [ ] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Current problem

Would love to be able to use Firebase entirely natively on my Capacitor app, and the only missing piece from this great repo is Functions support!

### Preferred solution

A new plugin for Firebase Functions that covers the key client-side methods across native and web. This would include:
- Web SDK: https://firebase.google.com/docs/reference/js/functions
- iOS SDK: https://firebase.google.com/docs/reference/swift/firebasefunctions/api/reference/Classes
- Android SDK: https://firebase.google.com/docs/reference/android/com/google/firebase/functions/package-summary

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by robingenz** [comment]
@jjgriff93 Would you be willing to test a dev version?

**Comment by jjgriff93** [comment]
@robingenz absolutely! And happy to contribute if helpful

**Comment by robingenz** [comment]
@jjgriff93 That would be great because I am currently unable to deploy a cloud function. 😅 I tried it for several hours now with different `firebase-tools` versions.

```
Error: Cloud Runtime Config is currently experiencing issues, which is preventing your functions from being deployed. Please wait a few minutes and then try to deploy your functions again.
Run `firebase deploy --except functions` if you want to continue deploying the rest of your project.
```

I've just published a dev version for testing:

```
npm i @capacitor-firebase/functions@6.0.0-dev.b96fa6c.1718781196
```

If you discover any bugs, it would be great if you could create a PR against [`feat/issue-640`](https://github.com/capawesome-team/capacitor-firebase/tree/feat/issue-640). Let me know if you have any questions.

**Comment by robingenz** [comment]
@jjgriff93 Did you had a chance to test the plugin?

**Comment by robingenz** [comment]
You're welcome!
