### ISSUE TITLE
setConsent for iOS and Android, too

### ISSUE THREAD

**Issue by gasci** [capawesome-team/capacitor-firebase#641]
### Plugin(s)

- [X] Analytics
- [ ] App
- [ ] App Check
- [ ] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [ ] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Current problem

Is the `setConsent`method available only for web?
https://support.google.com/google-ads/answer/10000067?hl=en

### Preferred solution

It would be great if we could implement the `setConsent` for iOS and Android.
https://support.google.com/google-ads/answer/10000067?hl=en

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by robingenz** [comment]
This method is already available on Android and iOS. Please note, that the latest version has a bug which is fixed in #635.

**Comment by gasci** [comment]
Thank you for the quick answer. What version should I use to be able to use this method with iOS and Android, then? Should wait for a new version 6.x?

**Comment by gasci** [comment]
Thank you.

**Comment by AE1NS** [comment]
@robingenz could you publish another dev build in favor of the recent ios fix regarding the setConsent method?

**Comment by robingenz** [comment]
@AE1NS 

```bash
npm i @capacitor-firebase/analytics@6.0.0-dev.5ab166a.1720001083
```

**Comment by gasci** [comment]
Is it possible to set multiple consents at once? @robingenz

**Comment by robingenz** [comment]
@gasci No, this is not yet possible.

**Comment by gasci** [comment]
When I try to put 6 types of consent into a for loop multiple await statements crash the app unfortunately.

**Comment by robingenz** [comment]
@gasci Please create a bug report and provide all the information you have (logs, etc.).

**Comment by gasci** [comment]
This seems to be working, though:

```
if (isPlatform(["web", "android", "ios"])) {
    const consent = await Preferences.get({ key: 'cookieConsent' });

    await FirebaseAnalytics.setConsent({
      type: ConsentType.AdPersonalization,
      status: consent.value === 'authorized' ? ConsentStatus.Granted : ConsentStatus.Denied
    });

    await FirebaseAnalytics.setConsent({
      type: ConsentType.PersonalizationStorage,
      status: consent.value === 'authorized' ? ConsentStatus.Granted : ConsentStatus.Denied
    });

    await FirebaseAnalytics.setConsent({
      type: ConsentType.AdUserData,
      status: consent.value === 'authorized' ? ConsentStatus.Granted : ConsentStatus.Denied
    });

    await FirebaseAnalytics.setConsent({
      type: ConsentType.AdStorage,
      status: consent.value === 'authorized' ? ConsentStatus.Granted : ConsentStatus.Denied
    });

    await FirebaseAnalytics.setConsent({
      type: ConsentType.AnalyticsStorage,
      status: consent.value === 'authorized' ? ConsentStatus.Granted : ConsentStatus.Denied
    });
  }
```

**Comment by gasci** [comment]
Done:
https://github.com/capawesome-team/capacitor-firebase/issues/671
