### ISSUE TITLE
feat: passing state in email actions

### ISSUE THREAD

**Issue by mamillastre** [capawesome-team/capacitor-firebase#656]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [X] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [ ] Cloud Functions
- [ ] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Current problem

`sendEmailVerification()` & `sendPasswordResetEmail()` do not support to pass the action code settings.
`sendSignInLinkToEmail()` already support these settings.

### Preferred solution

These settings provide the user the ability to go back to the app after the action is completed.

Firebase documentation:
- Web: https://firebase.google.com/docs/auth/web/passing-state-in-email-actions
- Android: https://firebase.google.com/docs/auth/android/passing-state-in-email-actions
- iOS: https://firebase.google.com/docs/auth/ios/passing-state-in-email-actions

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by robingenz** [comment]
@mamillastre Thank you for your request. I've just created a PR for this. Would you be willing to test the dev version?

```
npm i @capacitor-firebase/authentication@6.0.0-dev.f54d9c3.1719494206
```

**Comment by mamillastre** [comment]
Sure, I will test that shortly.
Thanks for the PR.
