### ISSUE TITLE
feat: add the region configuration for Cloud Functions

### ISSUE THREAD

**Issue by mamillastre** [capawesome-team/capacitor-firebase#659]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [ ] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [X] Cloud Functions
- [ ] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Current problem

The default region is "us-central1" so if we use an another region, the callByName() method will fail.

### Preferred solution

We need a way to change the cloud functions' region. (a callByName() method option or a global configuration ?)

### Alternative options

We have a workaround for now by using the callByUrl() method.

```ts
const projectId = 'my-project-id';
const region = 'my-region-id';

public async callByName(options: CallByNameOptions): Promise<CallResult> {
    return FirebaseFunctions.callByUrl({
      ...options,
      url: isUsingEmulator ?
        `http://${functionsEmulatorHost}:${functionsEmulatorPort}/${projectId}/${region}/${options.name}` :
        `https://${region}-${projectId}.cloudfunctions.net/${options.name}`
    });
  }
```

### Additional context

Firebase docs: https://firebase.google.com/docs/functions/locations#client-side_location_selection_for_callable_functions

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by robingenz** [comment]
@mamillastre I've just created a PR. Would you be willing to test the dev build?

```
npm i @capacitor-firebase/functions@6.0.0-dev.59ed099.1719590033
```

**Comment by robingenz** [comment]
@mamillastre Have you had a chance to test this?

**Comment by mamillastre** [comment]
I just tested it and it works just as expected on all platforms.
Thanks for the PR.

**Comment by robingenz** [comment]
Thank you for testing.

**Comment by kbala-ami** [comment]
@robingenz Yes, we need this feature to support CloudFunction 2ndGen. Good if you push as early as posible.

Also, we need to support to connect given database id as well.

Thanks

**Comment by robingenz** [comment]
@kbala-ami Feel free to create a feature request.
