### ISSUE TITLE
feat: cloud functions generic types

### ISSUE THREAD

**Issue by mamillastre** [capawesome-team/capacitor-firebase#663]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [ ] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [X] Cloud Functions
- [ ] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Current problem

In the plugin, the request data and the response data are typed as any.

### Preferred solution

Like the JS SDK, we can add the generic type: `<RequestData = unknown, ResponseData = unknown>`

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by robingenz** [comment]
So you just want to replace `any` with `unkown` or what do you mean by`RequestData`/`ResponseData`?

```diff
export interface CallOptions {
  /**
   * The data to pass to the callable function.
   *
   * @since 6.1.0
   */
  data?: unknown;
}
```

**Comment by mamillastre** [comment]
No a generic type like:
```
export interface CallOptions<T = unknow> {
  data?: T;
}
```

I currently make the dev, I will create the PR shortly.

**Comment by robingenz** [comment]
Alright!
