### ISSUE TITLE
feat(storage): get custom metadata

### ISSUE THREAD

**Issue by mamillastre** [capawesome-team/capacitor-firebase#664]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [ ] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [ ] Cloud Functions
- [ ] Cloud Messaging
- [X] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Current problem

We can not get the custom metadata of a Cloud Storage file.

### Preferred solution

We can add the capability to get them.
`getMetadata()` should return the "customMetadata" attribute.

### Additional context

Web: https://firebase.google.com/docs/storage/web/file-metadata#custom_metadata
Android: https://firebase.google.com/docs/storage/android/file-metadata#custom_metadata
iOS: https://firebase.google.com/docs/storage/ios/file-metadata#custom_metadata

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by robingenz** [comment]
The plugin already provides the [`getMetadata(...)`](https://capawesome.io/plugins/firebase/cloud-storage/#getmetadata) and [`updateMetadata(...)`](https://capawesome.io/plugins/firebase/cloud-storage/#updatemetadata) methods. What else is missing?

**Comment by mamillastre** [comment]
Sorry, updateMetadata() already support the customMetadata. I didn't see that.
But "getMetadata()" does not return this value.

**Comment by robingenz** [comment]
Would you be willing to create a PR?

**Comment by mamillastre** [comment]
Yes, I will create a PR 👍
