### ISSUE TITLE
feat: setMinimumFetchInterval for iOS and Android

### ISSUE THREAD

**Issue by sagaraya** [capawesome-team/capacitor-firebase#687]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [ ] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [ ] Cloud Functions
- [ ] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [X] Remote Config

### Current problem

In the RemoteConfig package, setMinimumFetchInterval is currently only available for web. Therefore, a parameter must be passed to fetchConfig for iOS and Android.

This complicates the code, as fetchAndActivate is not available and a split occurs between the web version and iOS/Android.

### Preferred solution

I would like to use setMinimumFetchInterval on iOS and Android, it is supported on the Firebase side.

* iOS: https://firebase.google.com/docs/reference/swift/firebaseremoteconfig/api/reference/Classes/RemoteConfigSettings?_gl=1*ptpwho*_up*MQ..*_ga*MTI0MDI0NTY2NS4xNzIyMzA0OTk3*_ga_CW55HF8NVT*MTcyMjMwNDk5Ny4xLjAuMTcyMjMwNTA3MC4wLjAuMA..
* Android: https://firebase.google.com/docs/reference/android/com/google/firebase/remoteconfig/FirebaseRemoteConfigSettings.Builder?_gl=1*fqm33u*_up*MQ..*_ga*MTE4MDA5Njg5OS4xNzIyMzA2MTg3*_ga_CW55HF8NVT*MTcyMjMwNjE4Ny4xLjAuMTcyMjMwNjE5NC4wLjAuMA..#setMinimumFetchIntervalInSeconds(long)

### Additional context

https://github.com/capawesome-team/capacitor-firebase/discussions/685

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by robingenz** [comment]
Would you like to create a PR?

**Comment by sagaraya** [comment]
@robingenz Unfortunately, due to lack of time, I will not be able to make a pull request for this issue. 

I might be able to make a pull request for another issue https://github.com/capawesome-team/capacitor-firebase/issues/688

**Comment by sagaraya** [comment]
@robingenz I have created a pull request, Could you please review it? https://github.com/capawesome-team/capacitor-firebase/pull/694
