### ISSUE TITLE
bug: skipNativeAuth breaks signInWithGoogle

### ISSUE THREAD

**Issue by howlettga** [capawesome-team/capacitor-firebase#691]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [X] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [ ] Cloud Functions
- [ ] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Version

6.1.0

### Platform(s)

- [X] Android
- [X] iOS
- [ ] Web

### Current behavior

When `skipNativeAuth` is set to `true`, `signInWithApple()` and `signInWithGoogle()` return null `user` and `additionalUserInfo` values of the `signInResult` object. The `credential` value is populated as if the authentication succeeded, but no user is created in the Firebase IdP.

This happens the same on iOS and Android.

If I set `skipNativeAuth` to `false`, everything works as expected. But I cannot use the native Firebase Javascript SDK library.

package.json dependencies:
```
"dependencies": {
    "@angular/animations": "^18.0.0",
    "@angular/cdk": "^18.0.0",
    "@angular/common": "^18.0.0",
    "@angular/compiler": "^18.0.0",
    "@angular/core": "^18.0.0",
    "@angular/fire": "^18.0.1",
    "@angular/forms": "^18.0.0",
    "@angular/platform-browser": "^18.0.0",
    "@angular/platform-browser-dynamic": "^18.0.0",
    "@angular/router": "^18.0.0",
    "@apollo/client": "^3.11.2",
    "@capacitor-firebase/authentication": "^6.1.0",
    "@capacitor/android": "^6.1.2",
    "@capacitor/app": "6.0.0",
    "@capacitor/browser": "6.0.1",
    "@capacitor/camera": "6.0.1",
    "@capacitor/core": "6.1.1",
    "@capacitor/filesystem": "6.0.0",
    "@capacitor/haptics": "6.0.0",
    "@capacitor/ios": "^6.1.2",
    "@capacitor/keyboard": "6.0.1",
    "@capacitor/push-notifications": "6.0.1",
    "@capacitor/status-bar": "6.0.0",
    "@googlemaps/js-api-loader": "^1.16.6",
    "@ionic/angular": "^8.0.0",
    "@ionic/pwa-elements": "^3.2.2",
    "@ionic/storage-angular": "^4.0.0",
    "@maskito/angular": "^2.3.2",
    "@maskito/core": "^2.3.2",
    "apollo-angular": "^7.0.2",
    "date-fns": "^2.29.3",
    "firebase": "^10.12.4",
    "graphql": "^16.8.1",
    "ionicons": "^7.0.0",
    "libphonenumber-js": "^1.10.30",
    "rxjs": "~7.8.0",
    "swiper": "^10.2.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.2"
  },
```

![Screenshot 2024-08-09 at 2 43 14 PM](https://github.com/user-attachments/assets/03c7e234-88ce-43b8-a3f0-6a66b5fe8d34)

### Expected behavior

The documentation has no warning about the `skipNativeAuth` configuration not being valid for these sign in methods. It does specify a different sign in method that this configuration is not valid for. Therefore, I would expect to still be able to sign in via Apple and Google with `skipNativeAuth`.

This [issue](https://github.com/capawesome-team/capacitor-firebase/issues/155) makes me think the skipNativeAuth should work.

### Reproduction

https://github.com/robingenz/capacitor-firebase-authentication-demo

### Steps to reproduce

1. Clone the authentication demo and configure a Firebase project with Apple and Google.
2. Set `skipNativeAuth` to `true`.
3. Sign in with either Google or Apple on device and inspect the `signInResult` object.

### Other information

If this is expected behavior maybe the documentation should be updated. If that is the case, is the solution to providing Google and Apple sign in options on iOS and Android to rip out any direct usage of the Firebase Javascript SDK and solely use this plugin?

### Capacitor doctor

howlettga@~/dev/personal/capacitor-firebase-authentication-bug $ npx cap doctor
[warn] The bundledWebRuntime configuration option has been deprecated. Can be safely deleted.
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

Installed Dependencies:

  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/android: 6.0.0
  @capacitor/ios: 6.0.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
This is the expected behavior. If you skip the authentication, then no user can be returned because no login was performed. `skipNativeAuth` is only intended for use with the Firebase JS SDK.

**Comment by howlettga** [comment]
Thanks. I realized I missed the documentation page on signing into the web layer with the auth token after authenticating. Dropping the link here if someone finds this at a later point: https://github.com/capawesome-team/capacitor-firebase/blob/main/packages/authentication/docs/firebase-js-sdk.md
