### ISSUE TITLE
Authentication: mobile web version signInWithGoogle: Firebase: Error (auth/popup-blocked)

### ISSUE THREAD

**Issue by folsze** [capawesome-team/capacitor-firebase#692]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [X] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [ ] Cloud Functions
- [ ] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Version

^6.1.0

### Platform(s)

- [ ] Android
- [X] iOS
- [ ] Web

### Current behavior

no modal opens, error:
Firebase: Error (auth/popup-blocked)

### Expected behavior

google signin modal opens

### Reproduction

I will provide this soon

### Steps to reproduce

when using this code:

FirebaseAuthentication.signInWithGoogle()

it breaks on mobile web

related issue from firebase js sdk:

https://github.com/firebase/firebase-js-sdk/issues/8033

I am not sure, is this intended to be the default behaviour? Seems weird that it does not use signInWithRedirect by default on mobileweb, to prevent this issue

### Capacitor doctor

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

Installed Dependencies:

  @capacitor/cli: 6.1.1
  @capacitor/core: 6.1.1
  @capacitor/android: 6.1.1
  @capacitor/ios: 6.1.1

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by folsze** [comment]
sorry this is really just a question first, not a bug report. I am simply just not sure whether this plugin is aware of this issue:

https://github.com/firebase/firebase-js-sdk/issues/8033

**Comment by robingenz** [comment]
There is no specific reason why `popup` is the default. Possibly because less setup is required, making it easier to get started. I close this issue because no bug was reported.

**Comment by akroll1** [comment]
I am facing this same issue with the google signin method, the popup does not show on mobile (works on web) when using:

Firebase: 10.13.1 
@capacitor-firebase/authentication: 6.1.0

This method worked with @capacitor-firebase:/authentication: 6.1.0 and firebase 10.12.5. 
These library version were unchanged between my app versions:

@capacitor/app: 6.0.1
@capacitor/core: 6.1.2
@capacitor/ios: 6.1.2

Happy to submit a more detailed bug report, just spent a couple days working through this issue.

**Comment by robingenz** [comment]
@akroll1 This error is thrown in the Firebase SDK when the browser prevents the popup. Unfortunately, Capacitor Firebase has no control over this.
