### ISSUE TITLE
bug: removeAllListeners has been removed from messaging on iOS

### ISSUE THREAD

**Issue by alexstanbury** [capawesome-team/capacitor-firebase#695]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [ ] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [ ] Cloud Functions
- [X] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Version

6.1.0

### Platform(s)

- [ ] Android
- [X] iOS
- [ ] Web

### Current behavior

I cannot use `removeAllListeners`, the binding has been removed in [this commit ](https://github.com/capawesome-team/capacitor-firebase/commit/bbc83147d0140e862225f08e5ed6450d85c35a16#r145412885) with no comment as to why. The API docs still suggest it is available, and it's breaking my app without it.

### Expected behavior

It should exist, how else can listeners be removed?

### Reproduction

It's in this repo...

### Steps to reproduce

Look at [this commit ](https://github.com/capawesome-team/capacitor-firebase/commit/bbc83147d0140e862225f08e5ed6450d85c35a16#r145412885)

### Capacitor doctor

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

Installed Dependencies:

  @capacitor/core: 5.0.0
  @capacitor/cli: 5.0.0
  @capacitor/android: 5.0.0
  @capacitor/ios: 5.0.0

[success] iOS looking great! 👌

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
It was removewd, because it's no longer needed, see https://capacitorjs.com/docs/updating/plugins/6-0#remove-removealllisteners-method.

**Comment by alexstanbury** [comment]
Unfortunately it is needed for me, I am using AngularJS (also can't use ESM) and I have to access the capacitor plugins on the `window.Capacitor.Plugins` global object.

With that method removed, this is the output I see:

![Screenshot 2024-08-15 at 13 23 24](https://github.com/user-attachments/assets/45fd5376-6b73-4ac9-bb34-822b4b706746)

If I add the line back into the development pod, then it works as needed:

![Screenshot 2024-08-15 at 14 33 28](https://github.com/user-attachments/assets/32a97542-b315-49ef-8f0c-b697ff13dab1)

**Comment by robingenz** [comment]
> Is this because I am still using Capacitor 5? If so, AFAIK your docs don't say that it is required to upgrade to Capacitor 6.

Yes, you need to use the latest Capacitor version. This is mentioned [here](https://github.com/capawesome-team/capacitor-firebase/tree/main?tab=readme-ov-file#features). In addition, this package can only be installed with Capacitor 6, see [`peerDependencies`](https://github.com/capawesome-team/capacitor-firebase/blob/cf092aab19e43fe8e880b1877c863e9538c763cf/packages/authentication/package.json#L76). If you force install the package, you are responsible for compatibility.

**Comment by alexstanbury** [comment]
With all due respect, it doesn't say Cap 6 is required, just that it is supported. It installed fine and appears to be working ok for me. Looks like I'll have to maintain a fork. Thanks for your time anyway.
