### ISSUE TITLE
bug: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Iterator org.json.JSONObject.keys()' on a null object reference

### ISSUE THREAD

**Issue by braincomb** [capawesome-team/capacitor-firebase#696]
### Plugin(s)

- [X] Analytics
- [ ] App
- [ ] App Check
- [ ] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [ ] Cloud Functions
- [ ] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Version

6.0.0

### Platform(s)

- [X] Android
- [ ] iOS
- [ ] Web

### Current behavior

When calling `logEvent` with a single `name` parameter, for example:

```ts
 await FirebaseAnalytics.logEvent({
   name: 'some_event',
 });
  ```
  
  It throws an error on the native layer:
  
> 12:01:25.102  V  To native (Capacitor plugin): callbackId: 40108310, pluginId: FirebaseAnalytics, methodName: logEvent
> 12:01:25.102  V  callback: 40108310, pluginId: FirebaseAnalytics, methodName: logEvent, methodData: {"name":"some_event"}
> 12:01:25.102  W  java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Iterator org.json.JSONObject.keys()' on a null object reference
> 12:01:25.102  W  	at io.capawesome.capacitorjs.plugins.firebase.analytics.FirebaseAnalyticsHelper.createBundleFromJson(FirebaseAnalyticsHelper.java:15)
> 12:01:25.102  W  	at io.capawesome.capacitorjs.plugins.firebase.analytics.FirebaseAnalytics.logEvent(FirebaseAnalytics.java:77)
> 12:01:25.102  W  	at io.capawesome.capacitorjs.plugins.firebase.analytics.FirebaseAnalyticsPlugin.logEvent(FirebaseAnalyticsPlugin.java:129)
> 12:01:25.102  W  	at java.lang.reflect.Method.invoke(Native Method)
> 12:01:25.102  W  	at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138)
> 12:01:25.102  W  	at com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:820)
> 12:01:25.102  W  	at com.getcapacitor.Bridge.$r8$lambda$ehFTi5f4HhVNFKTbCKAYDkpQYRA(Unknown Source:0)
> 12:01:25.102  W  	at com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run(Unknown Source:8)
> 12:01:25.102  W  	at android.os.Handler.handleCallback(Handler.java:958)
> 12:01:25.102  W  	at android.os.Handler.dispatchMessage(Handler.java:99)
> 12:01:25.102  W  	at android.os.Looper.loopOnce(Looper.java:230)
> 12:01:25.102  W  	at android.os.Looper.loop(Looper.java:319)
> 12:01:25.102  W  	at android.os.HandlerThread.run(HandlerThread.java:67)

If you provide additional params, there are no errors and it works as expected, e.g:

```ts
 await FirebaseAnalytics.logEvent({
   name: 'some_event',
   params: { method: 'some_param' },
 });
  ```

### Expected behavior

Since event params are optional, I expect that just by providing an event name should not throw an error.

### Reproduction

N/A

### Steps to reproduce

Call `logEvent` with a single event name.

### Capacitor doctor

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

Installed Dependencies:

  @capacitor/cli: 6.1.0
  @capacitor/core: 6.1.0
  @capacitor/android: 6.1.0
  @capacitor/ios: 6.1.0

[success] Android looking great! 👌
[error] Xcode is not installed

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
Yes, but this error is only displayed in Logcat. The plugin call should still be successful, as there is a `try ... catch`, see: https://github.com/capawesome-team/capacitor-firebase/blob/cf092aab19e43fe8e880b1877c863e9538c763cf/packages/analytics/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/analytics/FirebaseAnalyticsHelper.java#L14

**Comment by braincomb** [comment]
Yes, I have verified that the call is successful and the events are being logged. However, when first seeing the errors it made me feel uneasy as if something was broken or didn't work. I know it only shows up on the native layer, but ideally I think the error shouldn't be thrown in the first place if the call is successful.

> Yes, but this error is only displayed in Logcat. The plugin call should still be successful, as there is a `try ... catch`, see:
> 
> https://github.com/capawesome-team/capacitor-firebase/blob/cf092aab19e43fe8e880b1877c863e9538c763cf/packages/analytics/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/analytics/FirebaseAnalyticsHelper.java#L14
