### ISSUE TITLE
bug: Consent for AdPersonalization enables personalization_storage instead of ad_personalization

### ISSUE THREAD

**Issue by MitjaNucic** [capawesome-team/capacitor-firebase#703]
### Plugin(s)

- [X] Analytics
- [ ] App
- [ ] App Check
- [ ] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [ ] Cloud Functions
- [ ] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Version

6.1.0

### Platform(s)

- [ ] Android
- [ ] iOS
- [X] Web

### Current behavior

It looks like calling 
```
 await FirebaseAnalytics.setConsent({
    type: ConsentType.AdPersonalization,
    status: ConsentStatus.Granted
  })

```
Is enabling personalization_storage instead of ad_personalization the correct behavior?
Code from lib:
```
async setConsent(options) {
            const status = options.status === exports.ConsentStatus.Granted ? 'granted' : 'denied';
            const consentSettings = {};
            switch (options.type) {
             ...
                case exports.ConsentType.AdPersonalization:
                    consentSettings.personalization_storage = status;
                    break;
                ...
                case exports.ConsentType.PersonalizationStorage:
                    consentSettings.personalization_storage = status;
                    break;
            }
            analytics.setConsent(consentSettings);
        }
```
Code to reproduce:
```
watch(marketingConsent, async (newValue) => {
  await FirebaseAnalytics.setConsent({
    type: ConsentType.AdPersonalization,
    status: marketingConsent ? ConsentStatus.Granted : ConsentStatus.Denied,
  })
  await FirebaseAnalytics.setConsent({
    type: ConsentType.AdStorage,
    status: marketingConsent ? ConsentStatus.Granted : ConsentStatus.Denied,
  })
  await FirebaseAnalytics.setConsent({
    type: ConsentType.AdUserData,
    status: marketingConsent ? ConsentStatus.Granted : ConsentStatus.Denied,
  })
})
```
![image](https://github.com/user-attachments/assets/689dde67-be68-4c3a-ad68-26e91159d574)

### Expected behavior

Consent status for AdPersonalization should enable ad_personalization and not personalization_storage

### Reproduction

https://github.com/capawesome-team/.capacitor-app

### Steps to reproduce

Explained above.

### Capacitor doctor

Installed Dependencies:

  @capacitor/core: 6.1.2
  @capacitor/ios: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/cli: 6.1.2

[success] Android looking great! 👌
[error] Xcode is not installed

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [x] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
Yes, this should be a bug. Would you be willing to create a PR?

**Comment by bor-creatim** [comment]
Something like this should probably suffice:

```patch
diff --git a/packages/analytics/src/web.ts b/packages/analytics/src/web.ts
index 7ee8262..f1a5c75 100644
--- a/packages/analytics/src/web.ts
+++ b/packages/analytics/src/web.ts
@@ -37,7 +37,7 @@ export class FirebaseAnalyticsWeb
     const consentSettings: ConsentSettings = {};
     switch (options.type) {
       case ConsentType.AdPersonalization:
-        consentSettings.personalization_storage = status;
+        consentSettings.ad_personalization = status;
         break;
       case ConsentType.AdStorage:
         consentSettings.ad_storage = status;
```
