### ISSUE TITLE
bug: Capacitor/Http API call is not working after integrating Crashlytics in Android

### ISSUE THREAD

**Issue by mantosh59** [capawesome-team/capacitor-firebase#718]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [ ] Authentication
- [X] Crashlytics
- [ ] Cloud Firestore
- [ ] Cloud Functions
- [ ] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Version

6.1.0

### Platform(s)

- [X] Android
- [ ] iOS
- [ ] Web

### Current behavior

Capacitor HTTP not working.

### Expected behavior

API calls should work after Crashlytics integration

### Reproduction

API call not working in Capacitor Android

### Steps to reproduce

1. Integrate Crashlytics in existing Capacitor app with Capacitor HTTP enabled in capacitor.config.ts.
2. After complete integration in Android. Run the application and do some API call.

### Capacitor doctor

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

Installed Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/ios: 6.1.2

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
This should be a bug in the Firebase Crashlytics SDK or the Capacitor HTTP plugin. This plugin is just a simple wrapper for the Firebase Crashlytics SDK. For this reason I'm closing this issue.
