### ISSUE TITLE
bug: Firebase Crashlytics iOS testCrash not passing message option

### ISSUE THREAD

**Issue by GoethelHB** [capawesome-team/capacitor-firebase#720]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [ ] Authentication
- [X] Crashlytics
- [ ] Cloud Firestore
- [ ] Cloud Functions
- [ ] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Version

6.1.0

### Platform(s)

- [ ] Android
- [X] iOS
- [ ] Web

### Current behavior

.crash(options) not adding the message to fatalError() call

### Expected behavior

.crash(options) adding the message to fatalError(message) call

### Reproduction

-

### Steps to reproduce

1. Import Crashlytics and run the crash function with message
import { FirebaseCrashlytics } from "@capacitor-firebase/crashlytics";
void FirebaseCrashlytics.crash({message: "native TestCrash"});
2. build it for iOS and run it

### Capacitor doctor

-

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
Would you be willing to submit a PR?

**Comment by GoethelHB** [comment]
Ok, I will submit one tomorrow.
