### ISSUE TITLE
bug: Capacitor-firebase + Capacitor-mlkit version conflicts

### ISSUE THREAD

**Issue by gerardopar** [capawesome-team/capacitor-firebase#750]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [X] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [ ] Cloud Functions
- [ ] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Version

6.2.0

### Platform(s)

- [ ] Android
- [X] iOS
- [ ] Web

### Current behavior

We are currently using the [capacitor-mlkit](https://github.com/capawesome-team/capacitor-mlkit) and [capacitor-firebase](https://github.com/capawesome-team/capacitor-firebase) plugins in our app.

With the following versions, everything works smoothly:

```json
"@capacitor-firebase/authentication": "^6.1.0",
"@capacitor-mlkit/barcode-scanning": "6.1.0",
"firebase": "^10.14.1"
```

However, we recently upgraded to the latest versions (`6.2.0`) to address an issue with Google login on iOS. After the update, versioning conflicts emerged between the plugins:

```json
"@capacitor-firebase/authentication": "^6.2.0",
"@capacitor-mlkit/barcode-scanning": "6.2.0",
"firebase": "^11.0.1"
```

### Error Details:

The issue stems from a version incompatibility with `GoogleUtilities/Environment`. Specifically:

- `FirebaseAuth` requires `GoogleUtilities/Environment` version 8.0 or above.
- `GoogleMLKit` depends on version 7.2.

This discrepancy causes CocoaPods to fail during installation. Here’s a screenshot of the error:

![Screenshot 2024-11-05 at 9 56 42 AM](https://github.com/user-attachments/assets/cce1b7b7-b547-4e38-9613-36f4cfc6b2f9)

Is there a recommended approach to resolve these conflicts, or are there planned updates to improve compatibility across these dependencies?

Thank you!

### Expected behavior

We expected the version bumps to work as expected

### Reproduction

https://github.com

### Steps to reproduce

the following pkgs should cause the issue we are running into

``` json
"@capacitor-firebase/authentication": "^6.2.0",
"@capacitor-mlkit/barcode-scanning": "6.2.0",
"firebase": "^11.0.1",
```

### Capacitor doctor

```
run pnpm i 
run npx cap sync 
```

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
Please install the latest version of the ML Kit Barcode Scanning plugin using the `next` tag:

```
npm install @capacitor-mlkit/barcode-scanning@next
npx cap sync
```

This is due to the following issue: https://github.com/capawesome-team/capacitor-mlkit/pull/179.

**Comment by gerardopar** [comment]
> Please install the latest version of the ML Kit Barcode Scanning plugin using the `next` tag:
> 
> ```
> npm install @capacitor-mlkit/barcode-scanning@next
> npx cap sync
> ```
> 
> This is due to the following issue: [capawesome-team/capacitor-mlkit#179](https://github.com/capawesome-team/capacitor-mlkit/pull/179).

@robingenz hey hey, thanks for the response ... will try shortly & report any changes 👍🏽

**Comment by gerardopar** [comment]
@robingenz 

the following fixed the package version conflicts 

1. installed  `@capacitor-mlkit/barcode-scanning@next` with the next tag
   - `7.0.0-next.1`
2. deleted my `Podfile.lock`
3. ran `pod install`
4. ran `npx cap sync`

this allowed me to build the app with the expected packages 


strangely i started encountering the follow on simulators running `ios 18.1` when i try using google login, works fine on versions running `ios 17`

![Screenshot 2024-11-05 at 2 41 48 PM](https://github.com/user-attachments/assets/8cf4d8c1-d253-414f-beda-3a38c423dc54)

these are my packages 

```json
"@capacitor-firebase/authentication": "^6.2.0",
"@capacitor-mlkit/barcode-scanning": "7.0.0-next.1",
```

**Comment by gerardopar** [comment]
it seems like SMS login is also having this issue

passwordless & apple login seem to be working as expected

**Comment by robingenz** [comment]
Please create a new issue for that. I close this issue since the version conflict is resolved.
