### ISSUE TITLE
bug: build issue in ios

### ISSUE THREAD

**Issue by AE1NS** [capawesome-team/capacitor-firebase#753]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [X] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [ ] Cloud Functions
- [ ] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Version

6.2.0

### Platform(s)

- [ ] Android
- [X] iOS
- [ ] Web

### Current behavior

Installing the pods is not working because of incompatible dependencies (GTMSessionFetcher/Core).

### Expected behavior

Installing the pods should work.

### Reproduction

-

### Steps to reproduce

Im not an ios expert, but I try to explain with references, what should be the reason for this issue. (Refering to https://guides.cocoapods.org/syntax/podspec.html#dependency)

https://github.com/capawesome-team/capacitor-firebase/blob/main/packages/authentication/CapacitorFirebaseAuthentication.podspec
Inside this podspec a dependency to 'FirebaseAuth ~> 11.0' is set. When I try to install the pods, it chooses the version 11.4.0.
There is also another dependency in this podspec to 'GoogleSignIn 7.1.0'.

**FirebaseAuth 11.4.0 podspec (released 3 weeks ago)**
https://github.com/CocoaPods/Specs/blob/master/Specs/6/3/6/FirebaseAuth/11.4.0/FirebaseAuth.podspec.json
Here is a dependency to GTMSessionFetcher/Core '>= 3.4, < 5.0'

FirebaseAuth 11.3.0 had this dependency set to '~> 3.4'

**GoogleSignIn 7.1.0 podspec**
https://github.com/CocoaPods/Specs/blob/master/Specs/d/4/0/GoogleSignIn/7.1.0/GoogleSignIn.podspec.json
Here is a dependency to GTMSessionFetcher/Core '~> 3.3'

That seems to be the reason why the pod installation throws an error, because it can not decide which GTMSessionFetcher/Core version to install.

ChatGPT answered this:
```
If you specify both ~> 3.3 and >= 3.4, < 5.0 as dependencies in a Podfile or Podspec, CocoaPods will detect a version conflict and likely produce an error.
Reason

When installing, CocoaPods checks all dependencies and their version constraints:

    ~> 3.3 allows any version from 3.3.0 up to, but not including, 4.0.0.
    >= 3.4, < 5.0 only allows versions from 3.4.0 up to, but not including, 5.0.0.

Since 3.3.x versions are excluded by the >= 3.4 constraint, there is no version that satisfies both conditions.
Result

    CocoaPods will find no version range that meets both constraints.
    You will get an error due to this version conflict, and the pods will not be installed.

Suggested Solution

To resolve this conflict, adjust the constraints as follows:

    If you only need versions from 3.4.0 up to 5.0.0, change ~> 3.3 to ~> 3.4.
    If 3.3.x versions are also acceptable, remove the >= 3.4 constraint and use ~> 3.3 alone.

Either solution ensures there is only one consistent version constraint for CocoaPods to work with.
```

### Capacitor doctor

-

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
Hi @AE1NS, thank you for your request. I need a minimal, reproducible example to debug the issue.

**Comment by AE1NS** [comment]
I understand your requirement for a reproduction code, but unfortunately I cant afford the time to create one right now. I will close this for now and maybe someone other will create issue for that. So long I stay at the 6.1.0.

If others read this, as workaround you could add the FirebaseAuth dependency to your project podfile with 7.3.0.
