### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by Tobertet** [capawesome-team/capacitor-firebase#780]
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [ ] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [X] Cloud Functions
- [ ] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Version

6.3.1

### Platform(s)

- [X] Android
- [ ] iOS
- [ ] Web

### Current behavior

It looks like when I return an array of arrays, the inner array is not being serialized correctly. 

Android example
![image](https://github.com/user-attachments/assets/39da379a-707e-45fd-a63d-471209478b20)

### Expected behavior

The exact same code on web works as expected.

Web example
![image](https://github.com/user-attachments/assets/22587e82-e3e6-440b-a05c-511ed9502f8f)

### Reproduction

Can't really use the template for this

### Steps to reproduce

Have a function in firebase that returns an object with an array of arrays. Example:

```
{
  squares: [
    [
      { kind: "blocked", position: { row: 0, column: 0 } },
      { kind: "blocked", position: { row: 0, column: 1 } },
    ],
    [
      { kind: "blocked", position: { row: 0, column: 0 } },
      { kind: "blocked", position: { row: 0, column: 1 } },
    ],
  ];
}

```

Now test it using Android and Web. The inner array is different in both cases.

### Capacitor doctor

  @capacitor/cli: 6.2.0
  @capacitor/core: 6.2.0
  @capacitor/android: 6.2.0

Installed Dependencies:

  @capacitor/cli: 6.1.1
  @capacitor/core: 6.1.1
  @capacitor/android: 6.1.1

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
Would you be willing to create a PR?

**Comment by Tobertet** [comment]
Yeah I would, but I would need some guidance. Where may the issue be?

**Comment by robingenz** [comment]
The issue must be in this [CallResult](https://github.com/capawesome-team/capacitor-firebase/blob/main/packages/functions/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/functions/classes/results/CallResult.java) class, see: https://github.com/capawesome-team/capacitor-firebase/blob/ded83c98e473b7db4ddba6a380fc31254bc70ba2/packages/functions/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/functions/classes/results/CallResult.java#L22
