### ISSUE TITLE
feat: support Firebase Remote Config

### ISSUE THREAD

**Issue by robingenz** [capawesome-team/capacitor-firebase#9]
**Is your feature request related to a problem? Please describe:**

Firebase Remote Config is not currently supported.

**Describe the solution you'd like:**

Add a Firebase Remote Config plugin.

**Describe alternatives you've considered:**

**Additional context:**

**Comment by HeikoKanzler** [comment]
+1

**Comment by tlebeitsuk** [comment]
+1

**Comment by carlossk** [comment]
it would be great to have this plugin

**Comment by robingenz** [comment]
Anyone want to test the new plugin? I would like to get some feedback.

```
npm i @capacitor-firebase/remote-config@1.2.0-dev.8dd4ad6.1668633721
```
Docs: https://github.com/capawesome-team/capacitor-firebase/blob/feat/issue-9/packages/remote-config/README.md
